### DISCUSSION TITLE
Mapping properties with hyphen to environment variables

### DISCUSSION THREAD

**Discussion by edeandrea** [quarkusio/quarkus#22028] [Q&A] [answered]
How do I map properties containing a hyphen into an environment variable? I've read through the [MicroProfile Config environment variable mapping rules](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#environment-variables-mapping-rules) and can't seem to figure out how to map a property containing a hyphen correctly to an environment variable.

I have an application that uses the MicroProfile REST client and am trying to create a docker compose file for that. The docker compose needs to override the URL property via an environment variable.

The property in question is `quarkus.rest-client.hero-client.url`.

I've tried `QUARKUS_REST-CLIENT_HERO-CLIENT_URL`, `QUARKUS_RESTCLIENT_HEROCLIENT_URL`, and `QUARKUS_REST_CLIENT_HERO_CLIENT_URL` and none of those work.

The only thing I've been able to get to work is this

```yaml
environment:
  QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://fights-db:5432/fights_database
  KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://fights-kafka:9092
  quarkus.rest-client.hero-client.url: http://rest-heroes-java11:8083
```
