### DISCUSSION TITLE
"Partial matching" for `@ConfigMapping`

### DISCUSSION THREAD

**Discussion by famod** [quarkusio/quarkus#22063] [Q&A] [answered]
Hi all (mainly @radcortez I guess)!

Is there any way to map a config structure like:
```yaml
provider:
  providerA:
    connector:
      client-endpoint-url: http://providerA
      client-cert:
        key-alias: providerA
        key-password: ****
    schedule:
      foo: "bar"
  providerB:
    connector:
      client-endpoint-url: http://providerB
      client-cert:
        key-alias: providerB
        key-password: ****
    schedule:
      foo: "baz"
```

to a `@ConfigMapping` that only contains a subset of properties, e,g,:
```java
@ConfigMapping(prefix = "provider")
public interface ProviderConfig {

    Map<String, ConnectorConfig> connector();

    interface ConnectorConfig {
        KeystoreKeyReferenceProperties clientCert();
    }
}
```
*but **without** switching off any global validation*?

The first naive approach resulted in:
```
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	provider.providerA.schedule.foo does not map to any root
	provider.providerB.schedule.foo does not map to any root
```

I don't want to map the schedules because those are referenced separately via `@Scheduled`.

Please note that the list of "providers" should be as dynamic as possible, hence the `Map`.

Could I alternatively get `ConnectorConfig` programmatically? I suppose not?

Thanks!
