### DISCUSSION TITLE
Use environment variables or application.ini variables in files in src/main/kubernetes

### DISCUSSION THREAD

**Discussion by loban** [quarkusio/quarkus#24785] [Q&A]
I want to extend or add additional resources to the generated `kubernetes.yml`, `knative.yml`, etc. files. The documentation states to add a file with the same name to `src/main/kubernetes/`, and add stuff to that. Great.

But, I would like to use environment variables, as well as properties set in `application.ini` in there. Does quarkus provide a way? If not, could this be a feature request?

[a comment by an automated account is not shown]

**Comment by geoand** [comment]
Does https://quarkus.io/guides/deploying-to-kubernetes#env-vars not fit your needs?

**Reply by loban** [reply]
I am using that already, to pass information to the deployed application, but supposed I want to do something like this: I want to include, e.g. generating a secret in my `kubernetes.yml` file. So, in my `main/kubernetes/kubernetes.yml` file, I add

```
---
apiVersion: v1
data:
  .dockerconfigjson: ${SECRET_VALUE}
kind: Secret
metadata:
  name: ${quarkus.application.name}
type: kubernetes.io/dockerconfigjson
```

Where the secret name could grab a value from my quarkus configuration, and the secret values could be stored in my `.env` (or stored in my CI/CD), so that the actual secret is not stored in the codebase.
