### DISCUSSION TITLE
Generation of Role and RoleBinding fails if usage of secrets in kubernetes-config is enabled

### DISCUSSION THREAD

**Discussion by wgresshoff** [quarkusio/quarkus#24932] [Q&A] [answered]
Hi, 
I have a multi-module project with Kubernetes and Kubernetes Config included. When I updated from Quarkus 2.6.1 to 2.8.0 suddenly the generation of K8s manifests failed. I figured out the problem is coming from
```
quarkus:
  kubernetes-config:
    enabled: true
    ...
    secrets:
      ~: ...
      enabled: true
```
leading to `java.lang.IllegalStateException: Expected at least one of: Deployment,DeploymentConfig,Service,StatefulSet,Pipeline,Task to be present.`When I set
`quarkus.kubernetes-config.secrets.enabled=false` the K8s manifests were created. The error happens in io.quarkus.kubernetes.deployment.AddRoleResourceDecorator so I guess generation of the Role for viewing secrets fails.

[a comment by an automated account is not shown]
