### DISCUSSION TITLE
Declare a bom in maven dependencyManagement in extension's codestart.yml?

### DISCUSSION THREAD

**Discussion by joes** [quarkusio/quarkus#25942] [Q&A] [answered]
I am attempting to create an extension with a codestart based on this documentation:

 - https://quarkus.io/guides/building-my-first-extension
 - https://quarkus.io/guides/writing-extensions 
 - https://quarkus.io/guides/extension-codestart
 - https://github.com/ia3andy/aloha-code

It is working out fine (mostly) but I am having a problem with declaring quarkus camel dependencies that aligns with those used by the targeted Quarkus platform version.

I was trying to declare the camel-quarkus dependencies (without versions):

```yml
name: my-org-camel-integration-codestart
ref: my-org-camel-integration
type: code
tags: extension-codestart
metadata:
  title: My Organisation Camel Integration Codestart
  description: Quarkus extension codestart for our organisation
  related-guide-section: https://wiki.somewhere.com/to/be/decided/later/README.md
language:
  base:
    dependencies:
      - org.apache.camel.quarkus:camel-quarkus-file-deployment
      - org.apache.camel.quarkus:camel-quarkus-file
      - org.apache.camel.quarkus:camel-quarkus-core
      - org.apache.camel.quarkus:camel-quarkus-yaml-dsl
      - org.apache.camel.quarkus:camel-quarkus-caffeine
      - org.apache.camel.quarkus:camel-quarkus-bean
      # and more...
```

Those do get included in the generated project's `pom.xml` as expected.

But one would also need the generated project's pom.xml to include the bom  `io.quarkus.platform:quarkus-camel-bom:${quarkus.version}` for those camel dependencies:

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <!-- Can I and how do I "inject" the quarkus-camel-bom? -->
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-camel-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

Is there any way for me to get the bom included in the generated project's `dependencyManagement` from a codestart extension?

[a comment by an automated account is not shown]
