### DISCUSSION TITLE
Quarkus and Skaffold won't build

### DISCUSSION THREAD

**Discussion by osbornk** [quarkusio/quarkus#26827] [Community]
I am using Gradle, Jib, and Skaffold to build a Docker image. I can build a Docker image on the CLI locally like this with no problem:

```
./gradlew build -Dquarkus.container-image.build=true -x test
```

But it fails to build with `skaffold build`. Here is my skaffold.yaml:

```
apiVersion: skaffold/v2beta27
kind: Config
build:
  platforms: ["linux/amd64"]
  artifacts:
    - image: 280296955917.dkr.ecr.us-east-2.amazonaws.com/scheduler
      jib:
        args: [ '-DskipTests' ]
```

I get this error:

```
Error checking cache.
getting hash for artifact "myproject": getting dependencies for "myproject": could not fetch dependencies for workspace .: initial Jib dependency refresh failed: failed to get Jib dependencies: running [/Users/kosborn/git/fulcrumapp/scheduler/gradlew _skaffoldFailIfJibOutOfDate -Djib.requiredVersion=1.4.0 :_jibSkaffoldFilesV2 -q --console=plain]
 - stdout: ""
 - stderr: "\nFAILURE: Build failed with an exception.\n\n* What went wrong:\nTask '_skaffoldFailIfJibOutOfDate' not found in root project 'myproject'.\n\n* Try:\n> Run gradlew tasks to get a list of available tasks.\n> Run with --stacktrace option to get the stack trace.\n> Run with --info or --debug option to get more log output.\n> Run with --scan to get full insights.\n\n* Get more help at https://help.gradle.org\n\nBUILD FAILED in 938ms\n"
 - cause: exit status 1
```

I have the `quarkus-container-image-jib` extension, which looks like a wrapper around Jib. Is that causing a problem with Skaffold?

Any help would be much appreciated.
