### DISCUSSION TITLE
Quarkus Gelf is left-padding traceId with 0s

### DISCUSSION THREAD

**Discussion by wabrit** [quarkusio/quarkus#27305] [Community]
I'm using Quarkus 2.11.2.Final with the following gelf config:

```yaml
quarkus:
  log:
    handler:
      gelf:
        enabled: true
        host: ...
        port: ...
        include-full-mdc: true
        include-log-message-parameters: false
```

The host and port are targeting a logstash server hooked into elastic search.

Looking at the resulting traces in kibana, the traceId (which arrives in my microservice courtesy of an inbound REST request from a gateway) is getting 0-padded:

First log from gateway:

```
traceId: 4dacb8d2ecda7fef
spanId: 4dacb8d2ecda7fef 
service: gateway
msg: calling my-service to get stuff
```

Second log as gateway calls into my-service

```
traceId: 00000000000000004dacb8d2ecda7fef 
spanId: 7084a1f3b7b057c1 
service: my-service 
msg: Request to return some stuff
```

I don't know where the 0-padding is coming from, but it means that its inconvenient to do cross-component tracing through kibana as you have to manually specify a traceId filter like `traceId: is one of <x> or <0-padded x>`.

Although 128-bit traceIds are no doubt preferable, with a mixed economy of components some of which can only generate 64-bit, it would be useful if gelf were able to propagate received 64-bit traceIds without padding.
