### DISCUSSION TITLE
When will jdk 19 be supported?

### DISCUSSION THREAD

**Discussion by TheBlindM** [quarkusio/quarkus#27350] [Community]
When will it officially support jdk 19, I can't wait to use it in the project, I want to show it off with my friends！！！

**Comment by maxandersen** [comment]
Quarkus should work with 19 in jvm mode. 

If You See issues please report then.

**Reply by TheBlindM** [reply]
When will the jdk19 version of grallvm be supported?

**Reply by maxandersen** [reply]
What fails when You try use it?

**Reply by DaHoC** [reply]
If you want to build native with GraalVM and JDK19, what worked for me was following entry in the application.yaml (or application.properties respectively, see https://quarkus.io/guides/native-reference#configure-quarkus-properties):

```
quarkus:
  native:
    container-build: true
    # See https://quay.io/repository/quarkus/ubi-quarkus-graalvmce-builder-image?tab=tags
    builder-image: quay.io/quarkus/ubi-quarkus-graalvmce-builder-image:22.3-java19
```
