### DISCUSSION TITLE
Keycloak DevService not starting on enabled project

### DISCUSSION THREAD

**Discussion by InfoSec812** [quarkusio/quarkus#27967] [Q&A] [answered]
I have the following dependencies installed:

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-keycloak-authorization</artifactId>
    </dependency>
```

I have the following configuration:

```
"%localdev":
  quarkus:
    quinoa:
      enable-spa-routing: true
      dev-server:
        port: 3000
      package-manager-command:
        build: npm run build:quinoa
    oidc:
      application-type: web-app
      discovery-enabled: false
      authorization-path: /protocol/openid-connect/auth
      # Token endpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/token
      token-path: /protocol/openid-connect/token
      # JWK set endpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/certs
      jwks-path: /protocol/openid-connect/certs
      # UserInfo endpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/userinfo
      user-info-path: /protocol/openid-connect/userinfo
      # Token Introspection endpoint: http://localhost:8180/realms/quarkus/protocol/openid-connect/tokens/introspect
      introspection-path: /protocol/openid-connect/tokens/introspect
    keycloak:
      devservices:
        realm-path: ${PWD}
        enabled: true
```

When I start my application in dev mode:

`./mvnw clean compile quarkus:dev -Dquarkus.profile=localdev`

My PostgreSQL container for the application starts and my liquibase migrations happen and my quinoa webapp get's proxied correctly, **BUT** the Keycloak container does not get started??

I see no errors related to the start of the containers and I see no indication that it ever tried to even pull the container image.

Any suggestions would be greatly appreciated!

Cheers,

FYI: Vital details:

OS: MacOS 12.5.1
Podman: 4.2.1
Quarkus Version: 2.12.2.Final

[a comment by an automated account is not shown]
