### DISCUSSION TITLE
@ConfigMapping  @WithConverter and application.yaml

### DISCUSSION THREAD

**Discussion by flicus** [quarkusio/quarkus#28979] [Q&A] [answered]
Hello, i am trying to have this configuration in my application.yaml:

```
app:
  birthdays:
    - name: John
      date: 12/12/1980
    - name: Jack
      date: 19/08/1980
```
For this i have such a POJO:
```
public class Person {
    private String name;
    private String date;
}
```

this config mapping class:

```
@ConfigMapping(prefix = "app")
public interface BirthdayConfig {
    @WithConverter(PersonConverter.class)
    List<Person> birthdays();
}
```
And a PersonConverter class which is now just printing the incoming string.
The problem is the string coming as:

{"birthdays": [{"name": "John"

Is this a bug or i doing something wrong?

<quarkus.platform.version>2.13.3.Final</quarkus.platform.version>
