### DISCUSSION TITLE
io.quarkus.platform as default for quarkus.platform.group-id in QuarkusCodestartTest?

### DISCUSSION THREAD

**Discussion by joes** [quarkusio/quarkus#29260] [Q&A]
The `pom.xml` that is generated by my extension project's integration tests (by way of @RegisterExtension) in `integration-tests/target/quarkus-codestart-test/my-extension-c0b1482a-0b6f-4469-9e6a-e0339a2d308e/real-data/java` has `io.quarkus` as `quarkus.platform.group-id`:

```xml
<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
```

Should that not be `io.quarkus.platform` by default @ia3andy ? This does seem to be the case if a codestart is invoked by the maven mojo `io.quarkus.platform:quarkus-maven-plugin:2.13.4.Final:create` as well as as `quarkus create app` so I think it would be nice if the project generated by the integration-tests was aligned with these.

For that to happen `QuarkusCodestartTest.quarkusBomGroupId` could be adjusted here: 

https://github.com/quarkusio/quarkus/blob/402107d47a2f39187f2bc8e87f165ec563e5d297/independent-projects/tools/devtools-testing/src/main/java/io/quarkus/devtools/testing/codestarts/QuarkusCodestartTest.java#L108-L110

Do you agree @ia3andy? Should I make this a pull request?

[a comment by an automated account is not shown]

**Reply by joes** [reply]
Not actually sure that the fix I suggest would fix the problem. 

Tried setting `quarkusBomGroupId` using `withQuarkusBom` on the the builder like this:

```java
@RegisterExtension
    public static QuarkusCodestartTest codestartTest = QuarkusCodestartTest.builder()
        .languages(Language.JAVA)
        .setupStandaloneExtensionTest("se.kristinehamn.quarkus:khbro-camel-integration")
        .codestarts("config-yaml")
        .withQuarkusBom("io.quarkus.platform", "2.13.4.Final")
        .build();
```

But then what happens is that no `pom.xml` is generated at all.

So, I am clearly not understanding something here.

**Reply by joes** [reply]
Must have been another problem, the `pom.xml` is now indeed generated as I want it with:

<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>

That is, if I set `.withQuarkusBom("io.quarkus.platform", "2.13.4.Final")` manually.

**Reply by joes** [reply]
And the whole reason that I wanted `io.quarkus.platform` in the first place is that the generated project was not able to resolve `quarkus-camel-bom` in group `io.quarkus`:

```xml
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-camel-bom</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
```

**Reply by aloubyansky** [reply]
The intention was to keep `io.quarkus` for extensions and `io.quarkus.platform` for applications.
@joes which extension are working on? How do you define a dependency on CEQ?

**Reply by joes** [reply]
@aloubyansky I am indeed generating an application in an integration test for an extension:

```java
public class KhbroCamelIntegrationCodestartTest {

    @RegisterExtension
    public static QuarkusCodestartTest codestartTest = QuarkusCodestartTest.builder()
        .languages(Language.JAVA)
        .setupStandaloneExtensionTest("se.kristinehamn.quarkus:khbro-camel-integration")
        .withQuarkusBom("io.quarkus.platform", "2.13.4.Final")
        .codestarts("config-yaml")
        .build();

    /**
     * This test runs the build (with tests) on generated projects for all selected languages
     */
    @Test
    void buildAllProjects() throws Throwable {
        codestartTest.buildAllProjects();
    }
}
```

If I do *not* set `.withQuarkusBom("io.quarkus.platform", "2.13.4.Final")` the generated applications pom.xml becomes:

```xml
<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
```

rather than the expected:

```xml
<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
```

I expect this because `io.quarkus.platform` is what I get for `quarkus.platform.group-id` when using the maven mojo for creating an app or if using `quarkus create app myapp`. My thinking was that `QuarkusCodestartTest.quarkusBomGroupId` should be aligned with this.

**Reply by joes** [reply]
I see that I originally mentioned `quarkus create extension` when I meant to say `quarkus create app` - fixing that now. It is an app that is being generated in all these cases.

**Reply by joes** [reply]
@aloubyansky 

> which extension are working on?

Just an in-house extension that works as a starter for camel integrations and applies Open API security definitions on Camel routes automatically based on configured `quarkus.http.auth.permission` settings.

> How do you define a dependency on CEQ?

Not sure what CEQ refers to so I cannot answer.

**Reply by aloubyansky** [reply]
CEQ is short for Camel Extensions for Quarkus

**Reply by joes** [reply]
Sorry, I am still not sure about the CEQ question, are you asking for some specific maven dependency? Could you provide me the maven groupId and artifactId and I shall check for you @aloubyansky.

**Reply by aloubyansky** [reply]
What do you use from the quarkus-camel-bom? Do you depend on any specific extension managed in the quarkus-camel-bom?

**Reply by joes** [reply]
I use quite a lot of dependencies from that bom but none of these are extensions @aloubyansky 

The codestarter for my extension has a `runtime/src/main/codestarts/quarkus/khbro-camel-integration-codestart/base/pom.xml` defining the bom:

```xml
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-camel-bom</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

The codestarter's pom.xml is merged with the generated project as defined by `smart-pom-merge` in  `codestart.yml`:

```yaml
#...
output-strategy:
  "pom.xml": smart-pom-merge
```

And the same `codestart.yml` brings in these dependencies from the `quarkus-camel-bom` to the project generated by the codestarter:
```yaml
language:
  base:
    dependencies:
      - org.apache.camel.quarkus:camel-quarkus-bean
      - org.apache.camel.quarkus:camel-quarkus-bean-validator
      - org.apache.camel.quarkus:camel-quarkus-caffeine
      - org.apache.camel.quarkus:camel-quarkus-core
      - org.apache.camel.quarkus:camel-quarkus-cron
      - org.apache.camel.quarkus:camel-quarkus-csv
      - org.apache.camel.quarkus:camel-quarkus-direct
      - org.apache.camel.quarkus:camel-quarkus-file
      - org.apache.camel.quarkus:camel-quarkus-freemarker
      - org.apache.camel.quarkus:camel-quarkus-ftp
      - org.apache.camel.quarkus:camel-quarkus-headersmap
      - org.apache.camel.quarkus:camel-quarkus-http
      - org.apache.camel.quarkus:camel-quarkus-jackson
      - org.apache.camel.quarkus:camel-quarkus-jslt
      - org.apache.camel.quarkus:camel-quarkus-jsonpath
      - org.apache.camel.quarkus:camel-quarkus-openapi-java
      - org.apache.camel.quarkus:camel-quarkus-quartz
      - org.apache.camel.quarkus:camel-quarkus-rest
      - org.apache.camel.quarkus:camel-quarkus-rest-openapi
      - org.apache.camel.quarkus:camel-quarkus-timer
      - org.apache.camel.quarkus:camel-quarkus-xj
      - org.apache.camel.quarkus:camel-quarkus-xslt-saxon
      - org.apache.camel.quarkus:camel-quarkus-yaml-dsl
      - org.apache.camel.quarkus:camel-quarkus-microprofile-health
      - org.apache.camel.quarkus:camel-quarkus-jta
      - org.apache.camel.quarkus:camel-quarkus-jpa
      - org.apache.camel.quarkus:camel-quarkus-log-deployment
```

None of these dependencies are other extensions.
