### DISCUSSION TITLE
How to set Docker image name when "testcontainers.reuse.enable=true"?

### DISCUSSION THREAD

**Discussion by jehrenzweig-leagueapps** [quarkusio/quarkus#31171] [Q&A]
Today, I setup a Quarkus application that uses DevServices to provision a MySQL database:
```
"%dev":
  quarkus:
    profile: dev
    datasource:
      db-kind: mysql
      devservices:
        enabled: true
        username: root
        password: messingaround
        db-name: TEST_DB
        port: 54321
````

I then created a new `.testcontainers.properties` file in my macOS user profile's root folder, to ensure the Docker image wasn't destroyed when Quarkus stopped running locally:
```
cd ~/
echo testcontainers.reuse.enable=true > .testcontainers.properties
```

Good stuff.  However, I'd like to be able to set the name of the Docker image, so that I more easily recognize it when I'm looking at my list of images in Docker Desktop.  Is there any way of doing this?
