### DISCUSSION TITLE
Set environment variables in Quarkus to deploy in Openshift

### DISCUSSION THREAD

**Discussion by aelzo1209** [quarkusio/quarkus#31531] [Q&A]
I want to deploy my quarkus application in Openshift. I am trying to make the connection to the database with some environment variables whose value will be indicated in a configmap file and in a secrets file.

I have a my-configmap.yaml like:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  db-url: jdbc:postgresql://postgresql/databasename
```

I also have a my-secret.yaml:

```
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  db-username: username
  db-password: password
```

My application.properties file:

```
quarkus.openshift.app-config-map=my-config-map
quarkus.openshift.app-secret=my-secret
quarkus.openshift.env.configmaps=my-config-map
quarkus.openshift.env.secrets=my-secret
quarkus.openshift.env.mapping.DB_URL.from-configmap=my-config-map
quarkus.openshift.env.mapping.DB_URL.with-key=db-url
quarkus.openshift.env.mapping.DB_USERNAME.from-secret=my-secret
quarkus.openshift.env.mapping.DB_USERNAME.with-key=db-username
quarkus.openshift.env.mapping.DB_PASSWORD.from-secret=my-secret
quarkus.openshift.env.mapping.DB_PASSWORD.with-key=db-password

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}
```

I have tried in several ways (quarkus.kubernetes.env... instead of quarkus.openshift.env) but I can't get it to work. I have also tried to create a deployment config from openshift in which I indicate the environment variables but nothing.

What am I doing wrong or how can I do it?

[a comment by an automated account is not shown]

**Reply by Sgitario** [reply]
We would need to know more details about why it does not work:
- Either does the generated Deployment not contain the env vars you have defined?
- Or does the generated `openshift.yml` file not contain your configMap or your secret?
- Or does the app fail to start in OpenShift?

Also, what version of Quarkus and what Quarkus extensions are you using? A reproducer could help too.

**Reply by aelzo1209** [reply]
I'm new to both quarkus and openshift, so I'm probably missing certain concepts. I will try to answer your questions.

My project quarkus version:
```
quarkusPluginId=io.quarkus
quarkusPluginVersion=2.16.3.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=2.16.3.Final
```

I am using the following extensions:
```
dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-openshift'
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-resteasy'
    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
}
```

Now I am only trying to take some variables from a secret file (what I had in the configmap I have put directly in the properties file)
```
quarkus.openshift.env.secrets=my-secret
quarkus.openshift.env.mapping.DB_USERNAME.from-secret=my-secret
quarkus.openshift.env.mapping.DB_USERNAME.with-key=db-username
quarkus.openshift.env.mapping.DB_PASSWORD.from-secret=my-secret
quarkus.openshift.env.mapping.DB_PASSWORD.with-key=db-password

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://postgresql/databasename
```

I create the image with the following command:
`gradlew build -Dquarkus.container-image.build=true`

The generated openshift.yml file looks like:
```
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-03-02 - 08:40:43 +0000
  labels:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
    app.openshift.io/runtime: quarkus
  name: sewo
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2023-03-02 - 08:40:43 +0000
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/name: sewo
        app.kubernetes.io/version: latest
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: sewo-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-username
                  name: sewo-secret
          image: sewo:latest
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: sewo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - sewo
        from:
          kind: ImageStreamTag
          name: sewo:latest
      type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-03-02 - 08:40:43 +0000
  labels:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
    app.openshift.io/runtime: quarkus
  name: sewo
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2023-03-02 - 08:40:43 +0000
  labels:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
    app.openshift.io/runtime: quarkus
  name: sewo
spec:
  dockerImageRepository: docker.io/group/sewo
```
When i deploy the image located in docker hub from openshift, it gives me an error because it can't find the database access credentials.
I don't know how to tell it to take them from the secret file that I have in openshift. I have also tried to create a Deployment config from Openshift itself, putting these variables contained in the secret but nothing.

**Reply by Sgitario** [reply]
I think I see what is going here. You need to incorporate your ConfigMap and Secret resources into the generated `openshift.yml` file. You can do this by adding these two files into `common.yml`:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  db-url: jdbc:postgresql://postgresql/databasename
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  db-username: username
  db-password: password
```

And then copy this `common.yml` file into the `src/main/kubernetes` folder. 

More information about this here: https://quarkus.io/guides/deploying-to-kubernetes#using-common-resources
A full example here (using K8s): https://sgitario.github.io/deploy-quarkus-apps-with-databases-kubernetes/

**Reply by aelzo1209** [reply]
I still can't deploy the app. I have created the common.yml file as you have told me, and I see that when I do the build it includes that inside the openshift.yml. 
```
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  ...
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: sewo
    app.kubernetes.io/version: latest
  template:
    metadata:
      ...
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: my-secret
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db-username
                  name: my-secret
	...
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  db-url: jdbc:postgresql://postgresql/databasename
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  db-username: username
  db-password: password
type: Opaque
---
apiVersion: v1
kind: Service
...
```
But when I display the image in opneshift it tells me the following:

`WARN [io.agr.pool] (agroal-11) Datasource '<default>': The server requested password-based authentication, but no password was provided by plugin null`

The values ​​inside the secret are encoded in base64

**Reply by Sgitario** [reply]
If the secret data values are encoded, it should work fine. I tried it myself and everything did. 
See my project attached just in case you can spot what is different:
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/10870859/code-with-quarkus.zip)

Note that I'm using the Kubernetes extension, but it should not really matter. My generated `kubernetes.yml` file is:

```yml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-02 - 11:37:23 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: code-with-quarkus
  name: code-with-quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: code-with-quarkus
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-03-02 - 11:37:23 +0000
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: code-with-quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRESQL_PASSWORD
                  name: my-secret
            - name: POSTGRESQL_URL
              valueFrom:
                secretKeyRef:
                  key: POSTGRESQL_URL
                  name: my-secret
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRESQL_USERNAME
                  name: my-secret
          image: quay.io/jcarvaja/quarkus-example:latest
          imagePullPolicy: Always
          name: code-with-quarkus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  POSTGRESQL_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXM6NTQzMi9leGFtcGxl
  POSTGRESQL_USERNAME: dXNlcg==
  POSTGRESQL_PASSWORD: cGFzcw==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: example
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
          image: postgres:15.1
          name: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
  selector:
    service: postgres
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-03-02 - 11:37:23 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP

```
