### DISCUSSION TITLE
About location endpoint

### DISCUSSION THREAD

**Discussion by Angel0926** [quarkusio/quarkus#32492] [Q&A]
hi. i want change location endpoint, but when i added 
```
quarkus:
  swagger-ui:
    always-include: true
    path: swagger
```
in my application.yaml, my endpoint location became to http://localhost:8080/q/swagger , but i want without `/q/`. I want that it looks like that http://localhost:8080/q/swagger
