### DISCUSSION TITLE
OpenTelemetry  counter

### DISCUSSION THREAD

**Discussion by cthiebault** [quarkusio/quarkus#34096] [Q&A] [answered]
Hello,

I'm new to OpenTelemetry, and I'm trying to create a simple counter to send metrics to Datadog.

Here is my Kotlin code:

```kotlin
import io.opentelemetry.api.OpenTelemetry
import io.opentelemetry.api.metrics.LongCounter
import jakarta.enterprise.context.ApplicationScoped
import jakarta.inject.Inject

@ApplicationScoped
class Metrics @Inject constructor(private val openTelemetry: OpenTelemetry) {

  fun incrementCounter() {
    val counter: LongCounter = openTelemetry.getMeter("my-metrics")
      .counterBuilder("counter")
      .build()
    counter.add(1)
  }
}
```

And the Quarkus configuration:

```yaml
quarkus:
  otel:
    sdk:
      disabled: false
    exporter:
      otlp:
        traces:
          endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}
```

When I run it, the counter is an instance of `io.opentelemetry.api.metrics.DefaultMeter$NoopLongCounter`, so of course I
don't get any metrics in Datadog :(

It seems that the `MeterProvider` is a `io.opentelemetry.api.metrics.DefaultMeterProvider$NoopMeterBuilder` and I don't
know how to configure Quarkus to not use a NOOP `MeterProvider`.

Any ideas?

Thanks in advance for your help :)

[a comment by an automated account is not shown]
