### DISCUSSION TITLE
Missing libc for Quarkus 3 native image build in GitLab CI/CD

### DISCUSSION THREAD

**Discussion by DevEnol** [quarkusio/quarkus#34543] [Q&A] [answered]
Hi all,

I am trying to build native docker image using GitLab CI/CD, with custom docker image, based on GraalVM and Maven preinstalled.

The build process finished and pushed successfully to my docker registry. However when I try to run it, the docker container failed to start with the following message:
```
./application: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./application)
./application: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./application)
```

At the moment I am using Quarkus 3.1.1.Final

My custom docker image for the native build:
```
FROM ghcr.io/graalvm/graalvm-ce:22.3.1

WORKDIR /workdir

COPY maven .

ENV GRAALVM_HOME=$JAVA_HOME
ENV PATH=$PATH:$GRAALVM_HOME/bin

RUN gu install native-image

RUN tar -xvf apache-maven-3.9.3-bin.tar.gz
RUN mv apache-maven-3.9.3 /opt/

ENV MAVEN_HOME='/opt/apache-maven-3.9.3'
ENV PATH="$MAVEN_HOME/bin:$PATH"

RUN mv settings.xml $MAVEN_HOME/conf/settings.xml
```
Let say this custom docker image is pushed to: 
```
local.registry/custom-builder/cicd-builder:v3
```

I am using **dind** to build the docker container, with the provided **Dockerfile.native** file.

My .gitlab-ci.yml file:
```
stages:
  - build
  - deploy

cache:
  paths:
    - ".m2/repository"
 
variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

build-job:
  stage: build
  image: local.registry/custom-builder/cicd-builder:v3
  script:
    - ./mvnw clean package $MAVEN_OPTS -DskipTests -Pnative -Dquarkus.container-image.push=false -X -s $MAVEN_HOME/conf/settings.xml
  artifacts:
    name: artifacts-build-native
    expire_in: 1 days
    paths:
      - $CI_PROJECT_DIR/target/

deploy-job:
  stage: deploy
  needs:
    - build-job
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/native:$CI_COMMIT_BRANCH -f $CI_PROJECT_DIR/src/main/docker/Dockerfile.native .
    - docker push $CI_REGISTRY_IMAGE/native:$CI_COMMIT_BRANCH
```
