### DISCUSSION TITLE
How to configure RabbitMQ as AMQP broker in dev resource

### DISCUSSION THREAD

**Discussion by hantsy** [quarkusio/quarkus#34937] [Q&A]
I want to configure RabbitMQ as AMQP broker in the dev resource, but tried the following config, both are not worked as expected, 

```properties
quarkus.amqp.devservices.image-name=rabbitmq:3-management-alpine
```

or 

```properties
quarkus.rabbitmq.devservices.enabled=true
quarkus.rabbitmq.devservices.image-name=rabbitmq:3-management-alpine
```

**Comment by ozangunalp** [comment]
It is not possible to do it OOTB as it requires enabling and configuring AMQP 1.0 plugin. 

However, you can configure and run a rabbitmq image locally, exposing a port mapping for the default AMQP 1.0 port with a label `quarkus-dev-service-amqp=amqp`. The AMQP dev service will pick and configure your application with this service instead of creating a new one.
For example with docker compose it'll look like :
```yaml
version: '3.8'

services:
  some-rabbit:
    image: rabbitmq:3.12-management-alpine
    labels:
      - quarkus-dev-service-amqp=amqp
    ports:
      - '5671'
      - '15671'
      - '5672'
      - '15672'
    volumes:
      - './enabled_plugins:/etc/rabbitmq/enabled_plugins:ro'
      - './custom_rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf'
```
