### DISCUSSION TITLE
How support multiple tenant root with hibernate6 ?

### DISCUSSION THREAD

**Discussion by seepine** [quarkusio/quarkus#35332] [Q&A] [answered]
## In Springboot
application.yml
```yml
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: true
        tenant_identifier_resolver: com.example.config.TenantResolver
```
TenantResolver.java
```java
public interface CurrentTenantIdentifierResolver {
        // set tenant value
	String resolveCurrentTenantIdentifier();
   
        // true will query all tenant data
	default boolean isRoot(String tenantId) {
		return false;
	}
}
```

## But in Quarkus 3.x

I can not find how to query ignore tenant like `CurrentTenantIdentifierResolver .isRoot`

application.properties
```properties
quarkus.hibernate-orm.multitenant=DISCRIMINATOR
```

CustomTenantResolver.java
```java
@PersistenceUnitExtension
@RequestScoped
public class CustomTenantResolver implements TenantResolver {

  // what is this ?
  @Override
  public String getDefaultTenantId() {
    return "0";
  }

  @Override
  public String resolveTenantId() {
    return Optional.ofNullable(TenantUtil.getTenantId()).map(Serializable::toString).orElse(null);
  }
}
```

[a comment by an automated account is not shown]

**Comment by yrodiere** [comment]
As far as I can tell this is simply a missing feature.

If you need it, I'd suggest [filing a feature request](https://github.com/quarkusio/quarkus/issues/new/choose), and ideally a pull request that:

* adds the missing method to `io.quarkus.hibernate.orm.runtime.tenant.TenantResolver`
* implements `isRoot()` in https://github.com/quarkusio/quarkus/blob/d7b4c51c313334fb13e2ece7a328da659a2860d8/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/tenant/HibernateCurrentTenantIdentifierResolver.java#L18
* adds a simple test (checking you have access to all tenants) in `integration-tests/hibernate-orm-tenancy/discriminator/src/main/java/io/quarkus/it/hibernate/multitenancy/fruit/CustomTenantResolver.java` / `integration-tests/hibernate-orm-tenancy/discriminator/src/main/java/io/quarkus/it/hibernate/multitenancy/fruit/FruitResource.java` / `integration-tests/hibernate-orm-tenancy/discriminator/src/test/java/io/quarkus/it/hibernate/multitenancy/fruit/HibernateTenancyFunctionalityTest.java`

**Reply by seepine** [reply]
Hi, can I directly use hibernate `org.hibernate.context.spi.CurrentTenantIdentifierResolver` like this in quarkus?
```yml
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: true
        tenant_identifier_resolver: com.example.config.TenantResolver
```
