### DISCUSSION TITLE
Openapi disable basic authorization

### DISCUSSION THREAD

**Discussion by zivkovic** [quarkusio/quarkus#36708] [Q&A]
I have an api defined with annotations. No security at all, but the generated schema always contains the "basic" auth definition:
```
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
```

How can I simply generate the api spec without the security schemas (as they are not used at all...). I debugged this a bit, and it seems to come out from `OpenApiDocumentService.java` where it loads a file 'META-INF/quarkus-generated-openapi-doc.json", which seems to contain basic auth, which is then propagated to my own api spec. This happens both in dev and prod mode.

Any ideas how to disable it?

Thank you.

[a comment by an automated account is not shown]
