### DISCUSSION TITLE
How to pass additional native jvm args on kubernetes deployment?

### DISCUSSION THREAD

**Discussion by HerrDerb** [quarkusio/quarkus#37711] [Q&A] [answered]
I would like to pass some additional native jvm args on deployment.
The current way to do so is
```
...
      containers:
        - args:
            - '-Xmn10m'
            - '-Xms1m'
            - '-Xmx30m'
          command:
            - ./application
          env:
...
```

While this does work, it overrides any arguments which are configured within the project over `quarkus.jib.native-argument`

I also tried to do something like `quarkus.jib.native-arguments=$ADDITIONAL_NATIVE_ARGS` with the idead that I could set a env variable for the container. With this, the container fails to start.
```
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "$ADDITIONAL_NATIVE_ARGS": executable file not found in $PATH: unknown.
```
What is a viable way in Quarkus and docker, kubernetes to pass additional native arguments at deploy time?

[a comment by an automated account is not shown]
