### DISCUSSION TITLE
Multi Container Dev Services

### DISCUSSION THREAD

**Discussion by cescoffier** [quarkusio/quarkus#38398] [Community]
Hello,

This is based on an email from @lbroudoux asking me about multi-container dev services and links between dev service containers.

---
I wonder how to manage dependencies between Quarkus DevServices and, more generally, between containers managed by DevServices.

I would need to attach/initialize them within the same network to enable communication via aliases and set dependencies to constrain the startup order.

For example, start the Microcks container after the Kafka container to avoid DNS resolution failures.
---

I know that @ozangunalp and @alesj have recently worked on that subject (or worked around the issue). Can you provide your insights?

**Comment by alesj** [comment]
> I would need to attach/initialize them within the same network to enable communication via aliases and set dependencies to constrain the startup order.

Wrt to "within the same network", this is still a mystery to me -- it works most of the time, but sometimes not.

I do set this in all containers (if shared of course, which they are by default)
```
        if (config.shared()) {
            withNetwork(Network.SHARED);
        }
```
and then set aliases to all of them.
But I remember that I had some weird issues where Jager had to be set differently - alias vs. 0.0.0.0 :
```
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  logging:
    loglevel: debug
  jaeger:
    endpoint: jaeger:14250
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8428
    namespace: quarkus_observability
```

Anyway, I'm just about to do a new PR (closed the previous one - as it was too big :-) -- and you can see the concept behind it.
And perhaps we can rewrite some of the existing stuff to this as well.
