### DISCUSSION TITLE
1 Unmanaged Datasource, 1 Managed Datasource

### DISCUSSION THREAD

**Discussion by zachlefevre** [quarkusio/quarkus#39814] [Q&A]
Howdy!

I have a project with multiple datasources.
1 datasource is passed into an external library which uses it. This external library handles transactions and sessions.
The *other* datasource is quarkus-managed and should respect `@Transactional`, and is only interacted with via the ORM.

This doesn't seem possible without manually managing transactions in the managed datasource.

My config contains
```
quarkus:
  datasource:
    managed:
      db-kind: postgresql
      jdbc:
        driver: org.postgresql.Driver
        url: ...
    unmanaged:
      db-kind: postgresql
      jdbc:
        transactions: disabled                       # I would like the external library to manage this connection
        driver: org.postgresql.Driver
        url: ...
```

It seems, however, that when operating in a `@Transactional` function that uses both the `managed` and  `unmanaged` datasource transactions are turned off globally, even though `transactions` remains enabled in the `managed` datasource.
