### DISCUSSION TITLE
Needs configuration options for custom annotations for Service, not for Ingress

### DISCUSSION THREAD

**Discussion by CynicDog** [quarkusio/quarkus#40940] [Q&A]
I'm implementing an app that includes Oauth2 implementation which mandates state key comparison (via cookie). 

The app is deployed on GKE. 

In such case the Ingress needs to have a sticky session (Session Affinity over Client IP), which could be configured via Service annotations, not Ingress annotations. 
(https://cloud.google.com/kubernetes-engine/docs/how-to/load-balance-ingress#service_annotations_related_to_ingress) 

For now quarkus has the configuration option for setting annotations on Ingress, `quarkus.kubernetes.ingress.annotations`, but there's no configuration option for setting annotations on Service, with which I would achieve to generate manifest that might reads: 

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.9.2
    app.quarkus.io/commit-id: ...
    app.quarkus.io/vcs-uri: ...
    app.quarkus.io/build-timestamp: ...

    # I need to write in the next line 😭
    cloud.google.com/backend-config: '{"ports": {"80":"my-backendconfig"}}'
```

Any other quarkus-fellows than me who are in similar need?

+++ 
``` java 
public static final String stateKey = "STATE";
// ... 
public void signIn(RoutingContext ctx) {
        OAuth2Auth oauth2Provider = OAuth2Auth.create(vertx, credentials);

        String state = generateRandomString(16);
        String authorizationUri = oauth2Provider.authorizeURL(
                new OAuth2AuthorizationURL()
                        .setRedirectUri(redirectUri)
                        .setScopes(Arrays.asList("read:user", "user:email"))
                        .setState(state));

        ctx.response()
                .addCookie(Cookie.cookie(stateKey, state))
                .putHeader("Location", authorizationUri)
                .setStatusCode(302).end();
    }

public void callback(RoutingContext ctx) {
        String code = ctx.request().getParam("code");
        String state = ctx.request().getParam("state");

        // getting errors on this line saying that there's no cookie stored for the state on GKE-deployed production 
        String storedState = ctx.request().getCookie(stateKey).getValue();

        if (state == null || !state.equals(storedState)) {
            ctx.response()
                    .putHeader("Location", "/#state_mismatch")
                    .setStatusCode(302)
                    .end();
        }
        else {
            ctx.response().removeCookie(stateKey);

            WebClient client = WebClient.create(ctx.vertx());

            var tokenFuture = getGithubAccessToken(client, code);
            tokenFuture
                    .thenAccept(result -> handleTokenSuccess(ctx, client, result))
                    .exceptionally(ex -> handleTokenFailure(ctx, ex));
        }
    }
```

[a comment by an automated account is not shown]
