### DISCUSSION TITLE
Kubernetes extension -  nodeSelector

### DISCUSSION THREAD

**Discussion by Vinche59** [quarkusio/quarkus#43982] [Q&A]
Hello @iocanel,

Is it possible to generate a "nodeselector" entry in yaml file with quarkus-kubernetes extension ?
```
apiVersion: apps/v1
kind: Deployment
spec:
  [...]
  template:
    [...]
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: mongo
      containers:
      [...]
```
I don't find anything relevant in the doc but maybe I missing something ?

[a comment by an automated account is not shown]
