### DISCUSSION TITLE
Generated function.zip and funqy-amazon-lambda-quickstart-1.0.0-SNAPSHOT.jar don't have FunqyStreamHandler.class

### DISCUSSION THREAD

**Discussion by underscore05** [quarkusio/quarkus#44985] [Q&A]
I am trying to use `serverless-offline` (https://github.com/dherault/serverless-offline) together with `[Funq-AWS-Lambda](https://github.com/quarkusio/quarkus-quickstarts/tree/main/funqy-quickstarts/funqy-amazon-lambda-quickstart)` but it looks like the `FunqyStreamHandler` does not exist in either the generated jar file or the function.zip files.

When I open the jar file `funqy-amazon-lambda-quickstart-1.0.0-SNAPSHOT-runner.jar\io\quarkus\funqy\lambda` I can only see `config` folder and no FunqyStreamHandler class.

Here's how my serverless.yml looks like and its pointing to that class.

```
service: my-quarkus-lambda

provider:
  name: aws
  runtime: java11

plugins:
  - serverless-offline

package:
  artifact: target/funqy-amazon-lambda-quickstart-1.0.0-SNAPSHOT-runner.jar

functions:
  greet:
    handler: io.quarkus.funqy.lambda.FunqyStreamHandler::handleRequest
    events:
      - http:
          path: greet
          method: get
```

[a comment by an automated account is not shown]
