### DISCUSSION TITLE
Opentelemetry implementation with multiple remote JDBC

### DISCUSSION THREAD

**Discussion by isaac-swift-bluestaq** [quarkusio/quarkus#45339] [Q&A]
I recently started implementing open telemetry on an application that has multiple JDBC connections that are piped through a bastion host and I'm primarily concerned with getting data (traces) for said JDBC connections.

Judging by the [documentation](https://quarkus.io/guides/opentelemetry-tracing#jdbc), it seems like all that needs to be done (beyond adding the dependency) is to enable telemetry on each data source, although no example is provided that has multiple data sources. I attempted this like so (using quarkus-config-yaml extension):
```
quarkus:
  application:
    name: appName
  artemis:
    url: url
  package:
    jar:
      enabled: true
      type: uber-jar
  datasource:
    #    max-size: 60
    postgresDS:
      db-kind: postgresql
      jdbc:
        telemetry: true
        acquisition-timeout: 10
        idle-removal-interval: 1M
        background-validation-interval: 2M
        validation-query-sql: "SELECT 1"
        leak-detection-interval: 5M
        detect-statement-leaks: true
        max-lifetime: 10M
        initial-size: 2
        min-size: 2
        max-size: 5
        enable-metrics: false
        url: url
      credentials-provider: credentials-provider
      credentials-provider-name: credentials-provider-name
    emrDS:
      db-kind: other
      jdbc:
        telemetry: true
etc....
```
In the resultant grafana window, the "JDBC" section still has no data while the other sections do:
![image](https://github.com/user-attachments/assets/0e132eae-5de0-4a8a-867f-2efbdf3da19d)

I also tried adding a base level jdbc section with telemetry enabled as featured verbatim in the documentation (quarkus.datasource.jdbc.telemetry=true) which yielded the same result.

I'm unsure whether the issue stems from the quantity of data sources, the configuration's format, the bastion piping, or something else entirely. I'm totally new to this, so any help would be much appreciated, and I'd be glad to provide more information and try things out as needed.

[a comment by an automated account is not shown]

**Reply by brunobat** [reply]
`quarkus.datasource.jdbc.telemetry=true` works for 1 datasource. I've tried it yesterday.
Here you have an example: 
https://github.com/brunobat/quarkus-observability-perf/blob/7d2df8c399f30640bbbe7e1ce7c9fd48aef2d42f/quarkus-otel-db-perf/src/main/resources/application.properties#L7

I assume you are using latest Quarkus (3.17.5) and the `quarkus-opentelemetry` extension with the lib:
```
        <dependency>
            <groupId>io.opentelemetry.instrumentation</groupId>
            <artifactId>opentelemetry-jdbc</artifactId>
        </dependency>
```

Try to configure just the default datasource... Something like:
```
quarkus:
  application:
    name: appName
  artemis:
    url: url
  package:
    jar:
      enabled: true
      type: uber-jar
  datasource:
    jdbc:
      telemetry: true
...
    emrDS:
```

**Reply by isaac-swift-bluestaq** [reply]
I'm on Quarkus 3.17.4

I've tried the default datasource before, and I tried it just now with no luck. To be explicit, here's what the config I just tried looked like:

```
quarkus:
  application:
    name: appName
  artemis:
    url: url
  package:
    jar:
      enabled: true
      type: uber-jar
  datasource:
    #    max-size: 60
    jdbc:
      telemetry: true
    postgresDS:
      db-kind: postgresql
      jdbc:
        telemetry: true
        acquisition-timeout: 10
        idle-removal-interval: 1M
        background-validation-interval: 2M
        validation-query-sql: "SELECT 1"
        leak-detection-interval: 5M
        detect-statement-leaks: true
        max-lifetime: 10M
        initial-size: 2
        min-size: 2
        max-size: 5
        enable-metrics: false
        url: url
      credentials-provider: credentials-provider
      credentials-provider-name: credentials-provider-name
    emrDS:
      db-kind: other
      jdbc:
        telemetry: true
etc....
```

I also tried moving the entire postgres config under the default, and that didn't work either:

```
quarkus:
  application:
    name: appName
  artemis:
    url: url
  package:
    jar:
      enabled: true
      type: uber-jar
  datasource:
    #    max-size: 60
    db-kind: postgresql
    jdbc:
      telemetry: true
      acquisition-timeout: 10
      idle-removal-interval: 1M
      background-validation-interval: 2M
      validation-query-sql: "SELECT 1"
      leak-detection-interval: 5M
      detect-statement-leaks: true
      max-lifetime: 10M
      initial-size: 2
      min-size: 2
      max-size: 5
      enable-metrics: false
      url: url
    credentials-provider: credentials-provider
    credentials-provider-name: credentials-provider-name
```
Since neither of those worked, is it possible the issue is related to connecting via the ssh bastion tunnel rather than the config?
