### DISCUSSION TITLE
Permission denied when mapping volume (devservices)

### DISCUSSION THREAD

**Discussion by costelus27** [quarkusio/quarkus#46010] [Q&A]
Hello,
I have Quarkus test for which I'm starting an Oracle database via devservices. My configuration is as follows:

```	
quarkus: 
        datasource:
            username: test
            password: test
            devservices:
                enabled: true
                volumes:
                    "classpath:scripts": /container-entrypoint-initdb.d
                show-logs: true
```
Locally everything works, but when I run the build in Jenkins, the mapped folder `/container-entrypoint-initdb.d` gets a Permission denied. 

`[io.qua.dev.ora.dep.OracleDevServicesProcessor] (docker-java-stream-748879329) STDERR: ls: cannot open directory '/container-entrypoint-initdb.d': Permission denied`

Also, in the container, I can see this:

```
bash-4.4$ ls -la /
...
dr-xr-xr-x.   2 root   root       6 Oct  9  2021 boot
drwxr-x---.   1   2500     2500  58 Jan 30 12:37 container-entrypoint-initdb.d
drwxr-xr-x.   2 oracle oinstall   6 Dec 14 20:27 container-entrypoint-startdb.d
drwxr-xr-x.   5 root   root     340 Jan 30 12:38 dev
...
```

My local user's id on the Jenkins server is 2500.  

I don't know how to make the test pass also on Jenkins. Any suggestions ?

[a comment by an automated account is not shown]
