### DISCUSSION TITLE
Camel Quarkus unable to pick up camel.component.kafka.brokers

### DISCUSSION THREAD

**Discussion by MikaelAnderssonWigander** [quarkusio/quarkus#46138] [Q&A] [answered]
In Quarkus 3.18.0, Camel 4.9.0, is not picking up configuration option for

```%prod.camel.component.kafka.brokers```

but picks up other configs such as:

```
[MicroProfilePropertiesSource] camel.component.kafka.sslKeystoreLocation = /mnt/kafka-cert/keystore.jks
[MicroProfilePropertiesSource] camel.component.kafka.reconnectBackoffMaxMs = 5000
[MicroProfilePropertiesSource] camel.component.kafka.saslMechanism = SCRAM-SHA-512
[MicroProfilePropertiesSource] camel.component.kafka.saslJaasConfig = xxxxxx
[MicroProfilePropertiesSource] camel.component.kafka.reconnectBackoffMs = 300
[MicroProfilePropertiesSource] camel.component.kafka.sslTruststoreLocation = /mnt/kafka-cert/truststore.jks
[MicroProfilePropertiesSource] camel.component.kafka.maxRequestSize = 10000000
[MicroProfilePropertiesSource] camel.component.kafka.sslKeyPassword = xxxxxx
[MicroProfilePropertiesSource] camel.component.kafka.securityProtocol = SASL_SSL
[MicroProfilePropertiesSource] camel.component.kafka.sslTruststorePassword = xxxxxx
[MicroProfilePropertiesSource] camel.component.kafka.sslKeystorePassword = xxxxxx
```

with this yaml config present:

```yml
%prod:
  camel:
    component:
      kafka:
        brokers: ${KAFKA_BOOTSTRAP_SERVERS}
        maxRequestSize: 10000000
        security-protocol: SASL_SSL
        sasl-mechanism: SCRAM-SHA-512
        sasl-jaas-config: >
          org.apache.kafka.common.security.scram.ScramLoginModule required
          username=${SASL_USERNAME}
          password=${SASL_PASSWORD};
        ssl-key-password: ${KAFKA_CONFIGURATION_SSL_KEY_PASSWORD}
        ssl-keystore-location: /mnt/kafka-cert/keystore.jks
        ssl-keystore-password: ${KAFKA_CONFIGURATION_SSL_KEYSTORE_PASSWORD}
        ssl-truststore-location: /mnt/kafka-cert/truststore.jks
        ssl-truststore-password: ${KAFKA_CONFIGURATION_SSL_TRUSTSTORE_PASSWORD}

```

Property is defined earlier in yaml file
```
KAFKA_BOOTSTRAP_SERVERS: mysite1
```

Everything works in %dev mode

Any ideas why?

I can't add the "?brokers=" to the component because we use Dev services and in PROD we deploy to different clusters in K8 using Helm, so this has to be as dynamic as possible.

Thx

[a comment by an automated account is not shown]
