### DISCUSSION TITLE
Quarkus jwt-authentication-with-http-only-cookie

### DISCUSSION THREAD

**Discussion by Nikhil12894** [quarkusio/quarkus#47200] [Q&A]
I am using OIDC with Quarkus and logging in through the backend API only. Once the login callback is called, I set the access token in a cookie. However, when I attempt to use that cookie to authenticate my requests, I always receive a 403 Forbidden error.
### **Login Api:**

```java
@GET
@Path("/login")
public Response login(@jakarta.ws.rs.QueryParam(STATE) String state) {
    // For 'web-app' type, this would typically trigger a redirect to Keycloak.
    // For 'service' type, you'd handle token exchange manually.
    // This example assumes 'web-app' for simplicity of initial login.
    String scope = URLEncoder.encode("openid profile email", StandardCharsets.UTF_8);
    String stateParam = (state != null && !state.isEmpty()) ? STATE_PARAM + state : "";


    String authUrl = authServerUrl + PROTOCOL_OPENID_CONNECT_AUTH +
            RESPONSE_TYPE_CODE_PARAM +
            CLIENT_ID_PARAM + clientId +
            REDIRECT_URI_PARAM + URLEncoder.encode(callbackUrl, StandardCharsets.UTF_8) + // Configure your callback URI
            SCOPE_PARAM + scope +
            stateParam;

    log.info("Redirecting to Keycloak Auth URL: {}", authUrl);

    return Response.seeOther(java.net.URI.create(authUrl)).build();
}
```

### **Callback APi:**

```java
@GET
@Path("/callback")
public Response callback(@jakarta.ws.rs.QueryParam(CODE) String code, @jakarta.ws.rs.QueryParam(STATE) String state) {
    if (code == null || code.isEmpty()) {
        return Response.status(Response.Status.BAD_REQUEST).entity("Authorization code missing.").build();
    }
    log.info("Received authorization code: {}", code);
    log.info("Received state: {}", state);
    try {
        Form form = new Form()
                .param(GRANT_TYPE, AUTHORIZATION_CODE)
                .param(CODE, code)
                .param(REDIRECT_URI, callbackUrl)
                .param(CLIENT_ID, clientId)
                .param(CLIENT_SECRET, clientSecret); // Only if your client is confidential

        Response tokenResponse = ClientBuilder.newClient()
                .target(authServerUrl + PROTOCOL_OPENID_CONNECT_TOKEN)
                .request(MediaType.APPLICATION_FORM_URLENCODED)
                .post(Entity.form(form));
        log.info("Token response status: " + tokenResponse);
        log.info("Token response status code: {}", tokenResponse.getStatus());
        if (tokenResponse.getStatusInfo().getFamily() == Response.Status.Family.SUCCESSFUL) {
            Map<String, Object> tokens = tokenResponse.readEntity(Map.class);
            String accessToken = (String) tokens.get(ACCESS_TOKEN);
            String idToken = (String) tokens.get(ID_TOKEN);
            String refreshToken = (String) tokens.get(REFRESH_TOKEN);

            // Redirect user to the stored path or default to dashboard
            String redirectUrl = (state != null ? state : ""); //+ "?token=" + accessToken;
            return Response.seeOther(java.net.URI.create(redirectUrl))
                    .cookie(
                            new NewCookie("access_token", accessToken, "/", "localhost", null, 300, false,false)
                    ).build();
        } else {
            String error = tokenResponse.readEntity(String.class);
            log.error("Error during token exchange: {} - {}", tokenResponse.getStatus(), error);
            return Response.status(Response.Status.BAD_REQUEST).entity("Token exchange failed: " + error).build();
        }
    } catch (Exception e) {
        log.error("Exception during callback processing: {}", e.getMessage());
        return Response.serverError().entity("Callback processing error.").build();
    } finally {
        // Ensure the tokenResponse is closed
    }
}
```

### **Application.yaml:** 

```yaml
quarkus:
  http:
      port: 8081
      cors:
        enabled: true
        origins: /.*/
        access-control-allow-credentials: true
#      auth:
#        enabled: true

# Keycloak configuration
  oidc:
    auth-server-url: http://localhost:8080/realms/blog-realm # Replace with your Keycloak URL
    client-id: my-auth # Replace with your Keycloak client ID
    credentials:
      secret: hjkghjhdsaghjghjdfasghjdfh # Replace with your Keycloak client secret
    application-type: service # Or 'web-app' if BFF handles UI redirects directly
    authentication:
      scopes: openid, profile, email
    token:
      cookie: true
  rest-client:
    backend-api: # Configuration for your backend service
      url: http://localhost:8081/api # Replace with your backend service URL
    keycloak-admin-api:
      url: http://localhost:8080/auth/admin/realms/my-realm # Keycloak Admin API URL

# Define roles (can be mapped from Keycloak roles)
mp:
  jwt:
    token:
      header: Cookie
      cookie: access_token
      issuer: http://localhost:8080/realms/my-realm
    verify:
      publickey:
        location: http://localhost:8080/realms/my-realm/protocol/openid-connect/certs
    roles-claim: realm_access/roles  # Ensure Quarkus reads roles from Keycloak

# Logging configuration
quarkus.log:
  console:
    enable: true
    color: true
  level: INFO


app:
  auth:
    callback:
      url: http://localhost:8081/auth/callback
    redirect:
      url: http://localhost:5173
  keycloak:
    admin:
      base-url: http://localhost:8080
      username: xyz
      password: xyz
      client-secret: hgsdhgjhsdjhdshjgdshdsj
      client-id: admin-cli
```

JS Code:

```js
  const fetchToken = async () => {
    try {
      const response = await fetch("http://localhost:8081/auth/token", {
        method: "GET",
        credentials: 'include', // 🔥 This sends the cookie
        headers: {
          "Accept": "application/json",
        },
      });

      if (!response.ok) throw new Error("Failed to authenticate");

      setIsLogin(true);
    } catch (error) {
      console.error("Authentication failed", error);
      setIsLogin(false);
    }
  };
```

[a comment by an automated account is not shown]

**Comment by sberyozkin** [comment]
Hi @Nikhil12894, I commented at https://stackoverflow.com/questions/79558948/quarkus-jwt-authentication-with-http-only-cookie

**Reply by Nikhil12894** [reply]
now I am using this only 

```yaml
quarkus:
  http:
      port: 8080
      cors:
        enabled: true
        origins: /.*/
        access-control-allow-credentials: true
        access-control-allow-methods: GET, POST, PUT, DELETE, OPTIONS

# Keycloak configuration
  oidc:
    auth-server-url: http://localhost:8180/realms/quarkus # Replace with your Keycloak URL
    client-id: frontend # Replace with your Keycloak client ID
    credentials:
      secret: secret # Replace with your Keycloak client secret
    application-type: service # Or 'web-app' if BFF handles UI redirects directly
    authentication:
      session-age: 3600
      cookie-path: /
      cookie-secure: false
      scopes: openid, profile, email
```

I'm trying to authenticate a request to my secured API by sending the access_token in a cookie, but I'm receiving a 401 error. I also attempted to use a filter to set the Authorization in the header, but I'm still getting a 401 response. How can I resolve this issue?

```java
@Provider
@Priority(Priorities.AUTHENTICATION-1)
@Slf4j
public class CookieTokenFilter implements ContainerRequestFilter {

    @Override
    public void filter(ContainerRequestContext requestContext) throws IOException {
        Cookie cookie = requestContext.getCookies().get("access_token");
        if (cookie != null) {
            String token = cookie.getValue();
            log.debug("Token cookie value: {}", token); // this is printing <--
            if (token != null && !token.isEmpty()) {
//                requestContext.getHeaders().putSingle("Authorization", "Bearer " + token);
                requestContext.getHeaders().add("Authorization", "Bearer " + token);
            }
        }

    }
}
```
