### DISCUSSION TITLE
Quartz logging some errors during shutdown

### DISCUSSION THREAD

**Discussion by iscu2020** [quarkusio/quarkus#48264] [Community]
Hello,
My Quarkus app (v3.20) uses Quartz, which is configured as follows:

```    
  quarkus:     
    quartz:
      clustered: true
      store-type: jdbc-cmt
      shutdown-wait-time: PT30S
      cron-trigger:
        misfire-policy: cron-trigger-do-nothing
      plugins:
        shutdown:
          class: org.quartz.plugins.management.ShutdownHookPlugin
    shutdown:
      timeout: PT35S
```

The exception that I see during shutdown is the following:

> java.sql.SQLRecoverableException: ORA-17008: Closed connection
> https://docs.oracle.com/error-help/db/ora-17008/
> at oracle.jdbc.driver.PhysicalConnection.requireOpenConnection(PhysicalConnection.java:13034)
> at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:2850)
> at io.agroal.pool.wrapper.ConnectionWrapper.rollback(ConnectionWrapper.java:208)
> at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
> at java.base/java.lang.reflect.Method.invoke(Unknown Source)
> at org.quartz.impl.jdbcjobstore.AttributeRestoringConnectionInvocationHandler.invoke(AttributeRestoringConnectionInvocationHandler.java:78)
> at jdk.proxy2/jdk.proxy2.$Proxy93.rollback(Unknown Source)
> at org.quartz.impl.jdbcjobstore.StdRowLockSemaphore.executeSQL(StdRowLockSemaphore.java:170)
> at org.quartz.impl.jdbcjobstore.DBSemaphore.obtainLock(DBSemaphore.java:112)
> at org.quartz.impl.jdbcjobstore.JobStoreSupport.executeInNonManagedTXLock(JobStoreSupport.java:3729)
> at org.quartz.impl.jdbcjobstore.JobStoreSupport.retryExecuteInNonManagedTXLock(JobStoreSupport.java:3691)
> at org.quartz.impl.jdbcjobstore.JobStoreSupport.releaseAcquiredTrigger(JobStoreSupport.java:2834)
> at org.quartz.core.QuartzSchedulerThread.releaseIfScheduleChangedSignificantly(QuartzSchedulerThread.java:483)
> at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:344)

It seems that quartz is shut down after the db connections are closed. 

How could I make it shutdown properly ?
Thank you !
