### DISCUSSION TITLE
what is the right way to configure list of object?

### DISCUSSION THREAD

**Discussion by abvaidya** [quarkusio/quarkus#48355] [Q&A] [answered]
I am using following yaml structure 

```
server:
  idp:
    custom:
      clientIds:
         - clientId: aa
           key: value1
         - clientId: bb
           key: value2
```

and on startup I see the error 
SRCFG00050: server.idp.custom.clientIds[0].clientId in YamlConfigSource[source=file:<PATH>/target/classes/application.yml] does not map to any root
SRCFG00050: server.idp.custom.clientIds[0].key in YamlConfigSource[source=file:<PATH>/target/classes/application.yml] does not map to any root
SRCFG00050: server.idp.custom.clientIds[1].clientId in YamlConfigSource[source=file:<PATH>/target/classes/application.yml] does not map to any root
SRCFG00050: server.idp.custom.clientIds[1].key in YamlConfigSource[source=file:<PATH>/target/classes/application.yml] does not map to any root

What am I missing here?

Quarkus version: 3.23.0
pom includes the dependency quarkus-config-yaml

[a comment by an automated account is not shown]

**Comment by abvaidya** [comment, marked as answer]
Apparently quarkus-config-yaml / smallrye expects kebab-case config keys so when i switched to 
```
server:
  idp:
    custom:
      client-ids:
         - client-id: aa
           key: value1
         - client-id: bb
           key: value2
```
and used `@WithName` annotation on my mapping interface, it worked as expected.
