### DISCUSSION TITLE
Maven Hangs during test phase after the migration v3.20.0 -> 3.23.4

### DISCUSSION THREAD

**Discussion by indalaterre** [quarkusio/quarkus#48531] [Community]
Hello, I have a very weird problem.
I'm migrating from v3.20.0 to v3.23.4 but I'm facing the problem mentioned in the title during the execution of `mvn verify`.

The system becomes very unstable (tried both on Gitlab CI Job which cause an OOM and on my personal machine) and I'm not able to figure out what is causing this. 

I thought this was caused by the new dev-service compose and I disable it without success
```
quarkus:
  compose:
    devservices:
      enabled: false
      start-services: false
```

To be honest I'm in a dead point and seeking for hints.
Does anyone have any idea regarding this?
