### ISSUE TITLE
custom kubernetes labels not added to minikube.yml

### ISSUE THREAD

**Issue by smsajid** [quarkusio/quarkus#10167]
**Describe the bug**
I am trying to apply custom labels to generated kubernetes.yml and minikube.yml using the property:
quarkus.kubernetes.labels.Foo=Bar

I have added both the kubernetes and minikube plugin in my build.gradle file:
```
dependencies {
   implementation 'io.quarkus:quarkus-minikube'
   implementation 'io.quarkus:quarkus-container-image-jib'
   implementation 'io.quarkus:quarkus-kubernetes'
   implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
   implementation 'io.quarkus:quarkus-undertow'

   testImplementation 'io.quarkus:quarkus-junit5'
   testImplementation 'io.rest-assured:rest-assured'
}
```

**Expected behavior**
Custom labels must be added to both yml files

**Actual behavior**
Labels only added to kubernetes.yml file but not to minikube.yml

kubernetes.yml:
```
  labels:
    app.kubernetes.io/name: "spring-theme"
    app.kubernetes.io/version: "1.0.0"
    greenscape.io/type: "Theme"
  name: "spring-theme"
```
minikube.yml:
```
  labels:
    app.kubernetes.io/name: "spring-theme"
    app.kubernetes.io/version: "1.0.0"
  name: "spring-theme"
```

**To Reproduce**
1.  As described above

**Configuration**
```properties
# gradle.properties
quarkusPluginVersion=1.5.2.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPlatformVersion=1.5.2.Final
quarkusPlatformGroupId=io.quarkus

quarkus.container-image.registry=docker.pkg.github.com
quarkus.container-image.group=greenscape/spring-theme
quarkus.kubernetes.labels."greenscape.io/type"=Theme


```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
v1.5.2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.0.1
------------------------------------------------------------

Build time:   2019-11-18 20:25:01 UTC
Revision:     fad121066a68c4701acd362daf4287a7c309a0f5

Kotlin:       1.3.50
Groovy:       2.5.8
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OS:           Windows 10 10.0 amd64
```
