### ISSUE TITLE
Quarkus 1.6.0.Final - generated kubernetes.yml has string values without quotes, it causes error on kubernetes.

### ISSUE THREAD

**Issue by evisentin** [quarkusio/quarkus#10649]
**Describe the bug**
With version 1.6.0.Final, the generated kubernetes.yml has string values without quotes, it causes error on kubernetes.

**Expected behavior**
 with version 1.5.2.Final the generated kubernetes.yml has quotes for the string values: 

```
  ---
  apiVersion: "v1"
  kind: "ServiceAccount"
  metadata:
    annotations:
      app.quarkus.io/build-timestamp: "2020-07-10 - 19:19:48 +0000"
    labels:
      app.kubernetes.io/name: "my-service"
      app.kubernetes.io/version: "1.0-SNAPSHOT"
    name: "my-service"

....
```

**Actual behavior**
Using Quarkus 1.6.0.Final I obtain

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2020-07-10 - 19:13:20 +0000
  labels:
    app.kubernetes.io/name: my-service
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: my-service
....
```

**To Reproduce**
1.  Use <quarkus-plugin.version>1.5.2.Final</quarkus-plugin.version> and <quarkus.platform.version>1.5.2.Final</quarkus.platform.version>
2.  mvn clean package
3. check the generated target/kubernetes/kubernetes.yml
4.  Use <quarkus-plugin.version>1.6.0.Final</quarkus-plugin.version> and <quarkus.platform.version>1.6.0.Final</quarkus.platform.version>
5.  mvn clean package
6. check the generated target/kubernetes/kubernetes.yml

**Configuration**
```properties
# [My Local Docker Registry] ----------------------
quarkus.container-image.registry=localhost:5000
quarkus.container-image.insecure=true
quarkus.container-image.build=true
quarkus.container-image.push=true

# [Kubernetes Minimal Configuration]
quarkus.kubernetes.name=my-service
```
