### ISSUE TITLE
Set quarkus.container-image.username to env property

### ISSUE THREAD

**Issue by UnvirtualHH** [quarkusio/quarkus#10753]
I want to user following config:

```yaml
 container-image:
      build: true
      push: true
      username: ${CI_REGISTRY_USER}
      password: ${CI_REGISTRY_PASSWORD}
```

GitLab CI Build runs fine, but when the pod will start I get following exception:

```
exception":{"refId":1,"exceptionType":"java.util.NoSuchElementException","message":"SRCFG00011: Could not expand value CI_REGISTRY_USER in property %prod.quarkus.container-image.username","frames":[{"class":"io.smallrye.config.ExpressionConfigSourceInterceptor","method":"lambda$getValue$0","line":44},{"class":"io.small │
│ rye.common.expression.ExpressionNode","method":"emit","line":22}
```

I think it should be possible to set username and password to dynamic values...or not? I don't understand why those properties will be needed on runtime, cause I supposed container-image is just used to build time. 

There is one more warning:

`{"timestamp":"2020-07-15T13:01:31.094Z","sequence":827,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.runtime.ConfigChangeRecorder","level":"WARN","message":"Build time property cannot be changed at runtime. quarkus.container-image.username was gitlab-ci-token at build time and is now empty","thr`
