### ISSUE TITLE
Add a way to find/list default (and for a set of codestarts) config keys in Codestarts

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#11085]
we should somewhere list the default name/data codestart properties/data will be fed in.

_Originally posted by @maxandersen in https://github.com/quarkusio/quarkus/pull/10372#discussion_r462137728_

**Comment by ia3andy** [comment]
Part of #8134

**Comment by ia3andy** [comment]
Here is the list of dynamic configs:
```yaml
gen-info.time: time of generation (in millis)
input.selected-extensions[].name|description|guide
input.selected-extensions-ga: Set of String with the list of extensions groupId:artifactId, usefull for dynamic codestarts depending on selected extensions
```

The list of static configs is here:
https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/codestarts/quarkus/QuarkusCodestartData.java#L18-L37
