### ISSUE TITLE
Enable platform to contribute settings/properties to initial project

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#11256]
**Description**
It would be interesting to enable the platform descriptor to provide input to the initial setup of a project.

Known items: 
- base image for docker native builds
- add maven repositories

**Implementation ideas**
have metadata in platform to seed project generation.

**Comment by maxandersen** [comment]
advantages:
 - no need for different semantics/diffs of quarkus core
 - its clearly documented and explicit to user what is "different"

disadvantages:
 - will (currently) only work for new projects
 - if platform changes its default user won't get updated; but maybe we can print a warning or add a "lint"-check to detect such.

caveat:
 - if diff relevant for extensions we don't have a way to handle it. Would need codestarts that can execute during new addition.

**Comment by maxandersen** [comment]
From chat: 

Figure out A) how the container image will be configurable B) how to represent that somewhere in the platform artifact (platform.json or somewhere else) C) how codestarts hook that into its data D) if/how legacy codegen handles this E) make this wokr in both command line and code.quarkus F) Adjust A - E if one affects the other :wink:

**Comment by ia3andy** [comment]
It seems this issue is also related: https://github.com/quarkusio/quarkus/issues/11096

**Comment by maxandersen** [comment]
Suggestion: 
 - we add "metadata" to platform.json.
 - add keys for:
    - application-properties
    - maven-repos
    - etc.
 - for 1.7.x only add these metadata in redhat universe/platform.
consequence: 
 - 1.7.0 will fail on platform.json with metadata, but not a big concern if we only do it for red hat universe.
 
Codegeneration:
  - choice between doing this in codestarts or good old gen:
    - old gen:
      - requires changes to pom/gradle/properties generation
   - codestart: 
      - suggestion is to use codestart for good old codegen and have flag to enable the more advanced codestarts features.


Best if we can change default platform fetch #11259 to just fetch latest minor (1.7.x instead of 1.x)

**Comment by aloubyansky** [comment]
i'd say
```
metadata
- project-configuration
-- application-properties
-- maven
--- properties
--- repositories
--- plugin-repositories
-- gradle
--- properties
--- repositories
--- plugin-repositories
```

**Comment by maxandersen** [comment]
example:

```yaml
- metadata:
	- application-properties:
		- quarkus.native.builder-image: yadydada:234324
    - maven:
    	- repositories:
			- id:  redhat
            - url: https://maven.repository.redhat.com
        - plugin-repositories
		    - id:  redhat
            - url  https://maven.repository.redhat.com
   - gradle:
    	- repositories:
			- id:  redhat
            - url: https://maven.repository.redhat.com
```
