### ISSUE TITLE
Unable to read a literal value from a secret containing keys ending in "yaml,yml or properties" 

### ISSUE THREAD

**Issue by noelo** [quarkusio/quarkus#11461]
**Describe the bug**
(Describe the problem clearly and concisely.)
When reading a secret any secret key with that ends with ".yml" or ".yaml" or ".properties" is assumed to contain a ConfigSource. It's not possible to read a literal value from a secret with containing keys ending in "yaml,yml or properties" 

**Expected behavior**
Should be able to read literal values from secrets containing keys ending in "yaml,yml or properties" 

**Actual behavior**
2020-08-19 09:42:27,386 DEBUG [io.qua.kub.cli.run.KubernetesConfigSourceProvider] (main) Attempting to read Secret tournamentcache-generated-secret
2020-08-19 09:42:48,593 DEBUG [io.qua.kub.cli.run.AbstractKubernetesConfigSourceUtil] (main) Attempting to convert data in Secret 'tournamentcache-generated-secret' to a list of ConfigSource objects
2020-08-19 09:45:23,074 DEBUG [io.qua.kub.cli.run.AbstractKubernetesConfigSourceUtil] (main) Secret 'tournamentcache-generated-secret' converted into 0ConfigSource objects
2020-08-19 09:46:09,200 DEBUG [io.qua.kub.cli.run.KubernetesConfigSourceProvider] (main) Done reading Secret tournamentcache-generated-secret

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.secrets.enabled=true
quarkus.kubernetes-config.fail-on-missing-config=true
quarkus.kubernetes-config.secrets=tournamentcache-generated-secret

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
```yaml
oc get secret -o yaml tournamentcache-generated-secret
apiVersion: v1
data:
  identities.yaml: Y3JlZGVudGlhbHM6Ci0gdXNlcm5hbWU6IGRldmVsb3BlcgogIHBhc3N3b3JkOiBUZDNaamZaYUJSOEQxQWZrCi0gdXNlcm5hbWU6IG9wZXJhdG9yCiAgcGFzc3dvcmQ6IGMyRm1KdTY3UlQ3R2JVQWsK
kind: Secret
metadata:
  creationTimestamp: "2020-08-09T08:29:49Z"
  labels:
    app: infinispan-secret-identities
    clusterName: tournamentcache
    infinispan_cr: tournamentcache
```
