### ISSUE TITLE
KubernetesProcessor  No registry was set for the container image, so 'ImagePullPolicy' is being force-set to 'IfNotPresent'.

### ISSUE THREAD

**Issue by lvargas0584** [quarkusio/quarkus#11917]
**Describe the bug**
 this warnning appears even though  i put the 'property quarkus.container-image.registry' , so the kubernetes yml is not correctly generated
```
 - image: xxxx.dkr.ecr.us-east-1.amazonaws.com/business-command:1.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: business-command
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```

**Expected behavior**
```
 - image: xxxx.dkr.ecr.us-east-1.amazonaws.com/business-command:0001
        imagePullPolicy: Always
        name: business-command
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
```
**Actual behavior**
(Describe the actual behavior clearly and concisely.)
[log.txt](https://github.com/quarkusio/quarkus/files/5177581/log.txt)

**Configuration**
```#CONFIG
com.app-name=${APP_NAME}
quarkus.package.output-name=${com.app-name}


# Log
quarkus.log.level=${LOG_LEVEL_ROOT:INFO}
#quarkus.log.category."io.smallrye".level=${LOG_LEVEL_ROOT:DEBUG}


#CLIENT SERVICIOS REST
data-core/mp-rest/url=http://data-core:8080


#DOCKER
quarkus.container-image.registry    =   xxxx.dkr.ecr.us-east-1.amazonaws.com
quarkus.container-image.build       =   true
quarkus.container-image.push        =   true
quarkus.container-image.name        =   ${com.app-name}
quarkus.container-image.tag         =   001
quarkus.container-image.group       =


#KUBE
quarkus.kubernetes.replicas=1
quarkus.kubernetes.part-of=core-app
quarkus.kubernetes.image-pull-policy=Always

```
