### ISSUE TITLE
Ability to declare Kubernetes resources requests and limits through properties

### ISSUE THREAD

**Issue by yanaga** [quarkusio/quarkus#12398]
**Description**
Kubernetes allows to specify how much resources (memory and cpu) a container needs to be executed. In addition to this, Kubernetes also allows you to enforce a limit on the amount of resources (again memory and cpu) that a container can use.

This information can be provided inside the following structure in the following yaml excerpt:
```
    spec:
      containers:
        image: quay.io/myrepo/myapp:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
```

It'd be nice if the `quarkus-kubernetes` extension could generate these information using some properties. A proposed name and usage for these properties is:
```
quarkus.kubernetes.resources.requests.memory=64Mi
quarkus.kubernetes.resources.requests.cpu=250m
quarkus.kubernetes.resources.limits.memory=512Mi
quarkus.kubernetes.resources.limits.cpu=1000m
```
