### ISSUE TITLE
Allow override of "level" key's name in json log

### ISSUE THREAD

**Issue by medvedev** [quarkusio/quarkus#12946]
**Description**
Problem: For Google Cloud Logging, every json entry is stored with "default" logging level no matter what level is used by an application. Reason is: the whole body of json entry is stored in Google Cloud Logging as a 2nd-level entry under "jsonPayload" key. This makes logs filtering a bit harder and makes harder or impossible to use GCP [Error reporting](https://cloud.google.com/error-reporting)
However, Google allows to set logging level by specifying "severity" key in log entry's json. Here's [related stackoverflow question](https://stackoverflow.com/questions/43208878/how-does-stackdriver-logging-assert-the-severity-of-an-entry).

Enhancement: Allow to override default "level" name of log level field.  
This is at least useful for Google Cloud Logging, where "severity" field in json is automatically recognized and moved to "top level" of logging entry.

**Implementation ideas**
Extension name: logging-json  
I have at least 2 options in mind:  
1. Add new optional item to config of logging-json extension to override "level" key only
2. Go more complex way and implement a solution that allows name overriding for any log key

I'll create a PR for option 1 very soon

**Comment by medvedev** [comment]
There's already extension allowing override for "level" and much more other configurable options for json logging.  
Here it is: https://github.com/quarkiverse/quarkiverse-logging-json
I'm closing this issue

**Comment by dratasich** [comment]
afaik, name or key overriding is now possible, see [quarkus-loggin-json config](https://quarkus.io/guides/logging#quarkus-logging-json_quarkus.log.console-json-console-logging)

For example, our [ECS](https://www.elastic.co/guide/en/ecs/1.8/ecs-field-reference.html) logging setup in Quarkus apps is:
```
quarkus:
  log:
    console:
      json:
        key-overrides: "timestamp=@timestamp,level=log.level,logger-name=log.logger,thread-name=process.thread.name,thread-id=process.thread.id,process-name=process.name,process-id=process.pid,stack-trace=error.stack_trace"
        excluded-keys: ["loggerClassName", "sequence", "hostName", "mdc", "ndc"]
        additional-field:
          service.name:
            value: "my-service-name"
            type: "string"
```
