### ISSUE TITLE
Hibernate ORM and Hibernate Reactive cannot be used in the same application

### ISSUE THREAD

**Issue by xuxianzhang** [quarkusio/quarkus#13425]
**Describe the bug**
when i boot both **hibernate-reactive and hibernate-orm** in my own project it throw an **IllegalStateException** and Quarkus startup failure

My application.yaml:
```yaml
quarkus:
  datasource:
    jdbc:
      url: ${JDBC_DATABASE_URL:jdbc:mysql://mysql:3306/temple}
    reactive:
      url: ${DATABASE_URL:mysql://mysql:3306/temple}
```

I think it's probably because a private method **checkIsReactive** in **PreconfiguredReactiveServiceRegistryBuilder.class** .
This inspection is not supposed to be here.
It should  be put in **FastBootHibernateReactivePersistenceProvider.getEntityManagerFactoryBuilderOrNull** where the RecordedState be created at.
```java
           RecordedState recordedState = PersistenceUnitsHolder.getRecordedState(persistenceUnitName);
           if(!recordedState.isReactive()){
                log.debug("An Hibernate Reactive serviceregistry can't boot on a non-reactive RecordedState!");
                continue;
           }


            final PrevalidatedQuarkusMetadata metadata = recordedState.getMetadata();
            final BuildTimeSettings buildTimeSettings = recordedState.getBuildTimeSettings();
            final IntegrationSettings integrationSettings = recordedState.getIntegrationSettings();
            RuntimeSettings.Builder runtimeSettingsBuilder = new RuntimeSettings.Builder(buildTimeSettings,
                    integrationSettings);
```

This is more in keeping with the original purpose of the method **getEntityManagerFactoryBuilderOrNull**
