### ISSUE TITLE
Rest-client extension is not compatible with YAML extension

### ISSUE THREAD

**Issue by oscarfh** [quarkusio/quarkus#13506]
The rest-client extension is not compatible with the yaml extension.

Steps to reproduce:
- Follow this tutorial as written: [https://quarkus.io/guides/rest-client](https://quarkus.io/guides/rest-client) . It will work
- Add the yaml extension and migrate your application.properties to application.yaml

The previous definition 
```
org.acme.rest.client.CountriesService/mp-rest/url=https://restcountries.eu/rest 
org.acme.rest.client.CountriesService/mp-rest/scope=javax.inject.Singleton 
```
Will become
```
org.acme.rest.client.CountriesService:
  mp-rest:
    url: https://restcountries.eu/rest
    scope=javax.inject.Singleton
```
 Your application will not start anymore with the given error:
> Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'org.acme.config.DefaultApi2/mp-rest/url' or 'org.acme.config.DefaultApi2/mp-rest/uri' to your Quarkus configuration

The reason is that the YAML extension will generate config entries similar to
`"org.acme.rest.client.CountriesService".mp-rest.url` (double quotes included in the name), while the rest-client extension will look for the following entry: `org.acme.rest.client.CountriesService/mp-rest/url`.

I do not know which extension is misbehaving in this case.

**Comment by phillip-kruger** [comment]
@radcortez I think this is more a config issue than a rest client issue ?

**Comment by jtama-op** [comment]
You should try : 
```yaml
org.acme.rest.client:
    CountriesService/mp-rest/url: https://restcountries.eu/rest
    CountriesService.scope: javax.inject.Singleton
```

**Comment by oscarfh** [comment]
@jtama-op Unfortunately the issue still persists.

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
This is related with https://github.com/quarkusio/quarkus/issues/11744.

One way to have it working is to just add each path to the yaml file like this:

```yaml
org:
  acme:
    rest:
      client:
        CountriesService/mp-rest/url: https://restcountries.eu/rest
```

Alternative, I recommend to set the `configKey` in `@RegisterRestClient` with a simple key like `countries-services-api`. Then you can just use:

```yaml
countries-services-api/mp-rest/url: https://restcountries.eu/rest
```
