### ISSUE TITLE
HTTP Lambda doesn't work with AWS Custom Domains

### ISSUE THREAD

**Issue by jonathanroques** [quarkusio/quarkus#13655]
**Describe the bug**
I have an issue when I'm using my REST API with Custom Domain. 
_Note_ : When I use the InvokeURL it's all good though.
I'm using the maven archetype from the [quarkus guide](https://quarkus.io/guides/amazon-lambda-http).
 
The issue is that with a Custom Domain (base path = hello) the root endpoint /hello doesn't work (missing token error). I can call /hello/myName for instance (I created a new endpoint that prints Hello + id). Looks like I have to add a mapping in my resource : ANY on / but I can't understand why... It works just fine using the InvokeURL ...

**Expected behavior**
My API should work seamlessly with or without Custom Domain.

**Actual behavior**
The API works fine using the InvokeURL, but the root endpoint is not accessible using Custom Domain.

**To Reproduce**

- Generate the maven archetype from this [quarkus guide](https://quarkus.io/guides/amazon-lambda-http).
- Deploy the stack using the guide again
- Create a Custom Domain and link the _hello_ base path this this API
- Call your API with the custom domain, it doesn't work (missing token error)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro-de-Jonathan.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.2.FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

Thanks

**Comment by patriot1burke** [comment]
You will have to set "quarkus.http.root-path=/hello" in application.properties if CustomDomain has a root path.

**Comment by jonathanroques** [comment]
I saw the bug is closed, but shouldn't this be changed in the sam JVM/native yaml files generation ? This would be related to quarkus-lambda-http then.

**Comment by jonathanroques** [comment]
Sure, I just add the / mapping

```
  Resources:
    MyResource:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Events:
          GetResourceForCustomDomain:
            Type: Api
            Properties:
              Path: /
              Method: any
          GetResource:
            Type: Api
            Properties:
              Path: /{proxy+}
              Method: any

```

**Comment by patriot1burke** [comment]
@jonathanroques I can't find documentation on 'GetResourceForCustomDomain'

**Comment by jonathanroques** [comment]
> @jonathanroques I can't find documentation on 'GetResourceForCustomDomain'

Oh it's just a random name you can set. The important part is that the "/" path has to be somewhere in the events list.

**Comment by patriot1burke** [comment]
I'm in the process of switching to proxy 2.0 api.  This might solve the problem in the process.

**Comment by drissamri** [comment]
@patriot1burke do you mean implementing the 2.0 payload for the old REST API's or implementing HTTP API's? (https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api.html which always use payload 2.0)

**Comment by patriot1burke** [comment]
@drissamri Correct.  Its already merged to master.  amazon-lambda-http extension will now use 2.0 payload.

**Comment by drissamri** [comment]
Is there any feature request already to support HTTP API's? Since it's faster, cheaper and supports native OIDC it seems to be come the default over the REST API's on AWS? Otherwise I'll make one now. 

It doesn't support the BinaryMediaTypes  - "*/*" feature so not sure how much of an issue that is for Quarkus

**Comment by patriot1burke** [comment]
I believe its Http API sending APIGatewayHTTPV2Event to a lambda that we convert to an internal format so it works with JAX-RS, Servlet, etc..  

I didn't know there was a difference between Rest API and Http API.  I thought it was just 1.0 vs 2.0 of the json protocol.

**Comment by patriot1burke** [comment]
So, we have extensions that can understand 1.0 and 2.0 of the API Gateway HTTP event json format that is sent to a Lambda.  So you could just use either REST or HTTP APIs as you want I guess.

**Comment by drissamri** [comment]
Ah, that's where the misunderstanding has been in a few tickets, now I see. :) 

The payload is not the only difference, these are two different services grouped in "API Gateway", I think Quarkus counts on the binary mediatype? While this is (probably?) not supported by the HTTP API's, there is more difference than just the payload. 

You can test this out by changing the AWS SAM template where it says type `Type: Api` to `Type: HttpApi`, you'll also need remove/change the Outputs section because the variable used there is not known for HttpApis. When you invoke then you'll see a NullPointer in the quarkus part:  `2021-01-31 16:51:37,110 ERROR [qua.ama.lam.http] (main) Request Failure: java.lang.NullPointerException`

**Comment by patriot1burke** [comment]
Try master.  I changed the generated sam.yaml to use http api and version 2.0

**Comment by patriot1burke** [comment]
@drissamri My current thinking is that I generate 4 .yaml files

* sam.jvm.http-api.yaml
* sam.native.http-api.yaml
* sam.jvm.rest-api.yaml
* sam.native.rest-api.yaml

The http-api.yaml files would be configured to use the 1.0 json protocol with a application.properites configuration option to switch to 2.0 if you were using http-api and cared about which protocol to use.

**Comment by patriot1burke** [comment]
> Ah, that's where the misunderstanding has been in a few tickets, now I see. :)
> 
> There are indeed two JSON models, with REST API's you can choose which one you use.
> With HTTP API's (different service grouped under API Gateway, with different features, cheaper, faster startup, native OIDC, ...) and this can only handle the v2.0 payload. https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-vs-rest.html
> 
> One of the features that is not implemented in HTTP API service is the Binary Media Type, which I guess Quarkus depends on?
> 
> You can test this out by changing the AWS SAM template where it says type `Type: Api` to `Type: HttpApi`, you'll also need remove/change the Outputs section because the variable used there is not known for HttpApis. When you invoke then you'll see a NullPointer in the quarkus part:
> 
> ```
> 2021-01-31 16:51:37,110 ERROR [qua.ama.lam.http] (main) Request Failure: java.lang.NullPointerException
> at io.netty.handler.codec.http.HttpMethod$EnumNameMap.hashCode(HttpMethod.java:211)
> ```

BTW, with the current release 1.11.0.FInal, you should be able to use HttpApi if you switch to using the 1.0 protocol

     Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Events:
          HttpApiEvent:
            Type: HttpApi
            PayloadFormatVersion: 1.0

**Comment by drissamri** [comment]
> @drissamri My current thinking is that I generate 4 .yaml files
> 
> * sam.jvm.http-api.yaml
> * sam.native.http-api.yaml
> * sam.jvm.rest-api.yaml
> * sam.native.rest-api.yaml
> 
> The http-api.yaml files would be configured to use the 1.0 json protocol with a application.properites configuration option to switch to 2.0 if you were using http-api and cared about which protocol to use.

I think it's nice that there is an example deployment file, but in my eyes it's not more than just that. Something to get a quick start up and running but no more. If you are an AWS user you'll have your own templates to reuse or have company specifics in there. I think could even just have one sam.yaml file and add a Parameter to switch between jvm/native, but not sure if that would be much easier for new people. 

That's why I'd just focus on one of the two for the quick start, and personally I'd choose the HTTP API because it's cheaper, faster and should have feature parity with the REST APIs in the future. Besides that the native OIDC integration is a killer feature, which is not available in REST API. Besides that since PayloadFormatVersion 2.0 is the default, I'd default to that in Quarkus too for newly generated applications? 

Just to avoid confusion for others reading this, `PayloadFormatVersion: 1.0` has to be configured one level deeper (and be a String):
```
        Events:
          GetResource:
            Type: HttpApi
            Properties:
              Path: /device
              Method: GET
              PayloadFormatVersion: "1.0"
```

**Comment by jonathanroques** [comment]
Hi,
I'm going back to quarkus after some frontend dev during the last months 🥵 .. I update from 1.10 to 1.13.2 and I have some issues. First of all it looks like `PAyloadFormatVersion` is not required anymore right ?

Secondly, I want to setup some auth using cognito here's what I do : 

```
Globals:
  Function:
    // Handler, runtime etc...
  HttpApi:
    Auth:
      Authorizers:
        OAuth2Authorizer:
          JwtConfiguration:
            issuer: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${ClozzleCognitoUserPoolId}
            audience:
              - !Ref ClozzleCognitoClientAppArn
          IdentitySource: "$request.header.Authorization"
        DefaultAuthorizer: OAuth2Authorizer

Resources:
  Deal:
    Type: AWS::Serverless::Function
    Properties:
      Policies: AWSLambdaBasicExecutionRole
      Events:
        GetResource:
          Type: HttpApi
```

But my request are always authorized, as if the authorizer is not used... Any suggestions, or something I'm doing wrong ? Tough going back to SAM files 😞

Thanks before !
