### ISSUE TITLE
(kubernetes-config) (kubernetes) Weird behavior with setting profiles & getting config-maps on Kubernetes

### ISSUE THREAD

**Issue by Barbiero** [quarkusio/quarkus#13836]
**Describe the bug**

There seems to be an inconsistent behavior with Quarkus' profiles, kubernetes-config and the order in which they are loaded.

When I start quarkus locally, it seems that `kubernetes-config` takes a while to load - to the point that `@Singleton` classes don't read the correct configuration on their `@PostConstruct` callbacks.

This is worse when running inside a kubernetes cluster(I'm using WSL2 Docker Desktop Kubernetes for testing, but I also experienced this on GKE). On a cluster, it seems that *no profile is set* at startup, unless I pass a `QUARKUS_PROFILE` environment variable. The above behavior with kubernetes-config is also present.

This caused a problem for us because we're trying to use kafka with quarkus, but the kafka configuration would be set on a configmap - but that won't work because kafka loads their configurations early in the startup cycle, and it happens before kubernetes-config.

**Expected behavior**

I expect all configuration and profiles to be set before anything else, including external configuration like kubernetes-config. I also expect that when building with `-Dquarkus.profile`, that profile will be the one set at startup when running on kubernetes.

**Actual behavior**

`kubernetes-config` is loaded in a delayed fashion, seemingly after `@PostConstruct` of `@Singleton` classes.

build-time `-Dquarkus.profile` seems to be loaded in the same delayed fashion; during startup, there's no profile set but after some time, it will set the correct profile.

It's not clear to me _when_ the configuration is loaded either.

**To Reproduce**

I'm attaching the project I used to reproduce it minimally, but I'll also add a few steps to explain what I did.
Project: [quarkus-configmap-bug.tar.gz](https://github.com/quarkusio/quarkus/files/5679111/quarkus-configmap-bug.tar.gz)

This project is a basic REST api I generated through code.quarkus.io

Extra steps:

Create a simple config-map in a kubernetes cluster:

```yaml
apiVersion: v1
data:
  application.yaml: |-
    test:
      value: TEST-K8S
    "%hmg":
      test:
        value: TEST-HMG-K8S
kind: ConfigMap
metadata:
  name: example-cfg
  namespace: default
```

Please take a look at `MyObjectMapperCustomizer.java` and `JacksonResource.java`, in particular their `onStart` methods which were used to log `quarkus.profile` and `test.value`, but at different points in time(due to resource/singleton construct behavior).

- Run  with `./mvnw quarkus:dev -Dquarkus.profile=hmg`
- Execute a basic REST request like `curl -X GET "http://localhost:8080/resteasy-jackson/quarks" -H  "accept: application/json"` so that `JacksonResource` loads itself
- Watch the difference in behavior in your logs
- use `./mvnw package -Dquarkus.profile=hmg` to build an image and run it on your local kubernetes cluster(like minikube or Docker Desktop-backed one)
- Use `kubectl port-forward` to forward the 8080 port and repeat the above request
- Use `kubectl logs` to see the difference in behaviors in the logs.

**Configuration**
```yaml
test:
  value: TESTE
quarkus:
  kubernetes:
    image-pull-policy: IfNotPresent
  kubernetes-config:
    config-maps: example-cfg
    namespace: default
    enabled: false
  package:
    type: fast-jar
  container-image:
    build: true

"%hmg":
  test:
    value: TESTE-HMG
  quarkus:
    kubernetes-config:
      config-maps: example-cfg
      enabled: true
    container-image:
      build: true
```

**Environment (please complete the following information):**
The behavior was reproduced in Docker-Desktop kubernetes local cluster and GKE.

```
❯ uname -a
Linux DESKTOP-PEDRO 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

java version:
```
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment 18.9 (build 11.0.9+11)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.9+11, mixed mode)
```

Quarkus 1.10.3.Final

Maven:
```
❯ ./mvnw --version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/barbiero/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /home/barbiero/.sdkman/candidates/java/11.0.9.open-adpt
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "4.19.104-microsoft-standard", arch: "amd64", family: "unix"
```
