### ISSUE TITLE
Support complex wildcard path matching for authorization of web endpoints

### ISSUE THREAD

**Issue by codependent** [quarkusio/quarkus#14047]
**Description**
According to the [documentation](https://quarkus.io/guides/security-authorization) path matching supports wildcards at the end of the path:

> Permission sets can also specify paths and methods as a comma separated list. If a path ends with * then it is considered to be a wildcard match and will match all sub paths, otherwise it is an exact match and will only match that specific path

There is a clear limitation regarding the usage of wildcards which doesn't allow us to compose complex authorization expressions.

This use case has come across in many occasions, in which I have an API which requires an authorization config like:

`/api/clients/{clientid}/accounts` -> needs to be **private**
`/api/clients/{clientid}/public-profile` -> needs to be **public**

This could be configured like this:

```
quarkus:
  http:
    port: 8081
    cors: false
    auth:
      permission:
        permit1:
          policy: permit
          paths: /api/clientes/*/public-profile
          methods: GET,HEAD,POST,PUT,OPTION,PATCH
        authenticated:
          policy: authenticated
          paths: /api/clientes/*/accounts
          methods: GET,HEAD,POST,PUT,OPTION,PATCH
```

However this isn't supported since wildcards are only allowed at the end of the path. 

Could you consider supporting it?
