### ISSUE TITLE
The property quarkus.kubernetes-config.enabled: "true" is ignored in the Kubernetes configuration

### ISSUE THREAD

**Issue by dloiacono** [quarkusio/quarkus#14275]
**Describe the bug**
Even you enable the possibility to read the configuration from the k8s config maps via environment varible, quarkus ignore the flag.

**Expected behavior**
The config map is read

**Actual behavior**
The flag is ignored and the config map is ignored

**To Reproduce**
Specify the `quarkus.kubernetes-config.enabled: "true"` in the application.yml like this:

```
  kubernetes:
    env:
      configmaps: my-config-map
      vars:
        quarkus.kubernetes-config.enabled: "true"
  kubernetes-config:
    enabled: false
    config-maps: my-config-map
```

**Configuration**
```
  kubernetes:
    env:
      configmaps: my-config-map
      vars:
        quarkus.kubernetes-config.enabled: "true"
  kubernetes-config:
    enabled: false
    config-maps: my-config-map
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
  ```
 Darwin NMOL538577.local 20.3.0 Darwin Kernel Version 20.3.0: Mon Dec  7 22:04:02 PST 2020; root:xnu-7195.80.16.111.1~1/RELEASE_X86_64 x86_64
 ```
 - Output of `java -version`: 
  ```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)
 ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.10.5.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
 ```
 Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/user1/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.9.1, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Additional context**
Kubernates cluster
