### ISSUE TITLE
Issues with sidecar probes

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#14795]
**Describe the bug**
There are several problems with attempting to configure sidecar probes through the application.properties.  First any probe properties such as http-action-path, seem to be ignored.  Second the probe port is set to the value of quarkus.http.port - which is not correct for the sidecar container.

**Expected behavior**
Using the properties:
quarkus.kubernetes.sidecars.x.liveness-probe.http-action-path=/q/health/ready
quarkus.kubernetes.sidecars.x.ports.http.container-port=9090

It is expected that the generated target/kubernetes/kubernetes.yml sidecar container would contain:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/q/health/ready"
            port: 9090
```

**Actual behavior**
Instead the generated kubernetes.yml contains an empty path and the quarkus.http.port for the port:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: ""
            port: 8080
```

**Environment:**
Quarkus version 1.11.0.Final
Maven info:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.7-100.fc32.x86_64", arch: "amd64", family: "unix"

See also an earlier issue: https://github.com/quarkusio/quarkus/issues/10308
