### ISSUE TITLE
kubernetes-config generated role for secrets is broad

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15279]
**Description**
quarkus-kubernetes-config generates the following role:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
```

However following https://kubernetes.io/docs/concepts/configuration/secret/#best-practices the ability to list/watch secrets across an entire namespace is considered broadly privileged.

**Implementation ideas**
The current implementation doesn't seem to need list or watch.  It also could restrict the role to only the resourceName of the secrets accessed.  

I'm also not sure how this meshes with the ability to set quarkus.kubernetes-config.namespace since a rolebinding is created.
