### ISSUE TITLE
Fault tolerance annotations not playing well with ThreadLocalPool

### ISSUE THREAD

**Issue by nachogiljaldo** [quarkusio/quarkus#15600]
**Describe the bug**
If you annotate a class with org.eclipse.microprofile.faulttolerance.Asynchronous then lots of threads are created and
the ThreadlocalPool can result on max number of connections restrictions in the database being reached.

One could try to return a Future, but then there are other complains from the internal validations. It is also funny that it requires exactly a Future and doesn't take a CompletableFuture, shouldn't it work with any future?.

That annotation is required for org.eclipse.microprofile.faulttolerance.Timeout to work (which is also inconvenient because it requires you to return a CompletionStage, when perhaps it could also handle Uni/Multi ?).

Example:
```java
  @Incoming("Something")
  @Counted(name = "received", description = "How many messages were received.")
  @Timeout(500)
  @Retry(maxDuration = 2000, maxRetries = 6, retryOn = {TimeoutException.class})
  @Asynchronous
  public CompletionStage<SomeResult> process(
      Message<SomeInput> record) {
```

I know one could alternatively use reactive handlers to deal with the timeout and the retries, but we started this way. If this is not the right way, could some documentation be added with the correct example?

**Expected behavior**
That the thread context would somehow be reused so all threads spawn by the Asynchronous use the same connection pool instead of creating one for each one of them.

**Actual behavior**
Each call to the method is executed in a different thread (as expected), creating multiple database connection pools and potentially reaching max limit in certain database (postgres in my case).

**To Reproduce**

On version 1.11.x or 1.12.x create a kafka listener with:

```java
  @Incoming("EnvironmentsWithGeo")
  @Counted(name = "received", description = "How many environments were received.")
  @IncomingLogged
  @Timeout(500)
  @Retry(maxDuration = 2000, maxRetries = 6})
  @Asynchronous
  public CompletionStage<Void> process(
      Message<SomeInput> record) {
    someReactiveDao.doSomething(record.getPayload()).toCompletableFuture();
  }
```

As soon as you put load on it, lots of threads are started and it reaches the max number of db connections on postgres.

**Configuration**
```yaml
# Add your application.properties here, if applicable.
quarkus:
  datasource:
    db-kind: postgresql
    metrics:
      enabled: true
    username: <redacted>
    password: <redacted>
    jdbc:
      url: jdbc:postgresql://localhost:5432/<redacted>
      max-size: 1
    reactive:
      url: postgresql://localhost:5432/<redacted>
      max-size: 20
kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    incoming:
      <redacted>:
        enable:
          auto:
            commit: true
        connector: smallrye-kafka
        topic: <redacted>
        pattern: true
        failure-strategy: ignore
        group:
          id: <redacted>
        value:
          deserializer: <redacted>
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.x or 1.12.x, the behaviour is not observed in 1.10.5.FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
N/A
