### ISSUE TITLE
AWS Serverless ApiGateway rawPath is null

### ISSUE THREAD

**Issue by igor-dmitriev** [quarkusio/quarkus#15740]
## Describe the bug
I am using Quarkus with GraalVM with native-image which is deployed on AWS Serverless:

- AWS ApiGateway

- AWS Lambda

SAM template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus Lambda play
Globals:
  Api:
    EndpointConfiguration: REGIONAL
    BinaryMediaTypes:
      - "*/*"
Parameters:
  Environment:
    Type: String
  CommitSha:
    Type: String
  MemorySize:
    Type: Number
  SecurityGroupsIds: # list of string dynamic reference is not yet supported
    Type: AWS::SSM::Parameter::Value<List<String>>
  SubnetIds:
    Type: AWS::SSM::Parameter::Value<List<String>>

Resources:
  ApiDeployment:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment

  BackendNative:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "quarkus-lambda-play-${Environment}"
      Description: !Ref CommitSha
      Handler: not.used.in.provided.runtimei
      Runtime: provided
      CodeUri: "../../build/function.zip"
      AutoPublishAlias: live
      MemorySize: !Ref MemorySize
      Timeout: 180
      Role: !Sub "{{resolve:ssm:/myapp/${Environment}/lambda/role-arn:1}}"
      ReservedConcurrentExecutions: 10
      Tracing: Active
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
            RestApiId: !Ref ApiDeployment
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroupsIds
        SubnetIds: !Ref SubnetIds
      Tags:
        project: "Quarkus Lambda play"

```

I upgraded Quarkus from `1.11.3.Final` to `1.12.2.Final`
It is failing now with an error:
```

  | 2021-03-15T22:34:53.850+02:00 | 2021-03-15 20:34:53 \| [ERROR] http - Request Failure: java.lang.NullPointerException
-- | -- | --
  | 2021-03-15T22:34:53.850+02:00 | at java.lang.StringBuilder.<init>(StringBuilder.java:124)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:153)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:59)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:39)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:152)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:78)
  | 2021-03-15T22:34:53.850+02:00 | at java.lang.Thread.run(Thread.java:834)

```

### Expected behavior
it should work fine how it worked in `1.11.3.Final` version

### Actual behavior

Fails with an error
```

  | 2021-03-15T22:34:53.850+02:00 | 2021-03-15 20:34:53 \| [ERROR] http - Request Failure: java.lang.NullPointerException
-- | -- | --
  | 2021-03-15T22:34:53.850+02:00 | at java.lang.StringBuilder.<init>(StringBuilder.java:124)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:153)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:59)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:39)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:152)
  | 2021-03-15T22:34:53.850+02:00 | at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:78)
  | 2021-03-15T22:34:53.850+02:00 | at java.lang.Thread.run(Thread.java:834)

```

Most likely it is relevant to this change - https://quarkus.io/blog/path-resolution-in-quarkus/

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1.  Generate 'hello world' project
2. Build a native image, deploy function.zip to AWS Lambda
3. Trigger the Lambda

### Configuration
```properties
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} | %X{userId} [%-5p] %c{1} - %m%n
quarkus.log.category."software.amazon.awssdk".level=WARN
quarkus.log.category."software.amazon.awssdk.request".level=DEBUG
quarkus.log.category."io.quarkus.bootstrap".level=WARN
quarkus.log.category."com.igor.repository".level=DEBUG

quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${JDBC_LOGIN}
quarkus.datasource.password=${JDBC_PASSWORD}
quarkus.datasource.jdbc.url=${JDBC_URL}
quarkus.mybatis.map-underscore-to-camel-case=true

quarkus.native.additional-build-args=--report-unsupported-elements-at-runtime

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `java -version`
11

### GraalVM version (if different from Java)
21.0.0.2

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
6.5.1

## Additional context
(Add any other context about the problem here.)
