### ISSUE TITLE
Regression issue: Wrong port in OpenShift route

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16089]
## Describe the bug
(Describe the problem clearly and concisely.)

### Actual behavior
The port in the route is set to 80 and it should be 8080.

## To Reproduce

1. `mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create     -DprojectGroupId=org.acme     -DprojectArtifactId=openshift-quickstart     -DclassName="org.acme.rest.GreetingResource"     -Dpath="/greeting"  -Dextensions=openshift`
2. cd `openshift-quickstart`
3. Deploy it using `mvn package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.expose=true`

The maven command finished ok, but when trying to have access to the application, the route endpoint always gets 503 Gateway error. 

The problem is that the port is set to 80 and it should be 8080.

See the whole content of the openshift.yml file:

```yaml
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: openjdk-11
spec:
  dockerImageRepository: registry.access.redhat.com/ubi8/openjdk-11
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec: {}
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  output:
    to:
      kind: ImageStreamTag
      name: openshift-quickstart:1.0.0-SNAPSHOT
  source:
    binary: {}
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: openjdk-11:latest
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  replicas: 1
  selector:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.openshift.io/vcs-url: <<unknown>>
        app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
      labels:
        app.kubernetes.io/name: openshift-quickstart
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.openshift.io/runtime: quarkus
    spec:
      containers:
      - args:
        - -Dquarkus.http.host=0.0.0.0
        - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        - -jar
        - /deployments/quarkus-run.jar
        command:
        - java
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/openshift-quickstart-1.0.0-SNAPSHOT-runner.jar
        image: jcarvaja/openshift-quickstart:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: openshift-quickstart
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - openshift-quickstart
      from:
        kind: ImageStreamTag
        name: openshift-quickstart:1.0.0-SNAPSHOT
    type: ImageChange
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2021-03-29 - 10:50:37 +0000
  labels:
    app.kubernetes.io/name: openshift-quickstart
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: openshift-quickstart
spec:
  port:
    targetPort: 80
  to:
    kind: Service
    name: openshift-quickstart
```

### Quarkus version or git rev
999-SNAPSHOT

(It works fine in 1.12+ and 1.13.0.Final)

## Additional context
I think this is another regression issue caused by [this change](https://github.com/quarkusio/quarkus/commit/e7acfd4a687e75aaab37f6c0778b678a0ae2a629). Another related issue is https://github.com/quarkusio/quarkus/issues/15953
