### ISSUE TITLE
There's no way of marking an env configmap or secret as optional

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#16690]
## Description
When using a list property https://quarkus.io/guides/deploying-to-kubernetes#environment-variables-from-secret to associate configmaps or secrets with the env using envFrom, they will always be marked as optional: false

**Comment by shawkins** [comment]
As a workaround you can use the src/main/kubernetes.yml fragment, instead of a config property:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-name
spec:
  template:
    spec:
      containers:
      - name: container-name
        envFrom:
        - configMapRef:
            name: map-name
            optional: true
```
