### ISSUE TITLE
quarkus.openshift.annotations not applied to deployment config

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkus#16776]
## Describe the bug
When deploying an app with the OpenShift extension, and specifying `-Dquarkus.openshift.annotations."app.openshift.io/connects-to"=foo`, the annotation is never applied (and therefore the desired visual connector doesn't show in the web console in OpenShift 4.6)

### Expected behavior
The annotation is applied to the `DeploymentConfig` and a visual connector shows up in the web console:

![image](https://user-images.githubusercontent.com/861894/115930332-42842a80-a457-11eb-8a5d-b90e21540c89.png)

### Actual behavior
No annotation is applied and therefore no connector is shown.

![image](https://user-images.githubusercontent.com/861894/115930429-6e9fab80-a457-11eb-8733-4e4add39cff1.png)

## To Reproduce

1. Create sample app with OpenShift connector
2. Configure `application.properties` to deploy to OpenShift
3. Deploy to OpenShift

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.openshift.annotations."app.openshift.io/connects-to"=foo
```

### Output of `uname -a` or `ver`

`Linux 883b2ff1b6d0 4.15.0-123-generic #126~16.04.1-Ubuntu SMP Wed Oct 21 13:48:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)
```

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

`1.13.2`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/maven/apache-maven-3.6.3
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /usr/local/jdk-11.0.10+9
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-123-generic", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
I can't reproduce this.

I added `quarkus.openshift.annotations."app.openshift.io/connects-to"=foo` to an application that contained the `quarkus-openshift` extension and 

it generated the following `DeploymentConfig`:

```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2021-04-24 - 13:54:34 +0000
    app.openshift.io/vcs-url: https://github.com/geoand/quarkus-quickstarts.git
    app.openshift.io/connects-to: foo
    app.quarkus.io/commit-id: 5785b865e2472bf5f1e0c5221540f674ec71408d
    app.quarkus.io/vcs-url: https://github.com/geoand/quarkus-quickstarts.git
  labels:
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
  name: getting-started
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: getting-started
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2021-04-24 - 13:54:34 +0000
        app.openshift.io/vcs-url: https://github.com/geoand/quarkus-quickstarts.git
        app.openshift.io/connects-to: foo
        app.quarkus.io/commit-id: 5785b865e2472bf5f1e0c5221540f674ec71408d
        app.quarkus.io/vcs-url: https://github.com/geoand/quarkus-quickstarts.git
      labels:
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: getting-started
    spec:
      containers:
      - args:
        - -Dquarkus.http.host=0.0.0.0
        - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
        - -jar
        - /deployments/quarkus-run.jar
        command:
        - java
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: JAVA_APP_JAR
          value: /deployments/getting-started-1.0.0-SNAPSHOT-runner.jar
        image: gandrian/getting-started:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: getting-started
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - getting-started
      from:
        kind: ImageStreamTag
        name: getting-started:1.0.0-SNAPSHOT
    type: ImageChange
```

Am I missing something?
