### ISSUE TITLE
Qurakus Dev mode crash

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#17213]
## Describe the bug
@radcortez 
The JVM crashes on starting in Quarkus Dev mode. This could be due to changes in smallrye config in Quarkus 1.13.4.FInal
and is a follow up to issues: #14847
Also see [zulip chat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.201.2E13.2E3.2EFinal.20issue/near/237205212)

This could be due to the latest change in smallrye config (included in Quarkus.1.13.4.FInal) or Java 16. Note that issue is identical for x86 or ARM64 MacOs, if that matters.

## To Reproduce
Find the attached [forRoberto.zip](https://github.com/quarkusio/quarkus/files/6474996/forRoberto.zip) ZIP file.
Save the config file (given below) somewhere (say /temp/config.yaml) and run:
>./gradlew -p dbproxy clean quarkusBuild
> ./gradlew -p dbproxy  -Dsuspend=true -Dsmallrye.config.locations=/temp/config.yaml

In your IDE, place a break point into ```Main.onStart``` . Instead of stopping there, the app crash and the JVM returns exits code 1.

### Configuration
```yaml
proxies:
#  encryption:
#    level: NOT_SUPPORTED
#    ssl_protocol: TLS
#    truststore:
#      location: /temp/keys
#      format: PCKS12
#      password: secret
    keystore:
      location: /temp/keys1
        format: PCKS12
        password: secret1
  -
      type: mssql
      name: first
      input:
        mssql:
          server: 192.168.1.10
          port: 1434
          user: 'test'
          password: 'test'
      read:
        regex: '(?i)^\s*select.*'
        mssql:
          server: 127.0.0.1
          port: 1433
          user: 'sa'
          password: 'Test!1234'
      write:
        mssql:
          server: 127.0.0.1
          port: 1433
          user: 'sa'
          password: 'Test!1234'
  -
      type: mssql
      name: second
      input:
        mssql:
          server: 192.168.1.10
          port: 1435
          user: 'test'
          password: 'test'
      read:
        regex: '(?i)^\s*select.*'
        mssql:
          server: 127.0.0.1
          port: 1433
          user: 'sa'
          password: 'Test!1234'
      write:
        mssql:
          server: 127.0.0.1
          port: 1433
          user: 'sa'
          password: 'Test!1234'
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
MacBook-Air.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:41 PDT 2021; root:xnu-7195.101.2~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`
openjdk version "16.0.1" 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9)
OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode)

### Quarkus version or git rev
Quarkus.1.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
------------------------------------------------------------
Gradle 7.0.1
------------------------------------------------------------

Build time:   2021-05-10 16:08:58 UTC
Revision:     67e618faef187783dadd03a34fdab9dc71b85b19

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16.0.1 (BellSoft 16.0.1+9)
OS:           Mac OS X 11.3.1 aarch64

## Additional context
(Add any other context about the problem here.)
