### ISSUE TITLE
 Add option to support selection of SSL key in JKS keystore using an alias property

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#17424]
## Description

Please see https://github.com/eclipse-vertx/vert.x/issues/3926 which has been fixed so a new Quarkus Vert.x HTTP option can be added after an update to the next Vert.x 4.x

**Comment by mickroll** [comment]
For a good starting point for property names see https://docs.spring.io/spring-cloud-dataflow/docs/1.1.0.M1/reference/html/getting-started-security.html

```
ssl:
    key-store: path/to/keystore
    key-store-password: yourKeyStorePassword
    key-alias: yourKeyAlias
    key-password: yourKeyPassword
    trust-store: path/to/trust-store
    trust-store-password: yourTrustStorePassword
```
