### ISSUE TITLE
improve kubernetes guide to explain how we use var name including dot

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#17629]
## Description

Proposition: Improve the kubernetes guide to explain that we use var name including dot(s) as currently there is no mention about that.

By example, you can use such a syntax with 2 vars `greeting.message`, `greeting.name` if they are enclosed with double quotes
```
quarkus.kubernetes.env.vars."greeting.message"=Hello from Kubernetes to
quarkus.kubernetes.env.vars."greeting.name"=Quarkus developers
```

to generate such kubernetes Deployment MANIFEST
```
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GREETING_MESSAGE
              value: Hello from Kubernetes to
            - name: GREETING_NAME
              value: Quarkus developers
```
