### ISSUE TITLE
2.0.0.CR3 smallrye graphql error code exception not being displayed

### ISSUE THREAD

**Issue by dvddhln** [quarkusio/quarkus#17712]
## Describe the bug
Currently when trying to transform an exception to the graphql error code exception class the error exception is not displayed in the response. When running 1.13.6.Final it is working fine. Perhaps this has already been covered in some issue, but any light on this matter would be nice :)

### Expected behavior
Expected output when running with 1.13.6.Final

```
{
  "errors": [
    {
      "message": "Relation: movieId: 1 and actorId: 1 was found.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addActorToMovie"
      ],
      "extensions": {
        "exception": "control.exception.AlreadyExistingException",
        "classification": "DataFetchingException",
        "code": "ALREADY_EXISTING"
      }
    }
  ],
  "data": {
    "addActorToMovie": null
  }
}
```
### Actual behavior
Exception in 2.0.0.CR3
```
{
  "errors": [
    {
      "message": "Server Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "addActorToMovie"
      ],
      "extensions": {
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "addActorToMovie": null
  }
}
```
## To Reproduce

1. $ git clone https://github.com/dvddhln/quarkus-reactive-hibernate-graphql-crud.git
2. $ git checkout 2.0.0.CR3-smallrye-graphql-bug 
3. $  docker run -d --rm --name my_reative_db -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=my_db -p 5432:5432 postgres:10.5
3. $ ./mvnw compile quarkus:dev
4. Go to http://localhost:8080/q/graphql-ui/
5. Add mutation and perform twice to see the actual output
6. Perform above steps for master branch which is on 1.13.6.Final

```
mutation addActorToMovie {
  addActorToMovie(movieId: 1, actorId: 1) {
    title
    releaseDate
    director
    actors {
      name
      id
    }
  }
}
```

### Configuration
```
quarkus:
  log:
    level: INFO
  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
    dialect: org.hibernate.dialect.PostgreSQL10Dialect
    jdbc:
      timezone: UTC
  datasource:
    db-kind: postgresql
    username: user
    password: password
    jdbc: false
    reactive:
      url: postgresql://localhost:5432/my_db
      max-size: 20
mp:
  graphql:
    showErrorMessage:
      - control.exception.AlreadyExistingException  
```

### Screenshots
Expected output:

![Screenshot from 2021-06-05 12-41-20](https://user-images.githubusercontent.com/2706002/120889002-724c5380-c5fb-11eb-8234-0f7bcb36a85f.png)
