### ISSUE TITLE
Kubernetes hostname configuration option in application.properties

### ISSUE THREAD

**Issue by martijnburgers** [quarkusio/quarkus#18383]
## Description

For licensing reasons I need to set the hostname of my pod to a certain name. For this I need to set the hostname in the generated Kubenetes json/yaml.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-url: https://blah.com
    app.quarkus.io/build-timestamp: 2021-07-04 - 15:35:08 +0000
    app.quarkus.io/commit-id: ab6d7f92a16c97207dcb2da63b16a6a62c61e610
  labels:
    app.kubernetes.io/name: some-service
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: some-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: some-service
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/vcs-url: https://blah.com
        app.quarkus.io/build-timestamp: 2021-07-04 - 15:35:08 +0000
        app.quarkus.io/commit-id: ab6d7f92a16c97207dcb2da63b16a6a62c61e610
      labels:
        app.kubernetes.io/name: some-service
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      hostname: XXXXXXXvm
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: blah.azurecr.io/some-service:1.0.0-SNAPSHOT
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/live
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: some-service
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /q/health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
```

The hostname is located under spec:

The trick with `pod.beta.kubernetes.io/hostname` doesn't work on my cluster.
