### ISSUE TITLE
Add profile specific config files to watched resources in dev mode

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#18731]
### Description

A file like `application-dev.yaml` (or .properties) is not automatically watched for changes, but the regular `application.yaml` is.

There seems to be no good reason for this difference.

Workaround; DIY:
```yaml
quarkus:
  live-reload:
    watched-resources:
      - application-dev.yaml
```

See also: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Profile.20aware.20config.20files/near/246092779
