### ISSUE TITLE
Migration guide Quarkus 2.0 / non-application endpoints

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#18855]
### Describe the bug

[Migration guide](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.0#legacy-redirect-for-non-application-endpoints-such-as-health) talks about non-application endpoint redirection, but should also talk about the impact of these changes in Openshift `ServiceMonitor` resource. 

If your services export metrics to Prometheus you must create an OCP ServiceMonitor, for example:
```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-app-monitor
  name: prometheus-app-monitor
spec:
  endpoints:
  - interval: 30s
    targetPort: 8080
    path: /q/metrics
    scheme: http
  selector:
    matchLabels:
      # Configured in application.properties: quarkus.openshift.labels.app-with-metrics
      app-with-metrics: 'quarkus-app'
```

This resource is not created by default by Quarkus so must be changed by the end-user itself.

Required changes:  path: /metrics -> path: /q/metrics
