### ISSUE TITLE
Map of Map not supported in SmallRye ConfigMapping

### ISSUE THREAD

**Issue by neoludo** [quarkusio/quarkus#19091]
Hi,

considering that interface :
```
@ConfigMapping(prefix = "sample")
public interface SampleConfig {
    Map<String, Map<String, String>> values();
}
```

and that application.yml
```
sample:
  values:
    key1:
      value1: xoxox11
      value2: xoxox12
      value3: xoxox13
    key2:
      value1: xoxox21
      value2: xoxox22
```

I'm getting that value in my SampleConfig object :
Map {
   value1 -> Map { value1: xoxox21 },
   value2 -> Map { value2: xoxox22 },
   value3 -> Map { value3: xoxox13 }
}

instead of :
Map {
   key1-> Map { value1: xoxox11, value2: xoxox12, value3: xoxox13 },
   key2 -> Map { value1: xoxox21, value2: xoxox22 }
}

Test to reproduce :
```
@QuarkusTest
public class SampleConfigTest {

    @Inject
    SampleConfig config;

    @Test
    public void testInjectedValues() {
        Assert.assertNotNull(config.values());
        Assert.assertTrue(config.values().size() == 2);
        Assert.assertTrue(config.values().keySet().stream().allMatch(s -> s.startsWith("key")));
    }

}
```

**Comment by vsevel** [comment]
you can do:

```
@ConfigMapping(prefix = "app")
public interface App {

    List<Server> servers();
}

public interface Server {
    
    String name();
    
    String host();

    int port();
}
```

Then with this config:
```
app:
  servers:
    - name: server1
      host: host1
      port: 1234
    - name: server2
      host: host2
      port: 4567
```

you can do:
```
    @Inject
    App config;

    @Path("/config")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String config() {
        config.servers().forEach(v -> log.info(v.name() + " => " + v.host() + ":" + v.port()));
        return ""+config.servers().size();
    }
```

I was not able to use a `Map` indeed. @radcortez is this possible?

**Comment by vsevel** [comment]
actually this works as well:

```
@ConfigMapping(prefix = "app")
public interface App {
    Map<String, Server> servers();
}

public interface Server {  
    String host();
    int port();
}
```
```
app:
  servers:
    server1:
      host: host1
      port: 1234
    server2:
      host: host2
      port: 4567
```
```
config.servers().forEach((name, server) -> log.info(name + " => " + server.host() + ":" + server.port()));
```
