### ISSUE TITLE
kubernetes extension: should not annotate unrelated resources

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#19168]
### Describe the bug

I'm using qurkus-kubernetes to generate k8s resources and I noticed that as example, some resources like ServiceAccount gets surprisingly annotated with some prometheus annotations, like: 

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/commit-id: 93f94a53d2f0d20c363962d0cb236e8267d4d692
    app.quarkus.io/build-timestamp: 2021-08-02 - 12:51:37 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
```

I think, only the relevant should be annotated

### Expected behavior

kubernetes extension should not annotate unrelated resources
