### ISSUE TITLE
dev services for confluent schema registry

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#19277]
### Description

Following https://quarkus.io/guides/kafka-schema-registry-avro,  Quarkus automatically starts docker containers for Kafka and Apicurio registry, but won't for Confluent schema registry.

Confluent has published an official docker image [cp-schema-registry](https://hub.docker.com/r/confluentinc/cp-schema-registry) but unluckily it's too big.

~~BTW, when use Confluent schema registry, quarkus doesn't automatically include `avro-maven-plugin`, I have to explicitly configure it in pom.xml,  see https://github.com/quarkusio/quarkus/issues/19276.~~ (Resolved by adding extension `quarkus-avro`)

### Implementation ideas

Confluent schema registry is written in pure Java, maybe Quarkus can just start a Java process for the registry service.

https://github.com/confluentinc/schema-registry

**Comment by Ladicek** [comment]
CC @cescoffier @ozangunalp

**Comment by cescoffier** [comment]
I would stay away from running it in Java because of port conflicts and classloading issues. The lack of a slim and supported image is annoying. Doing one ourselves would require a non-meaningless maintenance cost.

**Comment by Ladicek** [comment]
Also the Confluent Schema Registry code, except of the client libraries, is licensed under Confluent Community License, which doesn't seem to be an open source license. So there's a risk there, in my opinion (which doesn't weigh much, as I'm not a lawyer :-) ).

**Comment by lw-mcno** [comment]
Maybe for some using the Confluent-compatible endpoints of Apicurio registry would be enough. Here's one working configuration:

```yaml
  quarkus:
    apicurio-registry:
      devservices:
        port: 50501

    kafka-streams:
      schema-registry-url: 'http://localhost:${quarkus.apicurio-registry.devservices.port}/apis/ccompat/v6'
```
