### ISSUE TITLE
Allow overriding rbac permissions in KubernetesClientProcessor

### ISSUE THREAD

**Issue by jmrodri** [quarkusio/quarkus#19286]
### Description

The rbac generated by the kubernetes-extension only adds the `view` role. The [documentation](https://quarkus.io/guides/deploying-to-kubernetes#using-the-kubernetes-client) does mention that you have to manually edit this, but this is less than optimal when you are trying to automate building an operator.

We're currently building a [scaffolder](https://github.com/operator-framework/java-operator-plugins) to integrate with the [Operator Framework Operator SDK](https://github.com/operator-framework/operator-sdk/) and Quarkus. When the user runs `mvn install` we get incorrect rbac as view is not enough for an Operator. I've looked into adding `kustomize` but that seems out of place for this project. 

So being able to specify the roles we need a more advanced rbac mechanism, here is the sample we generate for the Go sample operators: https://github.com/operator-framework/operator-sdk/tree/master/testdata/go/v3/memcached-operator/config/rbac

**Comment by geoand** [comment]
cc @iocanel

**Comment by geoand** [comment]
Can you expand a little on what exactly you would like to see?

**Comment by jmrodri** [comment]
@geoand @iocanel today only a `view` role is generated and I don't see any way to customize it to generate different rbac rules. I would want to create something like the sample below without having the user edit it by hand. Are there any annotations or application.properties we could set to allow for a more complex rbac.yaml to be generated? 

```yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/finalizers
  verbs:
  - update
- apiGroups:
  - cache.example.com
  resources:
  - memcacheds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
```
