### ISSUE TITLE
quarkus-kubernetes should support security-context

### ISSUE THREAD

**Issue by anthonydahanne** [quarkusio/quarkus#19385]
### Description

quarkus-kubernetes supports many features from the `Deployment` resource, such as : `image-pull-policy` , `liveness-probe`, etc., see https://quarkus.io/guides/deploying-to-kubernetes#configuration-options

Unfortunately, it does not support `securityContext` (see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for details about this feature)

### Implementation ideas

Not sure if the integration with fabric8 prevents adding this feature, it looks kind of big since there are many options to a `securityContext` 

I am using this workaround for now:

* I create a resource named `patch-deployment.yml` with this content:
    
```
spec:
  template:
    spec:
      containers:
        - name: my
          securityContext:
            runAsNonRoot: true
            runAsUser: 1001
```

* and then I patch my deployment:

```
kubectl  patch deployment my --patch "$(cat src/main/kubernetes/patch-deployment.yml)"
```
