### ISSUE TITLE
Hibernate ORM properties are not configurable after the application has been compiled

### ISSUE THREAD

**Issue by ccarv** [quarkusio/quarkus#19592]
### Describe the bug

Quarkus will not allow reconfiguring the PU's default schema under the `hibernate-orm` once the applictaion has been compiled. Configuration that is defined in `./config/application.yaml` is ignored (only for `hibernate-orm`) entirely. Environment variables will not be evaluated and or expanded for those properties.

Under `./src/main/resources/application.yaml`:
```yaml
quarkus:
  ...

  hibernate-orm:
    firstPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.firstPU
      database:
        default-schema: ${DB_SCHEMA_FIRSTPU:somedefaultvalue}

    secondPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.secondPU
      database:
        default-schema: ${DB_SCHEMA_SECONDPU:somedefaultvalue}

  datasource:
    myDataSource:
      db-kind: oracle
      username: ${DB_USER}
      password: ${DB_PASS}
      jdbc:
        url: jdbc:oracle:thin:@${DB_URL}
        driver: oracle.jdbc.driver.OracleDriver
```

Under `./config/application.yaml`:
```yaml
quarkus:
  ...

  hibernate-orm:
    firstPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.firstPU
      database:
        default-schema: ${DB_SCHEMA_FIRSTPU}

    secondPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.secondPU
      database:
        default-schema: ${DB_SCHEMA_SECONDPU}

  datasource:
    myDataSource:
      db-kind: oracle
      username: ${DB_USER}
      password: ${DB_PASS}
      jdbc:
        url: jdbc:oracle:thin:@${DB_URL}
        driver: oracle.jdbc.driver.OracleDriver
```

### Expected behavior

`default-schema` should be configurable after the application has been compiled.

### Actual behavior

Whatever value is currently set for `default-schema` during the build phase cannot be overridden afterwards.

### How to Reproduce?

1. In your `./src/main/resources/application.yaml`, configure the `hibernate-orm`:
```yaml
  hibernate-orm:
    firstPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.firstPU
      database:
        default-schema: DefaultInvalidSchemaName
```
2. Once your application is compiled, create an externalized configuration (`./config/application.yaml`)
```yaml
  hibernate-orm:
    firstPU:
      dialect: org.hibernate.dialect.Oracle12Dialect
      datasource: myDataSource
      packages: com.myproject.utils.entity.firstPU
      database:
        default-schema: TheCorrectSchemaName
```
3. Run the applictaion
4. Quarkus will have hardcoded `DefaultInvalidSchemaName` and cannot be overridden

### Output of `uname -a` or `ver`

All environments

### Output of `java -version`

java version "1.8.301"

### Quarkus version or git rev

1.13.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

### Additional information

I've tried using environment variables but this has no effect.
