### ISSUE TITLE
Qute - Bean instance for localized interface not found

### ISSUE THREAD

**Issue by SLedunois** [quarkusio/quarkus#19617]
### Describe the bug

Using github action or maven docker, the `@MessageBundle` is not packaged and throw an exception : 
```
2021-08-24 15:04:55,075 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalStateException: Bean instance for localized interface not found: interface fr.uptimr.i18n.AppMessages
```

### Expected behavior

`@MessageBundle` should always packaged.

### Actual behavior

`@MessageBundle` is not bundled except with using the `quarkus cli tool` and `mvnw`.

### How to Reproduce?

Using the default github action: https://github.com/SLedunois/uptimr/runs/3401245346#step:5:2370

You can clone the code - branch env - and launch with :
```
docker-compose up -d postgres
docker-compose up server
```

The message bundle is here: https://github.com/SLedunois/uptimr/blob/env/src/main/java/fr/uptimr/i18n/AppMessages.java and uses properties messages : https://github.com/SLedunois/uptimr/tree/env/src/main/resources/messages

### Output of `uname -a` or `ver`

docker

### Output of `java -version`

openjdk 11

### Quarkus version or git rev

2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

docker-compose up server

**Comment by SLedunois** [comment]
Hi @mkouba 

Yes indeed. It occurs when I launch quarkus using maven:3.8-jdk11 image with the following configuration:
```yaml
  server:
    container_name: uptimr-server
    image: maven:3.8-jdk-11
    working_dir: /usr/src/app
    volumes:
      - "./:/usr/src/app"
    command: mvn compile quarkus:dev
    ports:
      - "8080:8080"
    links:
      - postgres
```

And launching with `docker-compose up server`.
