### ISSUE TITLE
SmallRye Reactive Messaging Getting Started Example does not work correctly

### ISSUE THREAD

**Issue by TobiWeier** [quarkusio/quarkus#19797]
### Describe the bug

The example in the guide https://quarkus.io/guides/kafka-reactive-getting-started does not work correctly.
After first start of producer process all quotes may received by Multi<Quote> in QuotesResource, but if browser page was reloaded, some events will not be received.

### Expected behavior

```
Quote # 44049ec5-a628-4c42-9155-0c1a08f3a1a5 | $ 12
Quote # da4d18a1-3109-4346-b0b0-53b661d1195c | $ 81
Quote # 6f9edd04-251c-4870-ba49-1bc4c8642bf9 | $ 41
Quote # e44810a3-7fb4-447b-9502-c9dd4c063f6f | $ 17
Quote # 8a84ae32-6923-49c2-a4ac-1d55788a2e33 | $ 7
Quote # 1ed7d116-29c4-40db-a997-aefd68637da0 | $ 47
Quote # d115f3b3-096d-4971-b178-269d278d9d2d | $ 47
Quote # 81fcee6d-6c3d-44a3-b0d9-ef0cfb9a5d7c | $ 3
```

### Actual behavior

After Browser Page Reload (F5):
```
Quote # d3ecef99-0859-450b-98a1-42cb8c5e06ef | Pending
Quote # 77eafb91-e454-4067-8d94-b37d59a29699 | $ 81
Quote # 057e8612-21ba-470a-8c36-9504c5f46a83 | Pending
Quote # 658e3238-46fa-4e45-95f3-a100c1dbd64d | Pending
Quote # a1b8580e-18a9-4c68-96e2-93cdcd4da76d | $ 44
Quote # 801ecb14-42bf-45cf-82d4-4e390b6698b2 | Pending
Quote # a59c5234-4c4e-48e1-885d-b160dea63331 | Pending
Quote # d8c9d974-a48b-420c-9838-a5cd33121d16 | $ 40
Quote # 985b7824-0ce8-4703-8b3b-0a041dd6612a | Pending
Quote # 3056827e-0ecb-4b63-b3ee-1d38fb3d38fc | Pending
Quote # 7cdd0d0a-6899-4de1-a14e-be0efbe666d7 | $ 42
Quote # dec4ef0b-b771-444d-bc61-771208c0a6ec | Pending
```

### How to Reproduce?

Reproducer:

Steps to reproduce the behavior
1. Create the projects as described in [guide](https://quarkus.io/guides/kafka-reactive-getting-started)
2. Add following line in application.properties of both projects
`kafka.bootstrap.servers=localhost:9092`
3. Start kafka/zookeeper with following docker-compose.yaml
```
version: '2'
services:
  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
```
4. start producer project with `mvn clean quarkus:dev`
5. start processor project with `mvn clean quarkus:dev`
6. Open browser with url `http://localhost:8080/quotes.html` and click button "Request Quote" multiple times
7. Reload page with F5 and click button "Request Quote" multiple times

### Output of `uname -a` or `ver`

`Linux iotosnb-8y1r 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

### Output of `java -version`

```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```

### Quarkus version or git rev

`2.1.4.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven/current
Java version: 14.0.2, vendor: Private Build, runtime: /usr/lib/jvm/java-14-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-81-generic", arch: "amd64", family: "unix"
```
