### ISSUE TITLE
Extension for Apache Flink

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#20013]
### Description

Would be great to run `Apache Flink` jobs with `Quarkus` against a given cluster (job/task manager).

### Configuration suggestion

```yaml
flink:
  job-manager:
    port: 6123
    url: "http://job-manager.url"
  task-manager:
    port: 6123
    url: "http://task-manager.url"
```
