### ISSUE TITLE
Dev Services to bootstrap "random" services

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#20037]
### Description

Say I have a system that looks like this:

![superhero](https://user-images.githubusercontent.com/363447/132736111-4da4aa66-8c1a-44d7-b3d8-8a6826eae844.png)

Maybe the **Hero** & **Villain** services have a source repo somewhere or a container image published somewhere and I now want to work on the **Fight** service. It would be _really_ slick if somehow I could configure Quarkus Dev Services to run those dependent services as part of running my service.

### Implementation ideas

Not really implementation ideas, but things to think about.

- Both the **Hero** & **Villain** services also have their own dependencies (each their own PostgreSQL DB), so those would have to be started too
- Both the **Hero** & **Villain** services may want to run on the same http port (`8080`), so they'd have to be mapped & configured somehow. Each service URL would have to have a matching property or something that the developer working on the **Fight** service would use for its URL (i.e. as described in the [rest client guide](https://quarkus.io/guides/rest-client))
    - Maybe some kind of configuration like this (I'm just spitballing here - I'm not sure how to express the dependency between the **Hero** service and its DB, since an env var would need to be set on that service to bind it to its db)
       ```yaml
       quarkus:
         devservices:
           dependencies:
             - image-name: quay.io/<repo>/hero-image:latest
               port-bindings:
                 - 8081:8080 # Binds port 8080 in the container to port 8081 on the host
               properties:
                 org.acme.rest.client.HeroService/mp-rest/url=http://localhost:8081/path
             - image-name: quay.io/<repo>/villain-image:latest
               port-bindings:
                 - 8082: 8080  # Binds port 8080 in the container to port 8082 on the host
               properties:
                 org.acme.rest.client.VillainService/mp-rest/url=http://localhost:8082/path
       ```
