### ISSUE TITLE
The query is very slow when some nodes of the redis cluster are unavailable

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#20159]
### Describe the bug

application.yml
The first three addresses in the configuration "quarkus.redis.hosts" are unavailable and do not belong to the cluster node (redis cluster shrinkage)
```yml
quarkus:
  redis:
    health:
      enabled: true
    hosts: redis://127.0.0.1:5138,redis://127.0.0.1:5139,redis://127.0.0.1:5140,redis://127.0.0.1:5141,redis://127.0.0.1:7017,redis://127.0.0.1:7018,redis://127.0.0.1:7019,redis://127.0.0.1:7020,redis://127.0.0.1:7021
    password: xxxxxxxxx
    timeout: 10s
    client-type: cluster
    replicas: share
    max-pool-size: 20
    max-pool-waiting: 24
    pool-cleaner-interval: 5s
    pool-recycle-timeout: 15s
    max-waiting-handlers: 2048
    max-nested-arrays: 16
    reconnect-interval: 30s
```

code
```java
@Tag(name = "redis sample")
@Slf4j
@Path("/redis")
public class RedisResource {

    @Inject
    RedisService redisService;

    @Operation(summary = "get redis key value")
    @GET @Path("/{key}") @Produces(MediaType.APPLICATION_JSON)
    @Blocking
    public Response<String> get(@PathParam("key") String key) {
        return Response.ok(redisService.get(key));
    }
}
```
```java
@Singleton
public class RedisService {
    @Inject
    RedisClient redisClient;

    @Inject
    ReactiveRedisClient reactiveRedisClient;

    public String get(String key) {
        Response response = redisClient.get(key);
        return response == null ? null : response.toString();
    }
}
```

When I request http://localhost:8080/redis/key1, I need to wait 5-10 seconds before there is a return value. If I remove the first three unavailable addresses configured by "quarkus.redis.hosts", I will get it soon To return value

### Expected behavior

Regardless of whether there are unavailable nodes, as long as the node where the key is located is available, the value should be returned immediately, which is very useful in the scenario of redis cluster shrinking (no need to restart the service)

### Actual behavior

When the unavailable node is configured in front of "quarkus.redis.hosts", the request response is slow. If configured in the back, it will not affect

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.168]

### Output of `java -version`

java version "11.0.10" 2021-01-19

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1
