### ISSUE TITLE
Property Merging in Profile specific configuration ymls does not always work

### ISSUE THREAD

**Issue by ferencbeutel4711** [quarkusio/quarkus#20445]
### Describe the bug

Hello there,

we have custom properties in our application.yml file which are environment specific. Therefore we were excited to split that huge configuration into smaller files as supported by quarkus.
However, while doing that, we found out that properties defined in the profile specific files are not used if they are not defined in the non-profile specific configuration. From our understanding of map merging, this may be a bug.
If we are only using a single configuration file, everything is working as expected.

### Expected behavior

_application.yml_
```yml
example:
  property:
    a: foobar
```

_application-dev.yml_
```yml
example:
  property:
    a: different-value
    b: profile-specific value
```

resulting config:

```json
{
  "example": {
    "property": {
      "a": "different-value",
      "b": "profile-specific value"
    }
  }
}
```

### Actual behavior

_application.yml_
```yml
example:
  property:
    a: foobar
```

_application-dev.yml_
```yml
example:
  property:
    a: different-value
    b: profile-specific value
```

resulting config:

```json
{
  "example": {
    "property": {
      "a": "different-value"
    }
  }
}
```

### Output of `uname -a` or `ver`

Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "11.0.9.1" 2020-11-04 LTS OpenJDK Runtime Environment Zulu11.43+1021-CA (build 11.0.9.1+1-LTS) OpenJDK 64-Bit Server VM Zulu11.43+1021-CA (build 11.0.9.1+1-LTS, mixed mode)

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 6.7.1
