### ISSUE TITLE
Support folded style yaml configuration

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#20508]
### Description

Given an `application.yaml` and the following code:

```
    @ConfigProperty(name = "a.b.c.d")
    String prop;
```

I would like to be able to write:
```
a.b:
  c.d: Hello RESTEasy
```

or:
```
a.b.c.d: Hello RESTEasy
```

and not just the full hierarchy:
```
a:
  b:
    c:
      d: Hello RESTEasy
```

it makes it a lot easier to read and maintain.

another example:

```
quarkus:
  security.users.embedded:
    enabled: true
    plain-text: true
    users:
      scott: jb0ss
      stuart: test
      jdoe: p4ssw0rd
      noadmin: n0Adm1n
    roles:
      scott: Admin,admin,Tester,user
      stuart: admin,user
      jdoe: NoRolesUser
      noadmin: user
```

instead of:

```
quarkus:
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          scott: jb0ss
          stuart: test
          jdoe: p4ssw0rd
          noadmin: n0Adm1n
        roles:
          scott: Admin,admin,Tester,user
          stuart: admin,user
          jdoe: NoRolesUser
          noadmin: user
```

/cc @radcortez
