### ISSUE TITLE
Redis cluster client give error if any pod down

### ISSUE THREAD

**Issue by itboy87** [quarkusio/quarkus#20963]
### Describe the bug

I have deployed redis-cluster from here:
`https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster`

Using following command:
`helm install redis-cluster bitnami/redis-cluster --create-namespace -n redis -f redis-values.yaml`

and `redis-values-yaml` is:
```
cluster:
  init: true
  nodes: 6
  replicas: 1

password: "redis@pass"

redis:
  configmap: |-
    maxmemory 600mb
    maxmemory-policy allkeys-lru
    maxclients 40000

sysctlImage:
  enabled: true
  mountHostSys: true
  command:
    - /bin/sh
    - -c
    - |-
      install_packages procps
      sysctl -w net.core.somaxconn=10000
      echo never > /host-sys/kernel/mm/transparent_hugepage/enabled
```

Cluster working fine and I'm connecting it with following yaml env:
```
            - name: QUARKUS_REDIS_HOSTS
              value: redis://redis-cluster-0.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-1.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-2.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-3.redis-cluster-headless.redis.svc.cluster.local:6379,redis://redis-cluster-4.redis-cluster-headless.redis.svc.cluster.local:6379
            - name: QUARKUS_REDIS_PASSWORD
              value: redis@pass
            - name: QUARKUS_REDIS_CLIENT_TYPE
              value: cluster

```
Where redis-cluster-0, redis-cluster-1 and redis-cluster-2 is master and other are slave.

It is working fine but if any pod of redis-cluster down then i start getting following error:

`java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Failed to connect to all nodes of the cluster`

### Expected behavior

It should work fine without any error if any single master up. But if any master or slave down then it is not working..

### Output of `uname -a` or `ver`

Linux app-5b8c6b9577-4nptz 4.19.0-17-cloud-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64 Linux

### Output of `java -version`

Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseContainerSupport -XX:MaxRAMPercentage=76 -Duser.timezone=UTC openjdk version "11.0.5" 2019-10-15 OpenJDK Runtime Environment (build 11.0.5+10-alpine-r0) OpenJDK 64-Bit Server VM (build 11.0.5+10-alpine-r0, mixed mode)

### Quarkus version or git rev

2.3.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.1 ------------------------------------------------------------ Build time: 2021-06-14 14:47:26 UTC Revision: 989ccc9952b140ee6ab88870e8a12f1b2998369e Kotlin: 1.4.31 Groovy: 3.0.7 Ant: Apache Ant(TM) version 1.10.9 compiled on September 27 2020 JVM: 11.0.12 (GraalVM Community 11.0.12+6-jvmci-21.2-b08) OS: Mac OS X 11.5 x86_64
