### ISSUE TITLE
Yaml config broken

### ISSUE THREAD

**Issue by samekim** [quarkusio/quarkus#20961]
### Describe the bug

config kafka messaging using yaml like below.
`mp.messaging.incoming.my-channel.auto.offset.reset=earliest`

result: 
The configuration '"auto.offset.reset"' was supplied but isn't a known config.

but it works well using properties.

**Comment by radcortez** [comment]
Hi @samekim 

How are you setting this property? This works for me:

```yaml
mp:
  messaging:
    incoming:
      "my-channel":
        auto:
          offset:
            reset: earliest
```

**Comment by samekim** [comment]
@radcortez does it works in native?

**Comment by radcortez** [comment]
Didn't try native, but it should work the same way.

Are you seeing an issue where it works in JVM mode but not in native?

**Comment by samekim** [comment]
I've tested it as you said.

* it works in jvm and native.
```
mp:
  messaging:
    incoming:
      my-channel:
        auto:
          offset:
            reset: earliest
```

* it works only in jvm.
```
mp:
  messaging:
    incoming:
      my-channel:
        auto.offset.reset: earliest
```
