### ISSUE TITLE
Problem with quarkus kafka smallrye consumer multithreading

### ISSUE THREAD

**Issue by davideginna** [quarkusio/quarkus#21306]
### Describe the bug

By setting "partitions" parameter to 3.
I have 3 different consumer ids, but the messages are processed sequentially.

- quarkus version 2.X
- smallrye

Properties that i set

``` yml
mp:
  messaging:
    incoming:
      event:
        connector: smallrye-kafka
        auto:
          offset:
            reset: earliest
        topic: MY_TOPIC
        group:
          id: my-group
        partitions: 3
```

### Expected behavior

the messages should be processed concurrently for  each partition

### Actual behavior

the messages are processed sequentialy though we have different partitions

### Output of `java -version`

jdk11

### Quarkus version or git rev

2.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3
