### ISSUE TITLE
Introspection succeed even if client secret is wrong

### ISSUE THREAD

**Issue by allebdev** [quarkusio/quarkus#21582]
I have a service with authorisation configured to accept JWT Bearer Token with enabled introspection (using quarkus-oidc).
But even if client secret is wrong my application respond successfully whilst direct introspection request to auth server (Keycloak) with the same credentials fails with `401 Unauthorized`. Looks like my app doesn't do any introspection request to auth server at all if token is not expired. I guess it's either a bug or misconfiguration, but I tried a lot of combinations of existing flags and behaviour hasn't been changed.

My OIDC configuration:
```yaml
quarkus:
  oidc:
    application-type: service
    auth-server-url: ${AUTH_SERVER_URL:}
    client-id: ${CLIENT_ID:}
    credentials:
      secret: wrongsecret
    token:
      allow-jwt-introspection: true
    tenant-enabled: true
    allow-token-introspection-cache: false
    authentication:
      verify-access-token: true
```
 Please help me figure out how to fix it.
