### ISSUE TITLE
Qute should allow configuring HTML escaping for "custom" content-types/variants

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#21731]
### Description

Currently hard-coded here for xml and html: https://github.com/quarkusio/quarkus/blob/2.5.0.Final/independent-projects/qute/core/src/main/java/io/quarkus/qute/HtmlEscaper.java#L42

When you have e.g. xhml, you'll probably configure something like:
```
quarkus:
  qute:
    suffixes:
      - xhtml
    content-types:
      xhtml: application/xhtml+xml
```
but you'd still want escaping for those xhtml templates, which doesn't work, even not with a selected variant (at least for `@CheckedTemplates`; see #21730).

### Implementation ideas

```
quarkus:
  qute:
    html-escape-content-types:
      - xhtml
```
(or a better name)

Maybe it's better to create a new `content-types` config object that takes:
- file ending
- content-type
- locale (optional)
- encoding (optional)
- escaping yes/no (optional)

Otherwise the config would become really verbose and not so DRY, IMHO.

Also, I think `Variant` should be extended to toggle escaping.

Related:
- #21730
- #21405
- https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Qute.20and.20XML.20templates.20.28char.20escaping.20issues.29
