### ISSUE TITLE
insert in import.sql is not acted upon

### ISSUE THREAD

**Issue by anborg** [quarkusio/quarkus#21745]
### Describe the bug

In import.sql I have this insert statement

import.sql is default file name
```sql
-- couple of table definitions..

insert into MYTABLE(svc_pt_id, addr_id) values(0,1234);
commit;
```

Snippet of my yaml file. I commented out the "schema_ddl.sql" as "import.sql" is default.   I also tried with schema_ddl.sql. The tables are available, but no the inserted rows. 

```yaml
      jdbc:
        url: jdbc:h2:mem:myDB;DB_CLOSE_DELAY=-1;MODE=Oracle;INIT=CREATE SCHEMA IF NOT EXISTS integ
        max-size: 8
    hibernate-orm:
#      sql-load-script: ${app.configBasePath}/../sql/cis/schema_ddl.sql
      #datasource-cis:
      #datasource: "datasource-cis" # defined above
      packages: package model
      database:
        default-schema: integ
        generation: drop-and-create # none, create, drop-and-create, drop, update, validate
```

### Expected behavior

Rows inserted in import.sql  must be available during unit-test & development

### How to Reproduce?

add an insert statement for a mapped object in import.sql

do a  repo.byId(id) and check if that inserted object is available

### Output of `uname -a` or `ver`

MSYS_NT-10.0-17763 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)

### Quarkus version or git rev

2.3.1.Fina

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

### Additional information

Maven home: C:\apps\apache-maven-3.8.3
Java version: 11.0.13, vendor: GraalVM Community, runtime: C:\apps\graalvm-ce-java11-21.3.0
Default locale: en_CA, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
