### ISSUE TITLE
OpenAPI hidden property not hidden

### ISSUE THREAD

**Issue by enbohm** [quarkusio/quarkus#2230]
The following POJO annotated with a property declared as hidden in OpenAPI (``` @Schema(hidden = true) ```) is still visible in the final OpenAPI document

```java
public class MyOpenApiEntity {

  @Schema(hidden = false)
  private String visibleProperty;

  @Schema(hidden = true)
  private String hiddenProperty;

  public String getVisibleProperty() {
    return visibleProperty;
  }
  public String getHiddenProperty() {
    return hiddenProperty;
  }
}
```

In SwaggerUI it looks like this, i.e. the hidden property is visible which is wrong.

![quakus-hiddenproperty](https://user-images.githubusercontent.com/4103786/56785335-02045e80-67f5-11e9-8b5b-b5a119815584.png)

The openAPI yaml file looks like this:

```yaml
components:
  schemas:
    MyOpenApiEntity:
      properties:
        hiddenProperty: {}
        visibleProperty:
          type: string
```

(I guess that the hiddenProperty shouldn't be there at all)

This code was tested on macOS Mojave and OpenJDK Runtime Environment 18.9 (build 11+28) and Quarkus 0.14.0
