### ISSUE TITLE
Build native error with liquibase & multidatabase

### ISSUE THREAD

**Issue by stephanecottin** [quarkusio/quarkus#23224]
### Describe the bug

With Quarkus last version (2.6.3) and liquibase, I have a very strange behaviour.
I have in my config:

```
quarkus:
  liquibase:
    migrate-at-start: true
    change-log: /db/changelog/db.changelog-master.yaml
    database-change-log-lock-table-name: database_changelog_lock
    database-change-log-table-name: database_changelog
```

and 3 database:

 ```
 datasource:
    db-kind: mariadb
    username: root
    password:
    jdbc:
      url: jxxx

    auth:
      db-kind: mariadb
      username: root
      password:
      jdbc:
        url: yyyyy

    app:
      db-kind: mariadb
      username: root
      password:
      jdbc:
        url: xxx

```

When I run on JDK, no problem.
When I want to build on native, I have the error:

`[ERROR] 	[error]: Build step io.quarkus.liquibase.deployment.LiquibaseProcessor#nativeImageConfiguration threw an exception: java.lang.IllegalStateException: liquibase.exception.ChangeLogParseException: The file db/changeLog.xml was not found in`

I add an empty file: changeLog.xml, the native build is OK.
Liquibase is looking for this file for my auth & app database but I don't use liquibase on it.
If I remove these 2 database, it's working fine.

If I add:
```

  liquibase:
    auth:
      migrate-at-start: false

    smartisi:
      migrate-at-start: false

```
It doesn't change any thing

### Expected behavior

Liquibase + quarkus on native build must not be looking for changelog.xml file for the all the data source.

### Output of `uname -a` or `ver`

21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

16.0.2
