### ISSUE TITLE
selected-alternatives YAML List

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#23276]
### Description

When using the `application.yaml`, it would be nicer organizationally to support the `quarkus.arc.selected-alternatives` as a list. When adding many alternatives the line becomes very hard to read when common separated.

Current:
```yaml
quarkus:
  arc:
    selected-alternatives: my.project.subproject.AlternativeA,my.project.subproject.AlternativeB,my.project.subproject.AlternativeC,my.project.subproject.AlternativeD
```

Proposed:
```yaml
quarkus:
  arc:
    selected-alternatives: 
      - my.project.subproject1.AlternativeA
      - my.project.subproject1.AlternativeB
      - my.project.subproject1.AlternativeC
      - my.project.subproject1.AlternativeD
```

`quarkus.arc.excluded-types` is another good contender for this treatment.
