### ISSUE TITLE
reactive-messaging-kafka + config-yaml - warning about unknown '"auto.offset.reset"' config

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#23387]
### Describe the bug

reactive-messaging-kafka + config-yaml - warning about unknown '"auto.offset.reset"' config

```
2022-02-02 21:08:44,247 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18214: Key deserializer omitted, using String as default
2022-02-02 21:08:44,343 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (Quarkus Main Thread) The configuration '"auto.offset.reset"' was supplied but isn't a known config.
2022-02-02 21:08:44,407 INFO  [io.sma.rea.mes.kafka] (Quarkus Main Thread) SRMSG18258: Kafka producer kafka-producer-words-out, connected to Kafka brokers 'OUTSIDE://localhost:55004', is configured to write records to 'words'
2022
...
```

Generated `src/main/resources/application.yml` looks like this:
```yaml
greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        topic: "words"
        auto.offset.reset: "earliest"
```

But should look like this:
```yaml
greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        topic: "words"
        auto:
          offset:
            reset: "earliest"
```

### Expected behavior

No warning

### Actual behavior

Warning about unknown config entry

### How to Reproduce?

 - Download app https://code.quarkus.io/?e=smallrye-reactive-messaging-kafka&e=config-yaml
 - Run `mvn quarkus:dev`
 - check log

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.0.Final

**Comment by cescoffier** [comment]
The beauty of yaml and kafka. `.` is an object separator. 
So you need to wrap the key between quotes:

```
"auto.offset.reset": "earliest"
```

**Comment by rsvoboda** [comment]
@cescoffier is the codestart fixed?

**Comment by cescoffier** [comment]
No, I don't think there is anything. We can do. @ia3andy a y idea?

**Comment by ia3andy** [comment]
The working solution is as @rsvoboda described it to have:
```yaml
greeting:
  message: "hello"
mp:
  messaging:
    outgoing:
      words-out:
        topic: "words"
    incoming:
      words-in:
        topic: "words"
        auto:
          offset:
            reset: "earliest"
```
I am working on the PR to fix the template.
