### ISSUE TITLE
Knative: Property `quarkus.knative.revision-auto-scaling.container-concurrency` is ignored

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#23832]
### Describe the bug

When using the property `quarkus.knative.revision-auto-scaling.container-concurrency` with a value `5` for example and we generate the Knative manifests, the generated Knative service ignores this value and it always uses `0`:

```yaml
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-02-21 - 11:09:14 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: knative-demo
  name: knative-demo
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: knative-demo
      name: my-revision
    spec:
      containerConcurrency: 0
      containers:
        - image: jcarvaja/knative-demo:1.0.0-SNAPSHOT
          name: knative-demo
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
```

I did check that the decorator `ApplyLocalContainerConcurrencyDecorator` is executed with the right value (`5`), but for some reason, this is overwritten later.
