### ISSUE TITLE
application.yaml override doesn't work as expected

### ISSUE THREAD

**Issue by romilpunetha** [quarkusio/quarkus#23855]
### Describe the bug

I have an `application.yaml` and an `application-dev.yaml` as follows:

```
application.yaml:

quarkus:
  profile: ${ENVIRONMENT:dev}

  native:
    container-build: true

  container-image:
    push: true
    build: true
    image: ${IMAGE_URL:default}:${IMAGE_TAG:default}


application-dev.yaml: 

quarkus:
  profile: dev

  container-image:
    push: false
    build: false

  native:
    container-build: false
```

When I try to do a build using `-Dquarkus.profile=dev`, it still tries to build the native container and fails. When I disable the properties in the parent application.yaml, it works. 

When I reverse the config, ie, enable builds in the `application-dev.yaml` and disable it in the parent yaml, it still works because it picks from the parent yaml .

### Expected behavior

On disabling container build in the `application-dev.yaml` profile and passing the profile param as `dev`, container build should not happen locally. 

### Actual behavior

Configs are picked from parent yaml.

### How to Reproduce?

1. Create a dummy application with a parent application.yaml and a profile application.yaml as `application-dev.yaml`.
2. Enable native container build in the parent yaml and disable it in the profile yaml.
3. Run local build

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Homebrew (build 17.0.2+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.2+0, mixed mode, sharing)

### Quarkus version or git rev

2.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 17.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "aarch64", family: "mac"
