### ISSUE TITLE
quarkus-smallrye-openapi generation uses fields and ignores annotated methods

### ISSUE THREAD

**Issue by sandersteenhoudt** [quarkusio/quarkus#24085]
### Describe the bug

I have the response body of my resources defined as interfaces, because I'm using the [Immutables library](https://immutables.github.io) to generate the implementation. I added Jackson's `@JsonProperty` annotations to the methods, but the resulting openAPI shows an empty schema. 

I've been scratching my head for a few hours now and I can't find much about it online, but I'm pretty sure I've done the exact same set-up using Spring and springdoc. Anyway, I'm sorry if I've missed something obvious (some configuration option to explicitly state methods should be used instead of fields?). I've added a reproducer repo with some comments, but it's pretty straightforward. 

### Expected behavior

OpenAPI is generated using the property names defined in the annotations.

In my search for more information on this behaviour, I found this PR in the smallrye openapi repo that makes me assume this should work, but I might be confused: https://github.com/smallrye/smallrye-open-api/pull/150

### Actual behavior

Empty schema when using only methods (as in the case of the interface), or schema using the field names as properties instead of the value in the method's annotation

### How to Reproduce?

Reproducer: https://github.com/sandersteenhoudt/quarkus-openapi-bug-reproducer

1. Run the reproducer application
2. Go to the [swagger UI ](http://localhost:8080/q/swagger-ui/)
3. Look at the schemas

### Output of `uname -a` or `ver`

5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment (build 17.0.3+3) OpenJDK 64-Bit Server VM (build 17.0.3+3, mixed mode)

### Quarkus version or git rev

2.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.3.3

**Comment by MikeEdgar** [comment]
@sandersteenhoudt - can you confirm if it works if you name your interface methods with a `get` prefix?

```yaml
components:
  schemas:
    Cookie:
      type: object
    CookieImpl:
      type: object
      properties:
        implementationName:
          type: string
        implementationGlutenFree:
          type: boolean
        annotationOnField:
          type: array
          items:
            type: string
        anotherFieldProperty:
          type: object
          additionalProperties:
            type: string
    ImmutableImmutablesCookie:
      type: object
      properties:
        name:
          type: string
        glutenFree:
          type: boolean
    ImmutablesCookie:
      type: object

```
