### ISSUE TITLE
Kubernetes: Wrongly parsing JVM arguments when using commas

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#24136]
### Describe the bug

The property `quarkus.kubernetes.jvm-arguments` (or `quarkus.[openshift or s2i ...].jvm-arguments`) is splitting the value by comma. The problem is that some values need to keep the comma characters, for example, using:
```
quarkus.openshift.jvm-arguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
```

Will result in the following container command:

```yaml
...
containers:
- command:
    - java
    - -agentlib:jdwp=transport=dt_socket
    - server=y
    - suspend=n
    - address=*:5005
    - -jar
    - /deployments/quarkus-run.jar
...
```

Which is wrong. The expected output should be:

```yaml
containers:
- command:
    - java
    - -Dquarkus.http.host=0.0.0.0
    - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    - -jar
    - /deployments/quarkus-run.jar
```

Also, note that if we set the property `quarkus.openshift.jvm-arguments`, it will remove both `quarkus.http.host` and `java.util.logging.manager` which as far I see, it's also wrong. 

### Expected behavior

We should allow users to append JVM arguments to achieve the following resource:

```yaml
containers:
- command:
    - java
    - -Dquarkus.http.host=0.0.0.0
    - -Djava.util.logging.manager=org.jboss.logmanager.LogManager
    - -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    - -jar
    - /deployments/quarkus-run.jar
```

This is:
- To not split the property in comma
- To not override the `quarkus.http.host` and `java.util.logging.manager`

A possible solution is to provide a new property to provide additional JVM arguments in a map fashion way:

```
quarkus.kubernetes.jvm-additional-arguments.0=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
quarkus.kubernetes.jvm-additional-arguments.1=-Ddebug=true
```
