### ISSUE TITLE
AWS Lambda throws IllegalStateException: Missing HTTP method in request event

### ISSUE THREAD

**Issue by brielmayer** [quarkusio/quarkus#24284]
### Describe the bug

Every time a HTTP request hits the AWS Lambda, we are receiving the following error: 

```
java.lang.IllegalStateException: Missing HTTP method in request event
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.nettyDispatch(LambdaHttpHandler.java:176)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:63)
at io.quarkus.amazon.lambda.http.LambdaHttpHandler.handleRequest(LambdaHttpHandler.java:43)
at io.quarkus.amazon.lambda.runtime.AmazonLambdaRecorder$1.processRequest(AmazonLambdaRecorder.java:164)
at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:126)
at java.lang.Thread.run(Thread.java:829)
at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:600)
at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
```

We use the latest Quarkus version.

### Expected behavior

Lambda is starting and handeling the request

### Actual behavior

java.lang.IllegalStateException: Missing HTTP method in request event whenever a request hits the Lambda

### Output of `java -version`

11

### GraalVM version (if different from Java)

graalvm-ce-java11-linux-amd64-21.3.1

### Quarkus version or git rev

2.7.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by patriot1burke** [comment]
Which quarkus extension?  "quarkus-amazon-lambda-http" or "quarkus-amazon-lambda-rest"?  This smells like you are mixing the wrong quarkus extension with the amazon api gateway product you are using "REST" vs "HTTP API".

**Comment by brielmayer** [comment]
Thank you @patriot1burke, using "quarkus-amazon-lambda-rest" instead of "quarkus-amazon-lambda-http" resolved this issue!

**Comment by JOSUERV99** [comment]
Hi, I am in the same situation, but I need to use the HTTP version, what can I do to solve the error?

**Comment by JOSUERV99** [comment]
I was trying with both my own .yaml and the generated getting the same result

My own yaml:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  StageName:
    Type: String
    Default: Test

Resources:
  HttpApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java11
      CodeUri: target/function.zip
      MemorySize: 1024
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      VpcConfig:
        SubnetIds:
          - subnet-XXXXXXXXXXXXXXX
          - subnet-XXXXXXXXXXXXXXX
        SecurityGroupIds:
          - sg-XXXXXXXXXXXXXXXX
      Events:
        ExplicitApi: # warning: creates a public endpoint
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /json-transposition-tool
            Method: POST
            PayloadFormatVersion: "2.0"
            RouteSettings:
              ThrottlingBurstLimit: 600

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Tags:
        Tag: Value
      DefaultRouteSettings:
        ThrottlingBurstLimit: 200
      RouteSettings:
        "POST /json-transposition-tool":
          ThrottlingBurstLimit: 500 # overridden in HttpApi Event
      StageVariables:
        StageVar: Value
      FailOnWarnings: true

  AccessLogs:
    Type: AWS::Logs::LogGroup

Outputs:
  HttpApiUrl:
    Description: URL of your API endpoint
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi
```

Generated:
 ```
 AWSTemplateFormatVersion: '2010-09-09'
  Transform: AWS::Serverless-2016-10-31
  Description: AWS Serverless Quarkus HTTP - quarkus-amazon-lambda-http-deployment
  Globals:
    Api:
      EndpointConfiguration: REGIONAL
      BinaryMediaTypes:
        - "*/*"

  Resources:
    JsonTranspositionToolQuarkusHttpAwsLambda:
      Type: AWS::Serverless::Function
      Properties:
        Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
        Runtime: java11
        CodeUri: function.zip
        MemorySize: 512
        Policies: AWSLambdaBasicExecutionRole
        Timeout: 15
        Events:
          HttpApiEvent:
            Type: HttpApi
            Method: POST
            Path: /json-transposition-tool

  Outputs:
    JsonTranspositionToolQuarkusHttpAwsLambdaApi:
      Description: URL for application
      Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
      Export:
        Name: JsonTranspositionToolQuarkusHttpAwsLambdaApi
```
