### ISSUE TITLE
`stork-service-discovery-kubernetes` extension requires some extra configutation that is not documented

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#24444]
### Describe the bug

`stork-service-discovery-kubernetes` requires `org.bouncycastle:bctls-jdk15on` dependency and also some extra configuration on your application.properties:

Example 

```
# application properties should be here
quarkus.security.security-providers=BCJSSE

quarkus.http.ssl.certificate.key-store-file=server-keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
quarkus.http.ssl.certificate.trust-store-file=server-truststore.jks
quarkus.http.ssl.certificate.trust-store-password=password

quarkus.native.additional-build-args=--allow-incomplete-classpath
```

Also, end-user must be sure that has the following K8s/ocp cluster roles binding (JVM and native mode):

Cluster Role

```
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: "${NAMESPACE}"
  name: endpoints-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
```

ClusterRoleBinding

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fabric8-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    namespace: "${NAMESPACE}"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
```

I think that these requirements should be documented:
DocRef: https://quarkus.io/blog/stork-kubernetes-discovery/

Also would be great to understand why `org.bouncycastle:bctls-jdk15on` is needed and check if we could do something in order to avoid this extra dependency

Reproducer: https://github.com/quarkus-qe/quarkus-test-suite/pull/572
