### ISSUE TITLE
kubernetes: allow to customize the container name

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#24676]
### Description

As today the name of the `container` that the Kubernetes generates matches the name of the `artifactId` or the value of `quarkus.kubernetes.name` if that's set however the same value is used to set i.e. the name of the generated deployment resources.

In essence it behave as:

```yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: ${quarkus.kubernetes.name}
spec:
  template:
    spec:
      containers:
      - image: "foo/bar:latest"
        name: ${quarkus.kubernetes.name}
```

But in some cases, it is needed to set a specific name to a container and as today that's only possible by post by post processing the generated kubernetes resource yaml.

### Implementation ideas

A new property, like `quarkus.kubernetes.container-name` can be introduced to allow users to set the name of the container.
For backward compatibility, the default of the new property could be  `${quarkus.kubernetes.name}` 

```yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: ${quarkus.kubernetes.name}
spec:
  template:
    spec:
      containers:
      - image: "foo/bar:latest"
        name: ${quarkus.kubernetes.container-name}
```
