### ISSUE TITLE
smallrye-reactive-messaging-Feature Request: Customizing the underlying MQTT client 

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24718]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/693)
Hi,

a similar feature for the mqtt like: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2.2/amqp/amqp.html#amqp-customization would be very helpful.

At the moment I need to convert a ca.crt to a java key store to use it for the mqtt connection.
But it would be nice to have the option to use it without converting it.

T

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-reactive-messaging
upstream-issue: 693
upstream-status: open
upstream-milestone: unplanned
```
