### ISSUE TITLE
smallrye-reactive-messaging-Allow metadata injection for method receiving payload

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24717]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/593)
For method receiving payload (list below), we should support the injection of message metadata:

```java
@Incoming("x")
public void consume(T payload, KafkaIncomingMetadata meta1) {
  // ...
}
```

Note that a message can be multiple metadata objects, so multiple parameters can be injected:

```java
@Incoming("x")
public void consume(T payload, KafkaIncomingMetadata meta1, TracingMetadata tracing) {
  // ...
}
```

Also, because metadata can be missing, we should add support for `Optional`:

```java
@Incoming("x")
public void consume(T payload, Optional<KafkaIncomingMetadata> meta1) {
  // ...
}
```

This would also mean that if `Optional` is not used, failure should be propagated in the case of missing metadata.

Signatures that should support this metadata injection are:

```
@Incoming("x") void method(P payload);
@Incoming("x") CompletionStage<Void> method(P payload);
@Incoming("x") Uni<Void> method(P payload);

@Outgoing("x") @Incoming("y") Publisher<O> method(P payload);
@Outgoing("x") @Incoming("y") Multi<O> method(P payload);
@Outgoing("x") @Incoming("y") PublisherBuilder<O> method(P payload);

@Outgoing("x") @Incoming("y") O method(P payload);
@Outgoing("x") @Incoming("y") CompletionStage<O> method(P payload);
@Outgoing("x") @Incoming("y") Uni<O> method(P payload);
```

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-reactive-messaging
upstream-issue: 593
upstream-status: open
upstream-milestone: unplanned
```
