### ISSUE TITLE
smallrye-reactive-messaging-MQTT - Add metadata support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24719]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/466)
The MQTT connector should provide inbound and outbound metadata classes instead of a `MqttMessage`

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-reactive-messaging
upstream-issue: 466
upstream-status: open
upstream-milestone: unplanned
```
