### ISSUE TITLE
smallrye-mutiny-Move the website to MkDocs and adopt the Diátaxis Framework

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24722]
(From https://github.com/smallrye/smallrye-mutiny/issues/868)
See:

- https://squidfunk.github.io/mkdocs-material/
- https://diataxis.fr/

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-mutiny
upstream-issue: 868
upstream-status: open
upstream-milestone: 2.0.0 - https://github.com/smallrye/smallrye-mutiny/milestone/50
```
