### ISSUE TITLE
smallrye-mutiny - Replay last N items

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24724]
(From https://github.com/smallrye/smallrye-mutiny/issues/536)
Rx has a concept of `BehaviorSubject` and `ReplayingSubject`, which are quite similar and serve a very useful purpose: pre-seed a subscriber with last known value[s] / initial value[s] at the moment of subscription. I think we could unify them under an API like this:

```java
Multi.createBy()
    .replayingAtMost(int)  // buffer size -- to imitate `BehaviorSubject`, use 1
    .withInitialValues(T... or Iterable<T> or perhaps even Multi<T>) // initial values to emit when nothing was emitted yet
    .stream(Multi<T>); // the stream we're wrapping
```

Calling it `replayingAtMost` to highlight that if you set 5 items to replay but only 3 items have been emitted, then only 3 will be replayed to a new subscriber. If you think that's intuitive enough, can shorten to just `replaying`.

WDYT?

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-mutiny
upstream-issue: 536
upstream-status: released
upstream-milestone: 1.4.0 - https://github.com/smallrye/smallrye-mutiny/milestone/47
```
