### ISSUE TITLE
smallrye-reactive-messaging-Introduce failure management bean

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24720]
(From https://github.com/smallrye/smallrye-reactive-messaging/issues/438)
The idea is to catch the processing failure of the following method shapes:

*  `X process(Y)` and  `Message<X> process(Message<Y>)`
* `CompletionStage<X> process(Y)` and `CompletionStage<Messasge<X>> process(Message<Y>)`

When a failure happens (synchronously or asynchronously), a `FailureHandler` bean is called with the failing message:

```
public interface FailureHandler {
       // return true or failse whether the stream consumption must continue
       boolean handleFailure(Message<X>, Throwable failure);
}
```

Only a 0..1 instance of this handler is allowed. If none, the failure is not handled and the processing stopped.

The FailureHandler implementation is provided by the user.

_Implementation details_:

The mediator method invocation must be wrapped into a "flatMap" to avoid canceling the upstream subscription. 

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-reactive-messaging
upstream-issue: 438
upstream-status: open
upstream-milestone: unplanned
```
