### ISSUE TITLE
smallrye-mutiny-Use Java 11 as a baseline

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24723]
(From https://github.com/smallrye/smallrye-mutiny/issues/839)
- The Mutiny 1.x series will continue to require Java 8.
- Requiring Java 11 is considered as a major breaking change, so when we do that we will bump to the 2.x series.
- Once 2.0.0 is out we will consider supporting the final `1.x` release with important bug fixes.

```yaml
upstream-organization: GHUser@4b397d91[bio=<null>,blog=https://smallrye.io,company=<null>,email=<null>,followers=0,following=0,hireable=false,location=<null>,login=smallrye,name=SmallRye,type=Organization,createdAt=2018-05-01T19:22:51Z,id=38892730,nodeId=MDEyOk9yZ2FuaXphdGlvbjM4ODkyNzMw,updatedAt=2022-03-01T16:01:13Z,url=https://api.github.com/users/smallrye]
upstream-repository: smallrye-mutiny
upstream-issue: 839
upstream-status: open
upstream-milestone: 2.0.0 - https://github.com/smallrye/smallrye-mutiny/milestone/50
```
