### ISSUE TITLE
Custom Kubernetes file is not merged

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#24733]
### Describe the bug

I created a simple Quarkus application with the Kubernetes extension. The app is named todo-app.

Then I created in `src/main/kubernetes` a file named `kubernetes.yaml` with the following content:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quickstart
  template:
    metadata:
      labels:
        app: quickstart
```

### Expected behavior

Values merged

### Actual behavior

The resulting Kubernetes file at `target`  doesn't contain the replicas to 3 nor the labels.

I might be doing something wrong, but some log information on why was not merged would be perfect to know exactly what's going on.

### How to Reproduce?

https://github.com/redhat-scholars/kube-native-java-apps/tree/master/apps/todo-app
