### ISSUE TITLE
Can't configure Cors using YAML

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#24740]
### Describe the bug

When using Yaml to configure Quarkus, it is impossible to properly configure cors.

This is due to the fact that you can either have:

```
quarkus:
  http:
    cors: true
```
or
```
quarkus:
  http:
    cors:
      origins: "*"
```
but not
```
quarkus:
  http:
    cors: true
      origins: "*"
```

The last example breaks the parser; as the `quarkus.http.cors` value cannot be both an object and a value in the YAML spec.

I might reccommed we move the flag to enable cors to `quarkus.http.cors.enable`, allowing the yaml to parse correctly.

### Quarkus version or git rev

2.7.5.Final

**Comment by GregJohnStewart** [comment]
For those in a similar boat, you can use the following syntax to get around this issue:

```
quarkus:
  http:
    cors:
      ~: true
      origins: "*"
```

I still think the config parameter should be changed though
