### ISSUE TITLE
smallrye-stork - Add global discovery and load balancer types

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24758]
(From https://github.com/smallrye/smallrye-stork/issues/248)
Support global defaults for discovery and load balancer types used across the application:

```
stork.service-discovery=consul
stork.service-discovery.refresh-period=7M # default value for consul's discovery param refresh period
stork.load-balancer=least-response-time

# hello will use consul and least-response-time by default
hello/mp-rest/url=stork://my-service/hello

# if needed, params can still be used at the service level
stork.my-service.service-discovery.refresh-period=10M # override global default
stork.my-service.service-discovery.application=myapp

# or use an entirely new discovery/load balancer for a specific service
stork.my-service2.service-discovery=kubernetes
```

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 248
upstream-status: open
upstream-milestone: 1.2.0 - https://github.com/smallrye/smallrye-stork/milestone/3
```
