### ISSUE TITLE
smallrye-stork - Improve service instance cache

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24757]
(From https://github.com/smallrye/smallrye-stork/issues/284)
null

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 284
upstream-status: open
upstream-milestone: unplanned
```
