### ISSUE TITLE
smallrye-stork - Add a Service registration SPI

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24759]
(From https://github.com/smallrye/smallrye-stork/issues/110)
Often, services that would use Service Discovery, would also like to register themselves to the Service Registry that is backing up the discovery.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 110
upstream-status: open
upstream-milestone: unplanned
```
