### ISSUE TITLE
smallrye-stork - Failover support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24760]
(From https://github.com/smallrye/smallrye-stork/issues/232)
We had a few asks for failover support in Stork. 
Currently, we stand at the position that Stork should only provide service instances and not be involved in making calls, but maybe we should revisit it?

Currently, the way to solve it is to use a failure aware load balancer, such as `least-response-time` and combine it e.g. with MicroProfile Fault Tolerance `@Retry` annotation.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 232
upstream-status: open
upstream-milestone: unplanned
```
