### ISSUE TITLE
smallrye-stork - Improve release notes generation

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24762]
(From https://github.com/smallrye/smallrye-stork/issues/285)
Extend the release process to generate release notes:

- distinguish core/load-balancer/service-discovery (and maybe prefix with the type for SD and LB)
- list the breaking changes if any
- mention dependency update is a separated list

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 285
upstream-status: open
upstream-milestone: unplanned
```
