### ISSUE TITLE
smallrye-stork - Provide an example of load balancer using "machine learning" to select the best service instance

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24761]
(From https://github.com/smallrye/smallrye-stork/issues/283)
This epic is about writing a how-to explaining how one can implement an advanced load balancer integrating machine learning to choose the best service instance.

```yaml
upstream-organization: SmallRye
upstream-repository: smallrye-stork
upstream-issue: 283
upstream-status: open
upstream-milestone: unplanned
```
