### ISSUE TITLE
Sub-optimal YAML support for Kafka config

### ISSUE THREAD

**Issue by cdmikechen** [quarkusio/quarkus#24832]
### Describe the bug

I use application.yaml to config quarkus, and I use kafka extension.
My application.yaml like this:
```yaml
mp:
  messaging:
    incoming:
      test:
        topic: xxxx
        "auto.offset.reset": earliest
        "schema.registry.url": http://xxxx
        "key.deserializer": io.confluent.kafka.serializers.KafkaAvroDeserializer
        "value.deserializer": io.confluent.kafka.serializers.KafkaAvroDeserializer
```

At present, it seems that quarkus cannot directly recognize kafka's config like `log.category`.

### Expected behavior

I hope the configuration of Kafka can be similar to `log.category`.
```yaml
quarkus:
  log:
    min-level: DEBUG
    category:
      "org.apache":
        level: DEBUG
```
Instead of having to write like this, the readability of this writing method is certainly not very good, especially when there are many configured variables.
```yaml
mp:
  messaging:
    incoming:
      mqtt:
        topic: xxxx
        auto:
          offset:
            reset: earliest
        schema:
          registry:
            url: http://xxxx
        key:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
```

### Actual behavior

When the quarkus service starts, kafka will have the following warning:
```
[org.apa.kaf.cli.con.ConsumerConfig] (Quarkus Main Thread) The configuration '"schema.registry.url"' was supplied but isn't a known config.
```

### How to Reproduce?

No

### Output of `uname -a` or `ver`

dev

### Output of `java -version`

11.0.14

### GraalVM version (if different from Java)

GraalVM CE 22.0.0.2

### Quarkus version or git rev

2.7.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3

### Additional information

No

**Comment by alesj** [comment]
So the problem is yaml format or that warning?

**Comment by cdmikechen** [comment]
@alesj 
Both of these. Quarkus get config is `"schema.registry.url"`, `"auto.offset.reset"`, `"key.deserializer"`, `"value.deserializer"`, so that kafka cannot recognize these variables.

**Comment by alesj** [comment]
But the other, more yaml-ish format works for you?

**Comment by cescoffier** [comment]
I think that log category is a specific case in Quarkus. 
I had a long discussion about that with @ia3andy

**Comment by cdmikechen** [comment]
> But the other, more yaml-ish format works for you?

@alesj 
Quarkus can read config like this:
```yaml
mp:
  messaging:
    incoming:
      mqtt:
        topic: xxxx
        auto:
          offset:
            reset: earliest
        schema:
          registry:
            url: http://xxxx
        key:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
        value:
          deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
```
But I think the readability of this writing method is certainly not very good, especially when there are many configured variables.
