### ISSUE TITLE
Kubernetes: Allow to mount volumes for secrets/configmaps items

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#25058]
### Description

Currently, the Quarkus Kubernetes extension allows mounting volumes for secrets as directories. However, it would also be good to allow the mounting of single files from the secrets. Example:

If we want to mount the following:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - volumeMounts:
            - mountPath: /etc/certs
              name: volume-certs
      volumes:
        - name: volume-certs
          secret:
            secretName: rootsecretname
            items:
              - key: keystore.p12
                path: keystore.p12
```

To achieve the above deployment, we can't use the existing properties in https://quarkus.io/guides/deploying-to-kubernetes#secret-volumes as it only works for folders.

Therefore, it would be a nice to have to allow having something like:

```
quarkus.kubernetes.mounts.volume-certs.path=/etc/certs
quarkus.kubernetes.secret-volumes.volume-certs.secret-name=root-secret
quarkus.kubernetes.secret-volumes.volume-certs.items.keystore.path=keystore.p12
```

**Note**: The only new change here would be the new **items** property under **volume-certs**.
And hence the Quarkus Kubernetes would generate the above Deployment manifest. 

__Perhaps, this might imply changes in Dekorate as well__
