### ISSUE TITLE
Too many io.quarkus.arc.impl.EagerInstanceHandle objects cause outOfMemory

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#25083]
### Describe the bug

My Quarkus service starts to run slowly and times out after half a day, which is shown by using jmap-histo :live command：
   1:      25257143     1010285720  io.quarkus.arc.impl.EagerInstanceHandle
   2:      25257567      606181608  io.quarkus.arc.impl.CreationalContextImpl
   3:      25257212      606173088  java.time.Duration (java.base@11.0.14)
   4:         58156      140868248  [Ljava.lang.Object; (java.base@11.0.14)
   5:        175970       14388008  [B (java.base@11.0.14)

And "io.quarkus.arc.impl.EagerInstanceHandle" is growing，not clear what is causing this object to keep growing.

This is the difference in memory usage between the two commands：
![image](https://user-images.githubusercontent.com/10733976/164584471-aea7004e-5f70-458f-b925-4908ae23c6ec.png)

### Output of `uname -a` or `ver`

Linux 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM 18.9 (build 11.0.14+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Additional information

Startup log:
```log
....
2022-04-21 19:25:57.006[INFO]-[main]-[i.quarkus(103)]: iov-analysis-service 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.5.Final) started in 8.843s. Listening on: http://0.0.0.0:8008
2022-04-21 19:25:57.007[INFO]-[main]-[i.quarkus(106)]: Profile prod activated.
2022-04-21 19:25:57.009[INFO]-[main]-[i.quarkus(107)]: Installed features: [cache, cdi, config-yaml, hazelcast-client-cluster-job, hazelcast-client-distributed-id, kafka-client, logging-gelf, logging-manager, micrometer, quarkus-apollo-config, quarkus-discovery-nacos, quarkus-hazelcast-client, quarkus-register-nacos, reactive-mysql-client, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, scheduler, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, vertx]
.....
```

**Comment by mkouba** [comment]
`EagerInstanceHandle` is a wrapper around a bean instance (stored in the context or living standalone in case of a `@Dependent` bean). If you see a large number of `EagerInstanceHandle` instances then it's very likely that some part of your app (incl. extensions) looks up beans programmaticaly via `ArcContainer.instance()` methods and keeps the references on the resulting handles.

@liuzhaozhao In any case, we will need more information. Ideally, a heap dump (hprof files). You can use `jmap` or tools like VisualVM or Eclipse MAT.

**Comment by liuzhaozhao** [comment]
> `EagerInstanceHandle` is a wrapper around a bean instance (stored in the context or living standalone in case of a `@Dependent` bean). If you see a large number of `EagerInstanceHandle` instances then it's very likely that some part of your app (incl. extensions) looks up beans programmaticaly via `ArcContainer.instance()` methods and keeps the references on the resulting handles.
> 
> @liuzhaozhao In any case, we will need more information. Ideally, a heap dump (hprof files). You can use `jmap` or tools like VisualVM or Eclipse MAT.

Thanks for the orientation

**Comment by liuzhaozhao** [comment]
@mkouba I noticed that the object wrapped in EagerInstanceHandle was Duration, and I didn't get the @Dependent bean in my service through Arc.container()，I didn't find where it came from.
![image](https://user-images.githubusercontent.com/10733976/164751796-b7ab0854-b78a-4535-93df-956697ec50b4.png)

My hprof file
https://drive.google.com/file/d/15laOHZofwAtEBjoh2UR_O69eQwWwlSHB/view?usp=sharing

**Comment by mkouba** [comment]
It seems that a GC root for a lot of these ``EagerInstanceHandle``s is `org.apache.kafka.clients.consumer.KafkaConsumer` and I can also see the `cn.ecpark.service.iov.analysis.event.consumer.rebalance.KafkaRebalanceListener` in the reference tree. Could you share the source (or at least some pseudo-source ;-) of this class?

**Comment by liuzhaozhao** [comment]
@mkouba Hi, mkouba
I manage the kafka consume offset myself, Here is the issue I mentioned earlier about usage,I'm not sure if the usage is wrong
https://github.com/quarkusio/quarkus/issues/24067

There are two consumers using the same KafkaRebalanceListener, is there a problem with this usage?

```yml
mp:
  messaging:
    incoming:
      iov-event-in:
        connector: smallrye-kafka
        topic: IOTProtocol_DC_MQ0
        graceful-shutdown: true
        group:
          id: ${quarkus.application.name}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: latest
        batch: true
        fetch:
          min:
            bytes: 102400
          max:
            wait:
              ms: 1000
        enable:
          auto:
            commit: true
        broadcast: false
        partitions: 2
        max.poll.records: 100
        failure-strategy: ignore
        consumer-rebalance-listener:
          name: iov-event-topic.rebalancer
      location-in:
        connector: smallrye-kafka
        topic: ${mp.messaging.outgoing.location-out.topic}
        graceful-shutdown: true
        group:
          id: ${quarkus.application.name}
        key:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value:
          deserializer: org.apache.kafka.common.serialization.StringDeserializer
        auto:
          offset:
            reset: latest
        enable:
          auto:
            commit: true
        broadcast: false
        partitions: 2
        max.poll.records: 2000
        failure-strategy: ignore
        consumer-rebalance-listener:
          name: iov-event-topic.rebalancer
```

```java
package cn.ecpark.service.iov.analysis.event.consumer.rebalance;

import cn.ecpark.service.iov.analysis.dao.model.EventConsumeOffset;
import cn.ecpark.service.iov.analysis.event.EventBusEvent;
import cn.ecpark.service.iov.analysis.event.bean.ConsumeOffsetEventResponse;
import cn.ecpark.service.iov.analysis.event.bean.KafkaRebalanceEvent;
import cn.ecpark.service.iov.analysis.event.bean.TopicPartitionRebalanceEvent;
import io.smallrye.common.annotation.Identifier;
import io.smallrye.reactive.messaging.kafka.KafkaConsumerRebalanceListener;
import io.vertx.mutiny.core.eventbus.EventBus;
import lombok.extern.slf4j.Slf4j;
import org.apache.kafka.clients.consumer.Consumer;
import org.apache.kafka.clients.consumer.OffsetAndTimestamp;
import org.apache.kafka.common.TopicPartition;
import org.eclipse.microprofile.config.inject.ConfigProperty;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Provider;
import java.time.Duration;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@ApplicationScoped
@Identifier("iov-event-topic.rebalancer")
public class KafkaRebalanceListener implements KafkaConsumerRebalanceListener {
    @Inject
    EventBus bus;
    @ConfigProperty(name = "device-status.init-rollback", defaultValue = "3600S")
    Provider<Duration> initRollback;


    @Override
    public void onPartitionsAssigned(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions assigned: {}", partitions);
        try {
            ConsumeOffsetEventResponse consumeOffsetEventResponse = bus.<ConsumeOffsetEventResponse>requestAndAwait(EventBusEvent.ASSIGNED_OFFSET, new KafkaRebalanceEvent(consumer.groupMetadata().groupId(), partitions)).body();
            Map<Integer, Long> persistenceOffsets = new HashMap<>();
            if(consumeOffsetEventResponse != null && consumeOffsetEventResponse.getData() != null) {
                persistenceOffsets = consumeOffsetEventResponse.getData().stream().collect(Collectors.toMap(EventConsumeOffset::getPartitionNum, EventConsumeOffset::getOffset));
            }
            Map<TopicPartition, Long> requestOffset = new HashMap<>();
            long now = System.currentTimeMillis();
            long shouldStartAt = now - initRollback.get().toMillis();
            for (TopicPartition partition : partitions) {
                Long offset = persistenceOffsets.get(partition.partition());
                if(offset != null) {
                    setOffset(consumer, partition, offset + 1);
                    log.debug("Load offset from db: {} - {}", partition.partition(), offset);
                } else {
                    requestOffset.put(partition, shouldStartAt);
                }
            }
            Map<TopicPartition, OffsetAndTimestamp> offsets = consumer.offsetsForTimes(requestOffset);
            for (Map.Entry<TopicPartition, OffsetAndTimestamp> position : offsets.entrySet()) {
                long target = position.getValue() == null ? 0L : position.getValue().offset();
                setOffset(consumer, position.getKey(), target);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        convertTopicPartitions(partitions).forEach((key, value) ->
                bus.requestAndAwait(EventBusEvent.ASSIGNED_PREFIX + key, new TopicPartitionRebalanceEvent(key, value)));
    }

    private void setOffset(Consumer<?, ?> consumer, TopicPartition partition, long offset) {
        log.debug("Seeking position {} for partition {}", offset, partition);
        consumer.seek(partition, offset);
    }

    private Map<String, Collection<TopicPartition>> convertTopicPartitions(Collection<TopicPartition> partitions) {
        Map<String, Collection<TopicPartition>> topicPartitions = new HashMap<>();
        for (TopicPartition partition : partitions) {
            topicPartitions.computeIfAbsent(partition.topic(), k -> new ArrayList<>()).add(partition);
        }
        return topicPartitions;
    }
    @Override
    public void onPartitionsRevoked(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions revoked: {}", partitions);
        if(partitions.isEmpty()) {
            return;
        }
        convertTopicPartitions(partitions).forEach((key, value) ->
                bus.requestAndAwait(EventBusEvent.REVOKED_PREFIX + key, new TopicPartitionRebalanceEvent(key, value)));
    }

    @Override
    public void onPartitionsLost(Consumer<?, ?> consumer, Collection<TopicPartition> partitions) {
        log.info("Partitions lost: {}", partitions);
        if(partitions.isEmpty()) {
            return;
        }
        convertTopicPartitions(partitions).forEach((key, value) ->
                bus.requestAndAwait(EventBusEvent.REVOKED_PREFIX + key, new TopicPartitionRebalanceEvent(key, value)));
    }

}
```
