### ISSUE TITLE
Can't config multiple datasource as yaml file

### ISSUE THREAD

**Issue by matkinhig** [quarkusio/quarkus#25356]
### Describe the bug

i am having some problem regarding config multiple datasource using yml file,
all works great using the `appliction.properties` file as per the  [quarkus docs ](https://quarkus.io/guides/datasource), but when I change to the `appplication.yaml` file the quarkus compiler doesn't recognize it.
where did i do wrong? Looking forward to learning from you.

this is my file :
```yaml
quarkus:
  http:
    port: 8080
    cors:
      ~: true
      methods: GET,PUT,POST,PATCH
  hibernate-orm:
    database:
      generation: "none"
      default-schema: default
    log:
      sql: false
  rest-client:
    org.acme.rest.client.ExtensionsService:
      url: ""
  log:
    category:
      "io.quarkus.category":
        level: INFO
  container-image:
    registry: localhost:5000
    group: 
  jib:
    base-jvm-image: eclipse-temurin:17-jre
  datasource:
    - command:
        db-kind: postgresql
        jdbc:
          url: ""
        schema: transaction
        username: ""
        password: ""
    - query:
        db-kind: postgresql
        jdbc:
          url: ""
        schema: transaction
        username: ""
        password: ""

  flyway:
    schemas: default
    locations: classpath:schemas
    migrate-at-start: false
  smallrye-graphql:
    show-runtime-exception-message:
      - vn.bizzi.error.TestException
      - vn.bizzi.error.TransactionNotFoundException
      - vn.bizzi.error.UnknownException
    error-extension-fields:
      - code
"%dev":
  quarkus:
    http:
      port: 8081
    datasource:
      db-kind: postgresql
      jdbc:
        url: jdbc:postgresql://localhost:5432/default
      username: default
      password: secret
      schema: default
      "command":
        db-kind: postgresql
        jdbc:
          url: postgresql://localhost:5432/default
        username: default
        password: secret
        schema: default
      "query":
        db-kind: postgresql
        jdbc:
          url: jdbc:postgresql://localhost:5432/default
        schema: default
        username: default
        password: secret
  rest-client:
    org.acme.rest.client.ExtensionsService:
      url: https://stage.code.quarkus.io/api

```
thank alot for any help.
