### ISSUE TITLE
Configurations for Authorization of Web Endpoint doesn't work properly with different profiles

### ISSUE THREAD

**Issue by jmartinspt** [quarkusio/quarkus#25719]
### Describe the bug

I'm trying to configure different policies for different profiles in quarkus and only for these configurations, the ones defined for my prod profile are always being read.

Here is my configuration file (application.yaml):

```yaml
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_WLY_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  http:
    cors: true
    auth:
      policy:
        report-policy:
          roles-allowed: MyApp.Report, MyApp.Developer
        analytics-policy:
          roles-allowed: MyApp.Analytics, MyApp.Developer
      permission:
        report:
          paths: /api/v2/users/report
          policy: report-policy
        analytics:
          paths: /api/v2/analytics/*
          policy: analytics-policy
"%prod":
  quarkus:
      auth:
        policy:
          report-policy:
            roles-allowed: MyApp.Report
          analytics-policy:
            roles-allowed: MyApp.Analytics

"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true
        format-sql: true
        jdbc-warnings: true

"%local":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://${DB_HOST}:5433/${DB_WLY_NAME}
    hibernate-orm:
      log:
        sql: true
        format-sql: true
        jdbc-warnings: true
```
On my machine, using quarkus plugin on IntelliJ and the different profiles, the configurations work properly, but when I package the code with mvn command **mvn clean package** run it on docker passing the environment "QUARKUS_PROFILE=dev" or "-Dquarkus.profile=dev" on JAVA_OPTIONS environment variable, The applications will assume the prod profile only for "quarkus.auth" properties, the hibernate-orm works fine for example.
But If I package the code with dev profile **mvn clean package -Dquarkus.profile=dev** the configurations are correct, but I won't do that, I want to build the application just one time and pass different environment variables.

### Expected behavior

When passed the QUARKUS_PROFILE=dev the application will considers the **MyApp.Report** and **MyApp.Developer** roles

### Actual behavior

When passed the QUARKUS_PROFILE=dev the application considers the **MyApp.Report** role

### How to Reproduce?

1. Use different policies for different quarkus profiles on application.yaml config file
2. Compile the application **mvn clean package**
3. Run the application with **QUARKUS_PROFILE=dev** environment variable

### Output of `uname -a` or `ver`

Linux myapp-backend-7fbd44bc98-xxxx 5.4.0-1063-azure #66~18.04.1-Ubuntu SMP Thu Oct 21 09:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19 LTS OpenJDK Runtime Environment 18.9 (build 11.0.15+10-LTS) OpenJDK 64-Bit Server VM 18.9 (build 11.0.15+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: /Users/xxxxxx/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4 Java version: 1.8.0_232, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/jre Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by jmartinspt** [comment]
@sberyozkin thanks for the reply, I have already tried that. 
The quarkus will assume the properties defined on %dev, only the  **auth** are overridden by %prod profile instead the default defined on top of the properties file.

**Comment by sberyozkin** [comment]
@jmartinspt may be it is due to the fact these are build time properties, referenced from https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/HttpBuildTimeConfig.java#L27

@radcortez Can you comment please ?

**Comment by radcortez** [comment]
The configuration is set as build-time only (these are identified by the lock icon):
https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus.http.auth.policy.-role-policy-.roles-allowed

This means that the configuration is only read and evaluated during the build and it is fixed when you run the app (so you can't change it anymore). If this behavior is not desired we need to discuss what are the implications of changing the configuration to be evaluated at runtime as well. I had a quick look, and it seems we are not doing anything special with it during the build.

**Comment by jmartinspt** [comment]
Thanks @sberyozkin and @radcortez, 
In fact, it was my distraction and I didn't read the documentation more carefully. 
My intention was just to activate a Developer Role for the DEV and LOCAL environments and disable this role in PROD.
To avoid building the application for different targets, I chose the following configuration:
```
quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_WLY_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
  http:
    cors: true
    auth:
      policy:
        report-policy:
          roles-allowed: MyApp.Report
        analytics-policy:
          roles-allowed: MyApp.Analytics
        developer-policy:
          roles-allowed: MyApp.Developer
      permission:
        report:
          paths: /api/v2/users/report
          policy: report-policy
        analytics:
          paths: /api/v2/analytics/*
          policy: analytics-policy
        permit-all:
          paths: /api/v2/users/report, /api/v2/analytics/*
          policy: developer-policy
          methods: GET,HEAD,POST,PUT,DELETE,CONNECT,TRACE,PATCH,OPTIONS
"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: true
        format-sql: true
        jdbc-warnings: true

"%local":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:postgresql://${DB_HOST}:5433/${DB_WLY_NAME}
    hibernate-orm:
      log:
        sql: true
        format-sql: true
        jdbc-warnings: true
```

And disable the permission `permit-all` only on PROD environment with system property:
`-Dquarkus.http.auth.permission.permit-all.enabled=false`

I follow this documentation:
https://quarkus.io/guides/security-authorization

This approach works for me.

Thanks again for clarifying me, and in fact, it is not a bug, but the behavior of these settings
