### ISSUE TITLE
2.8.0 YAML config no longer working in 2.9.2

### ISSUE THREAD

**Issue by tbkahuna48** [quarkusio/quarkus#26009]
The below works in 2.8.0 but not in 2.9.2. 
Here are the respective configs in memory. 
You will notice that. in the 2.9.2 - the map keys are messed up. It appears that the keys for the Map<String, MessageUtilConfiguration> messageUtilConfigurations() in the config file have also been used for the key for the Map<String, Map<String, MessageUtilConfiguration>> messageUtilConfigsMap(); 
I've highlighted the map keys which are different in the 2 versions.

correct config with 2.8.0 top map key should be "filter"
```
messageHandlerConfigurations	MessageUtilConfigurations249831481Impl  (id=264)	
	enableDataswapDetection	Optional<T>  (id=275)	
	messageUtilConfigsMap	HashMap<K,V>  (id=277)	
		[0]	HashMap$Node<K,V>  (id=295)	
			key	"**filter**" (id=299)	
			value	HashMap<K,V>  (id=300)	
				[0]	HashMap$Node<K,V>  (id=314)	
					key	"**default**" (id=316)	
					value	MessageUtilConfigurations$MessageUtilConfiguration-464514824Impl  (id=317)	
				[1]	HashMap$Node<K,V>  (id=315)	
		[1]	HashMap$Node<K,V>  (id=296)	
			key	"client" (id=301)	
			value	HashMap<K,V>  (id=302)	
				[0]	HashMap$Node<K,V>  (id=310)	
					key	"reaction-api" (id=312)	
					value	MessageUtilConfigurations$MessageUtilConfiguration-464514824Impl  (id=313)	
				[1]	HashMap$Node<K,V>  (id=311)	
	messageUtilConfigurations	Collections$EmptyMap<K,V>  (id=283)	
	returnDetailedError	Optional<T>  (id=285)	
requestScopedContext	RequestScopedContext_ClientProxy  (id=268)	
```

bad Config with 2.9.2 (no code changes) top map key seems to be the key for the contained map "default "rather than "filter"

```
messageHandlerConfigurations	MessageUtilConfigurations249831481Impl  (id=225)	
	enableDataswapDetection	Optional<T>  (id=250)	
	messageUtilConfigsMap	HashMap<K,V>  (id=251)	
		[0]	HashMap$Node<K,V>  (id=280)	
			key	"**default**" (id=297)	
			value	HashMap<K,V>  (id=298)	
				[0]	HashMap$Node<K,V>  (id=336)	
					key	"**default**" (id=346)	
					value	MessageUtilConfigurations$MessageUtilConfiguration-464514824Impl  (id=347)	
		[1]	HashMap$Node<K,V>  (id=281)	
			key	"reaction-api" (id=299)	
			value	HashMap<K,V>  (id=300)	
				[0]	HashMap$Node<K,V>  (id=348)	
					key	"reaction-api" (id=359)	
					value	MessageUtilConfigurations$MessageUtilConfiguration-464514824Impl  (id=360)	
		[2]	HashMap$Node<K,V>  (id=282)	
		[3]	HashMap$Node<K,V>  (id=283)	
	messageUtilConfigurations	Collections$EmptyMap<K,V>  (id=262)	
	returnDetailedError	Optional<T>  (id=264)	
requestScopedContext	RequestScopedContext_ClientProxy  (id=229)	
```
Config interface:

```java
@ConfigMapping(prefix = "message-util-configurations", namingStrategy = ConfigMapping.NamingStrategy.KEBAB_CASE)
public interface MessageUtilConfigurations {

    Optional<Boolean> enableDataswapDetection();

    Optional<Boolean> returnDetailedError();

    Map<String, Map<String, MessageUtilConfiguration>> messageUtilConfigsMap();
    Map<String, MessageUtilConfiguration> messageUtilConfigurations();

    interface MessageUtilConfiguration {
    	Optional<Boolean> enableDataswapDetection();
        //Includes 'default'
        List<MessageUtilInstruction> messageUtilInstructions();

        interface MessageUtilInstruction {
            String name(); //x-correlationId

            String instructionType(); // REQUEST, RESPONSE

            String matchStrategy(); // REQUIRED

            Optional<String> groomAction(); // null, REPLACE

            String location(); //HDR

            String type(); //VALUE

            Optional<String> expression();  //null

            Optional<Boolean> loggable(); //true, false

            Optional<String> errorCode(); //515

            Optional<String> errorMsg(); // x-correlationId is required

            Optional<String> associatedInstruction(); // "x-correlationId" or whatever is in the 'name'
        }

    }
    
}
```
Associated Snippet from YAML file:

```yaml
#====================================================================
# Messagehandler config
#====================================================================
message-util-configurations:
  enable-dataswap-detection: true
  message-util-configs-map:
    filter:
      default:
        enable-dataswap-detection: false
      get-jokes-uni:
        enable-dataswap-detection: true
        message-util-instructions:
          - name: x-correlationId
            instruction-type: REQUEST
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true

          - name: x-correlationId
            associated-instruction: x-correlationId
            instruction-type: RESPONSE
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true

    client:
      reaction-api:
        enable-dataswap-detection: true
        message-util-instructions:
          - name: x-correlationId
            instruction-type: REQUEST
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true

          - name: x-correlationId
            associated-instruction: x-correlationId
            instruction-type: RESPONSE
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true

      setup-api:
        enable-dataswap-detection: true
        message-util-instructions:
          - name: x-correlationId
            instruction-type: REQUEST
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true

          - name: x-correlationId
            associated-instruction: x-correlationId
            instruction-type: RESPONSE
            match-strategy: REQUIRED
            groom-action: ''
            location: HDR
            type: VALUE
            loggable: true
```
