### ISSUE TITLE
Route generated by OpenShift extension should use named port

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#26587]
### Describe the bug

When generating openshift yamls using the OpenShift extension, the `Route` object that gets generated should use named ports. This is especially important if you run the application on a different port than the default (i.e. by setting `quarkus.http.port` to something).

### Expected behavior

I would expect the `Route` to look like this:

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-07-06 - 14:54:14 +0000
  labels:
    app.kubernetes.io/name: route-wrong
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: route-wrong
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: route-wrong
```

### Actual behavior

But instead, it looks like this:

```yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-07-06 - 14:54:14 +0000
  labels:
    app.kubernetes.io/name: route-wrong
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: route-wrong
spec:
  port:
    targetPort: 8082
  to:
    kind: Service
    name: route-wrong
```

The problem with this is that with the `Service` that is generated, the `Service` accepts requests on port `80` and not `8082`.

```yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.openshift.io/vcs-url: <<unknown>>
    app.quarkus.io/build-timestamp: 2022-07-06 - 14:54:14 +0000
  labels:
    app.kubernetes.io/name: route-wrong
    app.kubernetes.io/version: 1.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  name: route-wrong
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8082
  selector:
    app.kubernetes.io/name: route-wrong
    app.kubernetes.io/version: 1.0-SNAPSHOT
  type: ClusterIP
```

By changing the `Route` to use the named port (`http`), then the actual ports don't really matter so long as the `Service` is correct (which it is).

### How to Reproduce?

Reproducer:

[route-wrong.zip](https://github.com/quarkusio/quarkus/files/9055904/route-wrong.zip)

1. Unzip reproducer
2. `cd route-wrong`
3. `./mvnw package`
4. Examine `target/kubernetes/openshift.yml`

### Output of `uname -a` or `ver`

```
Darwin edeandrea-m1pro 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

### Output of `java -version`

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```

### Quarkus version or git rev

2.10.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/17.0.3-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"
```
