### ISSUE TITLE
[DOC] quarkus-extension.yaml format and fields not explined in Quarkus web-docs

### ISSUE THREAD

**Issue by alexeysharandin** [quarkusio/quarkus#26689]
### Describe the bug

Hi everyone,
I found reference to quarkus-extension.yaml only here https://quarkus.io/guides/writing-extensions but without any explanations whats fields can be added in yaml and what these fields doing.

based on review of yaml's from extentions and java code I found 
```
group-id: 
artifact-id:
metadata:
  unlisted: 
  config:
    - "quarkus.***"
```

Maybe something else exists but not required for me at this stage.

Is possible to improve docs? It's not require a lot of time.
