### ISSUE TITLE
Kubernetes Ingress path should be configurable

### ISSUE THREAD

**Issue by ThoSap** [quarkusio/quarkus#26747]
### Describe the bug

Currently, the `quarkus-kubernetes` extension (2.10.2.Final) does not honor the value of Quarkus property `quarkus.http.root-path`, so the Kubernetes ingress path is always the root `/`.

### Expected behavior

The Kubernetes ingress path should equal property `quarkus.http.root-path`.

**application.properties**
```
quarkus.http.root-path=/newroot
```
**kubernetes.yml**
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-14 - 15:06:39 +0000
  labels:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
  name: quarkus-app
  namespace: my-namespace
spec:
  rules:
    - host: myhost.example.com
      http:
        paths:
          - backend:
              service:
                name: quarkus-app
                port:
                  name: http
            path: /newroot
            pathType: Prefix
```

### Actual behavior

**application.properties**
```
quarkus.http.root-path=/newroot
```
**kubernetes.yml**
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-07-14 - 15:06:39 +0000
  labels:
    app.kubernetes.io/name: quarkus-app
    app.kubernetes.io/version: 1.0.0
  name: quarkus-app
  namespace: my-namespace
spec:
  rules:
    - host: myhost.example.com
      http:
        paths:
          - backend:
              service:
                name: quarkus-app
                port:
                  name: http
            path: /
            pathType: Prefix
```

### How to Reproduce?

https://code.quarkus.io/?j=17&e=kubernetes&e=resteasy-reactive&e=resteasy-reactive-jackson&extension-search=origin:platform%20resteasy

**application.properties**
```
quarkus.http.root-path=/newroot
```

### Output of `uname -a` or `ver`

Linux myhost 4.18.0-372.13.1.0.1.el8_6.x86_64 #1 SMP Fri Jul 1 15:06:54 PDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### GraalVM version (if different from Java)

OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.10.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2
