### ISSUE TITLE
Inconsistent configuration substitution when using Dev Services with a named DataSource

### ISSUE THREAD

**Issue by rgmz** [quarkusio/quarkus#26794]
### Describe the bug

When writing an application, it is common to want a real/configurable database URL for development and production, but a Dev Services URL for tests. However, depending on whether you're using a top-level `datasource` or a named `datasource`, Quarkus may not inject the dev services URL.

### Expected behavior

I would expect both of the following configurations to be equivalent and use `${MY_DB_URL}` in dev/prod, and the generated Dev Services URL in `test`.

1. top-level datasource
    ```yml
    # src/main/resources/application.yml
    quarkus:
      datasource:
        db-kind: postgresql
        reactive:
          url: "${MY_DB_URL}
    
    # src/test/resources/application.yml
    "%test":
      quarkus:
        datasource:
          db-kind: postgresql
          devservices:
            enabled: true
    ```
2. named datasource (this is reproducible with both `name:` and `"name":`)
    ```yml
    # src/main/resources/application.yml
    quarkus:
      datasource:
        reactive: false
        "app":
          db-kind: postgresql
          reactive:
            url: "${MY_DB_URL}
    
    # src/test/resources/application.yml
    "%test":
      quarkus:
        datasource:
          "app":
            db-kind: postgresql
            devservices:
              enabled: true
    ```

Here's a basic test case, albeit it isn't necessary:

```kotlin
package org.acme

import io.quarkus.test.junit.QuarkusTest
import io.vertx.mutiny.pgclient.PgPool
import org.junit.jupiter.api.Test
import javax.inject.Inject

@QuarkusTest
class DatasourceTest {
    @Inject
//    @ReactiveDataSource("app")
    lateinit var pool: PgPool

  @Test
  fun `should connect`() {
      val row = pool.query("SELECT current_user, inet_server_addr(), inet_server_port()")
          .execute()
          .await()
          .indefinitely()
          .first()
  
      println("Connection is: user=${row.getString("current_user")}, host=${(row.getValue("inet_server_addr") as Inet).address}, port=${row.getInteger("inet_server_port")}")
  }
}
```

### Actual behavior

**Using a top-level datasource**

The client fails to connect. (In this case, `MY_DB_URL` is defined as a `postgresql://localhost:5432`.)

```
java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5432

	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:79)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:65)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:46)
	at org.acme.DatasourceTest.should connect(DatasourceTest.kt:19)
```

**Using a named datasource**

The client works as expected, connecting to the instance generated by Dev Services.

```
Connection is: user=quarkus, host=/172.17.0.3, port=5432
```

### Output of `java -version`

11

### Quarkus version or git rev

2.10.2.Final

**Comment by rgmz** [comment]
The runtime configurations (from `ConfigProvider.getConfig()`) seem to be more-or-less the same:

#### Top-Level DataSource


(5)  `YamlConfigSource[source=file:/...application.yml]` 
```
quarkus.datasource.reactive.url -> "postgresql://localhost:5432/quarkus"
```

(7) `PropertiesConfigSource[source=Specified default values]` has:
```
quarkus.datasource.reactive.url -> "postgresql://localhost:5432/quarkus"
```

(8) `PropertiesConfigSource[source=Runtime Defaults]` has both:
```
quarkus.datasource.reactive.url -> "vertx-reactive:postgresql://localhost:49421/app?loggerLevel=OFF"
quarkus.datasource.username -> "quarkus"
quarkus.datasource.password -> "quarkus"
```

#### Named DataSource

(5)  `YamlConfigSource[source=file:/...application.yml]` 
```
quarkus.datasource.app.reactive.url -> "postgresql://localhost:5432/quarkus"
```

(7) `PropertiesConfigSource[source=Specified default values]` has:
```
quarkus.datasource.app.reactive.url -> "postgresql://localhost:5432/quarkus"
```

(8) `PropertiesConfigSource[source=Runtime Defaults]` has both:
```
quarkus.datasource.app.reactive.url -> "vertx-reactive:postgresql://localhost:49421/app?loggerLevel=OFF"
quarkus.datasource.app.username -> "quarkus"
quarkus.datasource.app.password -> "quarkus"
quarkus.datasource."app".reactive.url -> "vertx-reactive:postgresql://localhost:49421/app?loggerLevel=OFF"
```

**Comment by rgmz** [comment]
@radcortez: Apologies for the ping, but this didn't get tagged as `area/config` and you seem to be the person for that.

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
I'm not able to reproduce the issue with the supplied configuration.

Looking into the configuration, `quarkus.datasource.reactive.url` (which has an expression to `${MY_DB_URL}` is set in the main profile (the one used by prod). Configuration set in the main profile will always be active, regardless of any other profile, meaning that the value set in `quarkus.datasource.reactive.url` will be used for `prod`, `test` and `dev`, if they are in a higher ordinal source, which is the case.

To be able to achieve the desired outcome, you can use the following configuration:

```yaml
quarkus:
  datasource:
    "app":
      db-kind: postgresql

"%test":
  quarkus:
    datasource:
      "app":
        devservices:
          enabled: true

"%prod":
  quarkus:
    datasource:
      "app":
        username: database
        password: password
        reactive:
          url: "${MY_DB_URL}"

"%dev":
  quarkus:
    datasource:
      "app":
        username: database
        password: password
        reactive:
          url: "${MY_DB_URL}"
```

In this case, the expression will only be used for `dev` and `prod`, and since `test` does not define one, it will fall back to the one set by DevServices.
