### ISSUE TITLE
2.11.1: OpenAPI format broken for java.time.* types

### ISSUE THREAD

**Issue by tanadeau** [quarkusio/quarkus#27011]
### Describe the bug

Going from 2.10.4 to 2.11.1 causes invalid OpenAPI YAML to be generated when using java.time.* types like `OffsetDateTime`

### Expected behavior

A query parameter with type `OffsetDateTime` should have an OpenAPI definition like below (as was the case for 2.10.x):

```yaml
      - name: createdAfter
        in: query
        description: Filter by creation after provided date
        schema:
          format: date-time
          type: string
```

### Actual behavior

The schema changed to an invalid schema referencing an `OffsetDateTime` component that is not in the generated YAML file:

```yaml
      - name: createdAfter
        in: query
        description: Filter by creation after provided date
        schema:
          $ref: '#/components/schemas/OffsetDateTime'
```

### How to Reproduce?

Steps to reproduce behavior:
1. Create a resource with an OffsetDateTime query parameter or a model with a field of the same type
2. Generate OpenAPI YAML file

### Output of `uname -a` or `ver`

Darwin C02YK01PLVCG-ML 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:22 PDT 2022; root:xnu-8020.121.3~4/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### Quarkus version or git rev

2.11.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5
