### ISSUE TITLE
Add empty scopes for oauth flow

### ISSUE THREAD

**Issue by shnplr** [quarkusio/quarkus#27857]
### Description

For OAuth Flow Object specification for "scopes" states:

REQUIRED. The available scopes for the OAuth2 security scheme. A map between the scope name and a short description for it. The map MAY be empty.

Adding quarkus-smallrye-openapi dependency to oidc example project generates /q/openapi such as 

```
securitySchemes:
    SecurityScheme:
      type: oauth2
      description: Authentication
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/quarkus/protocol/openid-connect/auth
          tokenUrl: http://localhost:8080/realms/quarkus/protocol/openid-connect/token/introspect
          refreshUrl: http://localhost:8080/realms/quarkus/protocol/openid-connect/token
```
It could be a good feature to include empty scopes in this case to support the spec:
```
        implicit:
          scopes: {}
```

### Implementation ideas

org.eclipse.microprofile.openapi.models.security.OAuthFlow.setScopes(Map<String, String> scopes)

Perhaps it can be set to an empty map if null
