### ISSUE TITLE
kubernetes init container value wrong in yaml

### ISSUE THREAD

**Issue by csscriptplus** [quarkusio/quarkus#27934]
### Describe the bug

**My maven build has following parameters:**

- -Dquarkus.kubernetes.init-containers."init-containers".image=curlimages/curl:latest
- -Dquarkus.kubernetes.init-containers."init-containers".command=["sh","-c"]
- -Dquarkus.kubernetes.init-containers."init-containers".arguments=["while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done"]

**That is wrote in the Kubernetes.yml:**
```
  - args:
        - "[while [ 200 -ne 200 ]; do sleep 2; done]"
    command:
        - "[sh"
        - "-c]"
    image: curlimages/curl:latest
```

**I would like that:**
```
   - command: ["sh", "-c"]
     args: ["while [ $(curl -ksw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done"]
     image: curlimages/curl
```

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.11.2

**Comment by csscriptplus** [comment]
@geoand it doesn't work.
```
command:
        - "[\"sh\""
        - "\"-c\"]"
```

**Comment by Sgitario** [comment]
I think the problem is that you're wrapping the values with `[...]` in the `command` and `arguments` properties. These properties are a comma-separated list. Instead, I tried with:

```
quarkus.kubernetes.init-containers."init-containers".command=sh -c
quarkus.kubernetes.init-containers."init-containers".arguments=while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done
```

And the output looks better:

```yaml
initContainers:
      - args:
          - "while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null)\
            \ -ne 200 ]; do sleep 2; done"
        command:
          - sh -c
```

Note the stripping of the `args` value (it's in two lines because it's too long). I think this is automatically done by the yaml serializer (Jackson) and I'm not sure if it interferes with the execution, please let me know if so, as I think it would need some fixing on the Dekorate side.
