### ISSUE TITLE
New OpenShift property in order to set a custom port name

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#28225]
### Description

As a developer, I would like to be able to set my port name on K8s / OpenShift, though a new application.property. 

Service.yaml example

```
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "app"
      scenarioId: "OpenShiftRESTEasyMultipartIT-1664289247997"
    name: "app"
    namespace: "ts-kgzhdlzegk"
  spec:
    ports:
    - name: "http"
      port: 80
      targetPort: 8080
    selector:
      app.kubernetes.io/name: "app"
    type: "ClusterIP"
``` 

Currently, by default, I am getting the above service.yaml. My proposal is to be able to set a custom port name instead of using the default "http" name. 

### Implementation ideas

Create a new property as `quarkus.openshift.ports.name` that allows setting a custom target service port name.

Example: 

application.property
```
quarkus.openshift.ports.name=pepito
```

generated service.yaml

```
  kind: "Service"
  metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "app"
      scenarioId: "OpenShiftRESTEasyMultipartIT-1664289469424"
    name: "app"
    namespace: "ts-hofpydrzff"
  spec:
    ports:
    - name: "pepito"
      port: 80
      targetPort: 8080
    selector:
      app.kubernetes.io/name: "app"
    type: "ClusterIP"
```

route.yaml

```

apiVersion: route.openshift.io/v1
kind: Route
metadata:
    labels:
      app.openshift.io/runtime: "quarkus"
      app.kubernetes.io/name: "app"
      scenarioId: "OpenShiftRESTEasyMultipartIT-1664289469424"
    name: "app"
    namespace: "ts-hofpydrzff"
spec:
  port:
    targetPort: pepito
  to:
    kind: Service
    name: app
```
