### ISSUE TITLE
Add codestart data option in CLI and Maven plugin

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#28372]
### Description

It would be nice extension codestart to have user customizable data. This is already possible in codestarts but not yet connected in the tooling.

It would behave like this:

```shell
quarkus create app -x=my-ext -d=my-ext-codestart.foo.bar=hello,my-ext-codestart.foo.hello=andy
```

The `my-ext-codestart` prefix is required by the codestart system to know the data is targeting this particular codestart data (and avoid conflicts)

The default value is in the codestart.yml:
```yaml
name: my-ext-codestart
language:
  base:
    data:
      foo:
        bar: baz
        hello: world
```

FYI: I created this issue because @gsmet has a need for this.
