### ISSUE TITLE
[FR]: OpenTelemetry Auto-instrumentation for AWS SDK "Howto" guide/code example

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#28411]
### Description

If possible, it'd be great to have an example of how to configure tracing for AWS SDK calls that happen in a Quarkus app.
I read the docs and searched through the Quarkus repo source code but couldn't find anything on this

Also, pulling in these libraries does not seem to do the trick:
```kt
implementation("io.quarkus:quarkus-opentelemetry-exporter-otlp")
implementation("io.opentelemetry:opentelemetry-extension-trace-propagators")
implementation("io.opentelemetry:opentelemetry-extension-aws")
```

Related Zulip convo:
- https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20AWS.20SDK.20auto-instrument.3F

**Comment by brunobat** [comment]
A few questions...
Your Quarkus APP uses the AWS sdk how? Can you please give an example and the used dependencies?
Where do you see the traces? Locally? On some AWS Service?
Which specific tutorials did you follow until now?

**Comment by GavinRay97** [comment]
Sure, this app specifically uses the AWS SDK v2.x to make calls to AWS Athena and AWS Glue services

The dependency used is the shaded AWS SDK in this JDBC driver:
- https://docs.aws.amazon.com/athena/latest/ug/connect-with-jdbc.html#download-the-jdbc-driver

> Where do you see the traces? Locally? On some AWS Service?

I have `jaeger-all-in-one` set up like this:
```yaml
services:
    # OpenTracing
    jaeger:
        image: jaegertracing/all-in-one:1.37
        restart: always
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14250:14250
            - 14268:14268
            - 14269:14269
            - 4317:4317 # OTLP gRPC
            - 4318:4318 # OTLP HTTP
            - 9411:9411
        environment:
            COLLECTOR_OTLP_ENABLED: "true"
```

And the following dependencies:
```kt
    implementation("io.quarkus:quarkus-opentelemetry-exporter-otlp")
    implementation("io.opentelemetry.instrumentation:opentelemetry-aws-sdk-2.2-autoconfigure")
    implementation("io.opentelemetry:opentelemetry-extension-trace-propagators")
    implementation("io.opentelemetry:opentelemetry-extension-aws")
    implementation(files("../lib/AthenaJDBC${ProjectVersions.athena}.jar"))
```

> Which specific tutorials did you follow until now?

These ones:
- https://quarkus.io/guides/opentelemetry
- https://developers.redhat.com/articles/2022/08/08/opentelemetry-quarkus-superheroes-demo-observability
- https://developers.redhat.com/articles/2022/06/21/distributed-tracing-opentelemetry-knative-and-quarkus
- https://aws-otel.github.io/docs/getting-started/java-sdk/trace-manual-instr#instrumenting-the-aws-sdk
