### ISSUE TITLE
Quarkus extension developent: allow access to all config keys at build time

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#28415]
### Description

Suppose we have an extension with a nested structure (like `datasource`s), but with no compile-time fixated values, e.g.:

```
quarkus:
  artemis:
    url: tpc://borker-url-0
    named-connection-one:
      url: tcp://borker-url-1
    named-connection-two:
      url: tcp://borker-url-2
    ...
```
All those values are not compile-time fixated. I would like to be able to access all keys (not value) present at compile-time, i.e. in the example above, I want ot be able to see `named-connection-one`, `named-connection-two`, ...
