### ISSUE TITLE
Generated Ingress resource has duplicate paths elements

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#28812]
### Describe the bug

The generated Ingress resource has duplicate paths elements. This can be reproducible using the Quarkus Kubernetes extension and enabling the ingress exposition (`quarkus.kubernetes.ingress.expose=true`).
The generated Ingress resource looks like:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 64db796fa05191004c9a6f5f907f04ef11ae9e49
    app.quarkus.io/build-timestamp: 2022-10-25 - 09:34:28 +0000
  labels:
    app.kubernetes.io/name: kubernetes-with-ingress-rules
    app.kubernetes.io/version: 0.1-SNAPSHOT
  name: kubernetes-with-ingress-rules
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: kubernetes-with-ingress-rules
                port:
                  name: http
            path: /
            pathType: Prefix
          - backend:
              service:
                name: kubernetes-with-ingress-rules
                port:
                  name: http
            path: /
            pathType: Prefix
```

The expected behavior is that only one path is created. 

This issue is caused by this change in Dekorate upstream: https://github.com/dekorateio/dekorate/pull/1085

This is only happening using Quarkus main `999-SNAPSHOT`.
