### ISSUE TITLE
gRPC and generation of Knative resources port name error

### ISSUE THREAD

**Issue by hernael** [quarkusio/quarkus#29073]
### Describe the bug

The YAML generated by:
`quarkus.kubernetes.deployment-target=knative`
container port name is:
```
          ports:
            - containerPort: 9000
              name: grpc
              protocol: TCP
```
Knative deployment contains error:
```
"validation.webhook.serving.knative.dev" denied the request: validation failed: Port name grpc is not allowed: spec.template.spec.containers[0].ports Name must be empty, or one of: 'h2c', 'http1' more than one container port is set: spec.template.spec.containers[*].ports Only a single port is allowed across all containers (retried 5 times).
```

            

### Quarkus version or git rev

2.13.2

### Additional information

Knative version: 1.5
