### ISSUE TITLE
Panache reactive sequence - default schema not applied

### ISSUE THREAD

**Issue by silviu-negoita** [quarkusio/quarkus#29248]
### Describe the bug

I'm tying to persist a simple entity, in a custom schema using Panache Reactive
```
@Entity
@Table(name = "notification")
public class NotificationEntity extends PanacheEntityBase {

    @Id
    @SequenceGenerator(name = "notification_id_seq", sequenceName = "notification_id_seq")
    @GeneratedValue(generator = "notification_id_seq", strategy = GenerationType.IDENTITY)
    Long id;

    @NaturalId
    @Column(name = "external_id", nullable = false)
    private String externalId;

}
```

And REST call to test: 
```
    @GET
    @Path("/hello")
    @ReactiveTransactional
    public Uni<NotificationEntity> hello() {

        var notification = new NotificationEntity()
                .setExternalId(UUID.randomUUID().toString());

        return notification.persist();

    }
```

I have configured a default schema in yaml ( `ncs` )
```
quarkus:
  datasource:
    reactive:
      url: vertx-reactive:${DATABASE_TYPE:postgresql}://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:}
    db-kind:
      postgresql
    username: ${DATABASE_USERNAME:unset}
    password: ${DATABASE_PASSWORD:unset}
  hibernate-orm:
    database:
      default-schema: ncs
```

Confirming that `notification_id_seq` exists under my schema. 

### Expected behavior

Im assuming hibernate can map `ncs.notification_id_seq` and do the persist correctly. 

### Actual behavior

My REST endpoint call is never ending. No errors are thrown. 

If I'm adding the schema on my JPA entity under `SequenceGenerator` annotation:
```
@SequenceGenerator(name = "notification_id_seq", sequenceName = "notification_id_seq", schema = "ncs")
```

It works!

If I am manually creating the `notification_id_seq` under `public` schema it also works. Somehow `quarkus.hibernate-orm.database.default-schema` is totally ignored by hibernate. 

P.S. 
`quarkus.hibernate-orm.database.generation` is set to `none`, because im using Flyway to manually migrate DB. 

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.3
