### ISSUE TITLE
Upgrading to 2.14 ignores custom Kubernetes manifests (based on profile)

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#29241]
### Describe the bug

You used to be able to apply a custom manifest based on the profile when generating the Kubernetes manifests.  Now, it does not and it creates two paths at the root prefix.

The `application.yml` that is used in the service when generating the manifest looks like this:
```yaml
"%cluster":
  quarkus:
    kubernetes:
      env:
        fields:
          KUBERNETES_NAMESPACE: metadata.namespace
          HOST_IP: status.hostIP
     
"%kubernetes":
  quarkus:
    config:
      profile:
        parent: cluster
    container-image:
      build: false
    kubernetes:
      deployment-target: kubernetes
      replicas: 2
      ingress:
        expose: true
        host: "localhost"
        annotations:
          alb.ingress.kubernetes.io/scheme: internet-facing
          alb.ingress.kubernetes.io/target-type: ip
          alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
          alb.ingress.kubernetes.io/ssl-redirect: '443'
          alb.ingress.kubernetes.io/healthcheck-path: /q/health/ready
```

The service has a `kubernetes.yml` (under `service/src/main/resources`) which was applied based on the profile before.

### Expected behavior

The overlay for a profile is applied as it was in 2.13.x (using the `kubernetes.yml` under /resources)

```yaml
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: service
                port:
                  number: 80
            path: /a/aaa
            pathType: Prefix
          - backend:
              service:
                name: service
                port:
                  number: 80
            path: /a/bbb
            pathType: Prefix
          - backend:
              service:
                name: service
                port:
                  number: 80
            path: /b/xxx
            pathType: Prefix
          - backend:
              service:
                name: service
                port:
                  number: 80
            path: /b/yyy
            pathType: Prefix
```

### Actual behavior

The overlay is not only not applied when the profile is used and what it does generate has two root paths.

```yaml
rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: service
                port:
                  name: http
            path: /
            pathType: Prefix
          - backend:
              service:
                name: service
                port:
                  name: http
            path: /
            pathType: Prefix
```

### How to Reproduce?

1. Run `mvn package -DskipTests -Prelease` (this will apply the Quarkus "kubernetes" profile)
2. Review `/target/kubernetes/kubernetes.yml` - Ingress overlay is not there when using 2.14 but is when using 2.13

[2.14-not-working.zip](https://github.com/quarkusio/quarkus/files/9998170/2.14-not-working.zip)

[2.13-working.zip](https://github.com/quarkusio/quarkus/files/9998180/2.13-working.zip)

### Output of `java -version`

JDK 17

### Quarkus version or git rev

2.14.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8

### Additional information

It would also be nice to be able to set the `spec.ingressClassName` in the application.yml too.

**Comment by geoand** [comment]
@Sgitario can you take a look please?

Thanks

**Comment by Sgitario** [comment]
This issue is a consequence of using the latest Fabric8 Kubernetes Client 6.x. To be precise, now you need to provide the `apiVersion` of the resource (see more here: https://github.com/fabric8io/kubernetes-client/blob/master/doc/MIGRATION-v6.md#deserialization-resolution). 

Therefore, to fix this issue, you need to add this line `apiVersion: networking.k8s.io/v1` in your `service/src/main/kubernetes/kubernetes.yml` file and now everything will work as expected. @kjq can you confirm if this is now working fine for you?

We should add a note about this in the migration guide for Quarkus 2.14. @geoand, wdyt ?

**Comment by geoand** [comment]
> We should add a note about this in the migration guide for Quarkus 2.14. @geoand, wdyt ?

Absolutely

**Comment by iocanel** [comment]
Came to say that this doesn't seem to be related in a way with the profiles, but @Sgitario has given a more specific response.

**Comment by kjq** [comment]
I can verify adding that line works recognizes the manifest but it still adds a root path which may muck with a catch-all rule in another service under the same ALB.

```yaml
- backend:
    service:
      name: service
      port:
        name: http
  path: /
  pathType: Prefix
```
**BUT...**

Trying out the new ingress rules and it merged every file under the `/kubernetes` folder to the generated manigest regardless of profile or filename (in my case there could be a `kubernetes.yml` and `minikube.yml` but in the reproducer they were just named k8s1.yml and k8s2.yml).   

Removing the files completely and only he ingress rules are used but now it produce two root paths:

```yaml
http:
  paths:
    - backend:
        service:
          name: service
          port:
            name: http
      path: /
      pathType: Prefix
    - backend:
        service:
          name: service
          port:
            name: http
      path: /
      pathType: Prefix
    - backend:
        service:
          name: service
          port:
            name: http
      path: /aaa
      pathType: Prefix
    - backend:
        service:
          name: service
          port:
            name: http
      path: /bbb
      pathType: Prefix
```

[reproducer1.zip](https://github.com/quarkusio/quarkus/files/10002619/reproducer1.zip)

**Comment by Sgitario** [comment]
> I can verify adding that `apiVersion` to the custom manifest works - it applies it but it adds a root path which may muck with a catch-all rule in another service under the same ALB.
> 
> ```yaml
> - backend:
>     service:
>       name: service
>       port:
>         name: http
>   path: /
>   pathType: Prefix
> ```

I think this is the expected behaviour as it's the default path of a Quarkus application. You can configure this rule by setting the property: `quarkus.kubernetes.ports.http.path=<THE NEW PATH>` (by default, this value is '\'). More info in [this link](https://quarkus.io/guides/deploying-to-kubernetes#adding-ingress-rules).

About the problem of the duplciated Ingress path rules, the problem is that there are two modules in the reproducer and somehow it generates two path rules. This is a Quarkus issue that needs fixing.

**Comment by kjq** [comment]
Yes, the multiple "paths" would be an issue - we have many modules, not all services but potentially contributing configuration to the services.

As for the path, it is not that I want to change the base path.  I just dont want it as an ingress rule for prefix matching.  We deploy all of the services into a single ALB with target groups bound to the prefix that way they can co-exists, in this case it is an AWS ALB.  We have a catch-all ingress if none of the service paths match. (/a/*, /b/* - no match go to this service for /*)

**Comment by kjq** [comment]
What about it blindly merging "any" files in the Kubernetes folder even if they don't match a profile name?

>About the problem of the duplciated Ingress path rules, the problem is that there are two modules in the reproducer and somehow it generates two path rules. This is a Quarkus issue that needs fixing.

**Comment by Sgitario** [comment]
The property `quarkus.kubernetes.ports.http.path=/x` is only used to set the default ingress rule path, so I don't see any side effects. Anyway, @iocanel to confirm. 

Your custom ingress rules configuration can then be replaced with the following configuration:

```yaml
quarkus:
  kubernetes:
    ports:
      "http":
        path: /a/aaa
    ingress:
      expose: true
      rules:
        "1":
          path: /a/bbb
          host: ${quarkus.kubernetes.ingress.host}
        "2":
          path: /servicea/hello
          host: ${quarkus.kubernetes.ingress.host}
...
```
