### ISSUE TITLE
Kubernetes extension generates two Ingress rules

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#29303]
### Describe the bug

When using the Kubernetes extension and enabling the Ingress generation via `quarkus.kubernetes.ingress.expose=true`, two rules are created.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 52f15a78928c479a0ba55baf10c28412185591a5
    app.quarkus.io/build-timestamp: 2022-11-16 - 12:39:45 +0000
  labels:
    app.kubernetes.io/name: test-k8s
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: test-k8s
                port:
                  name: http
            path: /
            pathType: Prefix
          - backend:
              service:
                name: test-k8s
                port:
                  name: http
            path: /
            pathType: Prefix
``` 

### Expected behavior

Only one rule should be created.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/commit-id: 52f15a78928c479a0ba55baf10c28412185591a5
    app.quarkus.io/build-timestamp: 2022-11-16 - 12:39:45 +0000
  labels:
    app.kubernetes.io/name: test-k8s
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: test-k8s
                port:
                  name: http
            path: /
            pathType: Prefix
``` 

### Output of `uname -a` or `ver`

Ubuntu 22.04

### Output of `java -version`

17

### Quarkus version or git rev

2.14.0.Final
