### ISSUE TITLE
The configuration quarkus.smallrye-openapi.servers ignores the order in the swagger ui

### ISSUE THREAD

**Issue by wlybe** [quarkusio/quarkus#29444]
### Describe the bug

Setting servers on the application properties is randomly ordered.

These two settings show the servers in the same order on the swagger ui:

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: https://my.produciton.org, http://localhost:8080
```

or

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: http://localhost:8080, https://my.produciton.org
```
Maybe this is because on application.properties or application.yaml: quarkus.smallrye-openapi.servers is types java.util.Set<String>. on openapi.yaml, server: array (and not a set)

### Expected behavior

https://my.produciton.org appears first on the list in SwaggerUI with this configuration

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: https://my.produciton.org, http://localhost:8080
```

http://localhost:8080 appears first on the list in SwaggerUI with this configuration

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: http://localhost:8080, https://my.produciton.org
```

### Actual behavior

These two settings show the servers in the same order on the swagger ui:

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: https://my.produciton.org, http://localhost:8080
```

or

```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: http://localhost:8080, https://my.produciton.org
```

### How to Reproduce?

1. add this configuration to application.yaml
```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: https://my.produciton.org, http://localhost:8080
```
2. open the swagger UI
3. Do the same by changing the servers
```yaml
%dev:
  quar:kus:
    smallrye-openapi:
      servers: https://my.produciton.org, http://localhost:8080
```
4. On swaggerUI, the servers order do not change

### Output of `java -version`

openjdk 11.0.17 2022-10-18 LTS

### Quarkus version or git rev

2.14.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6
