### ISSUE TITLE
Support `ISO8601` string value for date format

### ISSUE THREAD

**Issue by x80486** [quarkusio/quarkus#29937]
### Description

Currently, there are several places where the logging configuration is done:

```yaml
quarkus:
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} |- %-5p in %c:%L [%t] - %m%e%n"
      json:
        date-format: "yyyy-MM-dd HH:mm:ss,SSS"
        exception-output-type: detailed_and_formatted
```

It's not a big deal to configure the format as desired, but there is this (super-cool I would say) abbreviation that `Logback` [uses](https://logback.qos.ch/manual/layouts.html#date) to refer to well-known formats.

For those cases where a `logback.xml` (or any other supported logging framework) configuration file is not used, but the built-in `Quarkus` configuration, it would be great if `ISO8601` (or a similar string value) is supported — and probably some other widely recognized formats.

### Implementation ideas

N/A
