### ISSUE TITLE
GraphQL federation directives do not appear in the schema

### ISSUE THREAD

**Issue by alexpoletaev** [quarkusio/quarkus#30129]
### Describe the bug

Once federation annotations are set in the code and Apollo federation is enabled in the config, the federation specific directives must appear in the graphql schema

### Expected behavior

GraphQL federation directives are visible in the schema

### Actual behavior

GraphQL federation directives do not appear in the schema

### How to Reproduce?

Reproducer: [quarkus-graphql-issue.zip](https://github.com/quarkusio/quarkus/files/10333185/quarkus-graphql-issue.zip)

- unzip a reproducer
- start service
- go to graphql UI
- execute next query:
`query {
  _service {
    sdl
  }
}`
- observe that no federation directives present in the graphql schema

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

2.15.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

### Additional information

A workaround: index smallrye module manually and federation directives will appear in the schema:
```
quarkus:
  index-dependency:
    "smallrye-graphql-api":
      group-id: io.smallrye
      artifact-id: smallrye-graphql-api
```
