### ISSUE TITLE
Docs: Briefly explain how Configuration via K8s ConfigMap works

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#305]
The [Kubernetes Guide](../blob/master/docs/src/main/asciidoc/kubernetes-guide.adoc#going-further) alludes to _"the configuration support allows mounting the application configuration using config map",_ and while reading the doc for the first time it would have seemed useful to me to have a paragraph in the [Configuration Guide](../blob/master/docs/src/main/asciidoc/application-configuration-guide.adoc) at least briefly elaborating on that? E.g. how do you have to name the ConfigMap and what not...

What would be REALLY cool for bonus points would be an IT in the protean-quickstarts/application-configuration which actually illustrates and exercises this. Not sure how to write an IT for k8s, but AFAIK there was some stuff in Arquillian and/or fabric8 somewhere for this? (I wasn't around at the time.)

**Comment by csotiriou** [comment]
Is there any update to this? I am scratching my head on how this can work, the smallrye microprofile config also does not have any definitive solution/documentation for this.

**Comment by owennewo** [comment]
I can stitch a solution together but docs would be helpful.

Here are my thoughts/solution
- quarkus main config story is application.properties typically found in src/main/resources.  This file gets copied into package jar (or embedded in graal binary)
- quarkus has an undocumented feature that prefers to use an external properties file workingdir/config/application.properties if present
- the Dockerfile.jvm's working dir (by default) is '/deployments' 
- the Dockerfile.native's working dir is '/work'
- if you use standard kubernetes volume mounts you can mount a kubenetes secret or configmap 'in the right place' for quarkus i.e. /deployments/config/application.properties or /work/config/application.properties
- the properties are layered e.g. you only need to override properties that are different

Example configmap
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: quarkus-config
data:
  application.properties: |-
    greeting.message=Overriden message
```
Example deployment

```
apiVersion: extensions/v1beta1                                      
kind: Deployment                                                    
metadata:                                                           
  labels:                                                           
    app: quarkus-websockets                                         
  name: quarkus-websockets                                          
spec:                                                               
  replicas: 1                                                       
  selector:                                                         
    matchLabels:                                                    
      app: quarkus-websockets                                       
  template:                                                         
    metadata:                                                       
      labels:                                                       
        app: quarkus-websockets                                     
    spec:                                                           
      containers:                                                   
      - image: XXXXXXX/quarkus-websocket:latest
        imagePullPolicy: Always                                     
        name: quarkus-websockets                                    
        volumeMounts:                                               
        - name: quarkus-config-volume                               
          mountPath: /deployments/config                            
      restartPolicy: Always                                         
      volumes:                                                      
        - name: quarkus-config-volume                               
          configMap:                                                
            name: quarkus-config

```
