### ISSUE TITLE
HTTPS protocol for health probe in kubernetes.yml when using Alpha5 and Alpha6

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#31854]
### Describe the bug

#31764

When upgrading from Alpha4 to Alpha5 or Alpha6 the wrong protocol (HTTPS) is used for health probe.
This causes the following error : 

Readiness probe failed: Get "https://10.8.22.154:8080/q/health/ready": http: server gave HTTP response to HTTPS client

Kubernetes when shutdown the container as expected

### Expected behavior

HTTP protocol should be used as for Alpha4 : 

```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

### Actual behavior

```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

### Quarkus version or git rev

3.0.0 Alpha5

**Comment by amoscatelli** [comment]
Sorry but I get several "Could not resolve dependencies" when building main ... maybe there is some issue in the dependency tree

**Comment by geoand** [comment]
You can build Quarkus from `main` using `mvn -T C1 -Dquickly -Dformat.skip=true`.

Then in your application use the following Maven properties for the Quarkus BOM:

```xml
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>999-SNAPSHOT</quarkus.platform.version>
```

**Comment by amoscatelli** [comment]
I confirm Alpha6 fixes the issue !
Thank you everybody

**Comment by geoand** [comment]
Thanks for the update!

**Comment by amoscatelli** [comment]
Guys this happened again !!?

```
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /greetings/q/health/live
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
```

Sometimes this happens sometimes and something doesn't !
I simply redeployed !
