### ISSUE TITLE
K8s extension with customization doesn't generate `spec.template.metadata` when it's not customized.

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#31968]
### Describe the bug

The Kubernetes extension doesn't generate `spec.template.metadata` (including the required `labels`) when a customization is provided that doesn't customize the `spec.template.metadata` key.

Using a customization like the following, to add a CSI volume, produces no `spec.template.metadata`.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector: {}
  template:
    spec:
      containers: [ ]
      volumes:
      - name: tls
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: local-tls
            csi.cert-manager.io/issuer-kind: ClusterIssuer
            csi.cert-manager.io/common-name: my-app.default.svc.cluster.local
            csi.cert-manager.io/dns-names: my-app,my-app.default,my-app.default.svc,my-app.default.svc.cluster.local
```

### Expected behavior

`spec.template.metadata` is generated correctly even when the deployment is customized

### Actual behavior

`spec.template.metadata` is generated correctly.

### How to Reproduce?

1. Add `kubernetes` extension
2. Add a `src/main/kubernetes/kubernetes.yml` with contents like the above.
3. Build the project and view the generated `kubernetes.yml`.

### Output of `uname -a` or `ver`

macOS 13.2.1

### Output of `java -version`

java version "17.0.2" 2022-01-18 LTS
Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### Quarkus version or git rev

2.16.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1
