### ISSUE TITLE
+5ms delay in RESTEasy Reactive endpoint before first line of code called

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#32168]
### Describe the bug

In our application we're seeing a 6-8ms delay before the first line of our business logic code is called in OTEL spans:
![image](https://user-images.githubusercontent.com/26604994/228048340-e902c6b2-9d30-46a3-bd02-ab3b6b7fa3f6.png)

On a fresh Quarkus app, with the below code, I can see about a 1.5-2.0ms delay before `hello()` is called:
![image](https://user-images.githubusercontent.com/26604994/228048603-e9f5c95c-8be9-4427-9f9f-ffe47647b4be.png)

Is there any way to debug/get visibility into what is happening in the "dead space" before user code is invoked?
Thank you 🙏 

```java
@Path("/hello")
public class GreetingResource {

    @Inject
    Tracer tracer;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return withSpan("hello", tracer, span -> {
            span.setAttribute("hello", "world");
            return withSpan("goodbye", tracer, span2 -> {
                span2.setAttribute("goodbye", "world");
                return "hello";
            });
        });
    }

    private static <T> T withSpan(String name, Tracer tracer, Function<Span, T> function) {
        Span span = tracer.spanBuilder(name).startSpan();
        try (Scope scope = span.makeCurrent()) {
            return function.apply(span);
        } finally {
            span.end();
        }
    }
}
```

### Output of `uname -a` or `ver`

Fedora 38 on WSL2

### Output of `java -version`

17

### Quarkus version or git rev

2.16.5.Final

**Comment by GavinRay97** [comment]
Heya, thanks for getting back to me Georgios.

Let me share a simple setup for this below.

Mostly curious if it's possible to profile/trace what is happening before the user code happens to see what is taking the time before user code is invoked, because it's difficult to optimize without this info 🙏 

![image](https://user-images.githubusercontent.com/26604994/228569044-1ae14369-2495-41dc-91a3-ff1460152568.png)

---

- Docker Compose
```yaml
version: "3.7"

services:
    jaeger:
        image: jaegertracing/all-in-one:latest
        restart: always
        ports:
            - 5775:5775/udp
            - 6831:6831/udp
            - 6832:6832/udp
            - 5778:5778
            - 16686:16686
            - 14250:14250
            - 14268:14268
            - 14269:14269
            - 4317:4317 # OTLP gRPC
            - 4318:4318 # OTLP HTTP
            - 9411:9411
        environment:
            COLLECTOR_OTLP_ENABLED: "true"
```

- application.properties
```properties
quarkus.application.name=myservice 
quarkus.opentelemetry.enabled=true 
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://localhost:4317 
````
- Dependencies
```kts
implementation("io.quarkus:quarkus-opentelemetry")
```
