### ISSUE TITLE
Client ID and Secret not passed to refresh

### ISSUE THREAD

**Issue by jhaakma** [quarkusio/quarkus#32282]
### Describe the bug

With OAuth2, the refresh_token endpoint may require client-id and client-secret:https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/ 

With the current implementation of oidc-client, the refresh_token call only includes the refresh_token. There is no configuration to change this behaviour.

OidcClientRecorder is hardcoded to construct an OidcClientImpl with a `commonRefreshGrantParams` containing only the grant type: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L186 

OidcClientImpl is then hardcoded to only add the refresh_token: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java#L80

### Expected behavior

When using `oidc-client` for Oauth2 authentication, and there is a refresh_token available, it should call the refresh_token endpoint with the client-id and client-secret and return a new set of tokens.

### Actual behavior

The refesh_token endpoint returns a `401 unauthenticated` status code.

### Quarkus version or git rev

2.13.5.Final

**Comment by sberyozkin** [comment]
@jhaakma My initial thinking is that this issue is invalid, the refreshTokens call ends up here, https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java#L134, where the client authentication is done, id and secret are passed as Basic credentials, or as form post parameters or a JWT authentication token is created, can you please show your configuration ? 
Also are you sure 401 is returned because no secret is submitted, can you trace the call ?

**Comment by sberyozkin** [comment]
We have refresh token grant tests for OidcClient, https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/src/main/resources/application.properties (note the secret), and https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java#L131

**Comment by jhaakma** [comment]
Thanks @sberyozkin, I probably have something messed up in my configuration. Not sure what though, I have `client-id` and `credentials.secret` configured for the given client. 

Here's my configuration, using a named client:

```yaml
quarkus:
  oidc-client:
    #disable default 
    client-enabled: false
    authorisation_code:
      auth-server-url: ${AUTH_SERVER_URL}
      token-path: /token
      discovery-enabled: false
      grant:
        type: password
      grant-options:
        password:
          username: ${USERNAME}
          password: ${PASSWORD}
          client_id: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
      client_id: ${CLIENT_ID}
      credentials:
        client_secret: ${CLIENT_SECRET}
```

> Also are you sure 401 is returned because no secret is submitted, can you trace the call ?

I've traced the call and can see the http request being made with no client-id and secret. Making the identical call with those credentials gives me a 200 response.
