### ISSUE TITLE
When adding a custom Knative Service using the same name of the app, it does not get merged, but duplicated

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#32345]
### Describe the bug

Given a project called "example", when adding a custom Knative Service in `src/main/kubernetes/common.yml`: 

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example
spec:
  template:
    spec:
      containers:
        - livenessProbe:
            httpGet:
              port: 8888
```

The generated `knative.yaml` contains now two Knative service with the same "example" name:

```yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-03 - 06:09:21 +0000
    app.quarkus.io/commit-id: 9a4b067181a8abec86343eaa8fc9613463f0e4e4
  labels:
    app.kubernetes.io/name: quarkus-helm-integration-tests-knative-minimal
    app.kubernetes.io/version: 1.0.2-SNAPSHOT
  name: example
spec:
  template:
    spec:
      containers:
        - image: ...
          imagePullPolicy: Always
          name: quarkus-helm-integration-tests-knative-minimal
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-03 - 06:09:21 +0000
    app.quarkus.io/commit-id: 9a4b067181a8abec86343eaa8fc9613463f0e4e4
  labels:
    app.kubernetes.io/name: quarkus-helm-integration-tests-knative-minimal
    app.kubernetes.io/version: 1.0.2-SNAPSHOT
  name: example
spec:
  template:
    spec:
      containers:
        - livenessProbe:
            httpGet:
              port: null
              scheme: HTTP

``` 

### Expected behavior

The provided Knative Service "example" should be merged into the generated Knative Service.
