### ISSUE TITLE
The `port` field is not set in Knative manifests

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#32347]
### Describe the bug

Given a Quarkus application that includes the Quarkus Kubernetes and Smallrye Heatlh extensions, when generating the Knative manifests:

```
quarkus.kubernetes.deployment-target=knative
```

The generated Knative service does not set the `port` in the probes:

```yaml
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  ...
  name: example
spec:
  template:
    spec:
      containers:
        - image: ...
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: example
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: null
              scheme: HTTP
```

For Kubernetes deployment, the `port` is set in the `Deployment` resources as expected.

Also, adding the property `quarkus.knative.liveness-probe.http-action-port=8888` does not seem to take any effect.
