### ISSUE TITLE
S3 Extension has problems using localstack and us-east-1 but not us-east-2 

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#32434]
### Describe the bug

This may or may not be an issue with the AWS extension, specifically S3, but I just worked through a scenario with LocalStack where for some reason using `us-east-1` was failing to create a bucket because it was passing over (or not) the `content-length`.

Switching the localstack test to use `us-east-2` instead of `us-east-1` resolved the issue.

I have not checked but the folks over at localstack thought maybe the AWS client was out of date.

This only was failing on the CI side and these were the settings that worked.

```
.java_e2e_services:
  services:
    - name: localstack/localstack
      alias: localstack
  variables:
    AWS_ACCESS_KEY_ID: test
    AWS_REGION: us-east-2
    AWS_SECRET_ACCESS_KEY: test
    CI_DEBUG_SERVICES: "true"
    DEBUG: 1
    FORCE_NONINTERACTIVE: "true"
    LS_LOG: trace
    LOCALSTACK_HOST: localstack
    SERVICES: s3
    SKIP_E2E_TESTS: "false"
    _TEST_QUARKUS_S3_ENDPOINT_OVERRIDE: http://localstack:4566
    _TEST_QUARKUS_S3_PATH_STYLE_ACCESS: "true"
```

Code-wise, the settings looked like this.

```
quarkus:
  s3:
    aws:
      region: ${AWS_REGION:us-east-2}
      credentials:
        type: static
        static-provider:
          access-key-id: test
          secret-access-key: test

"%test":
  quarkus:
    s3:
      endpoint-override: http://s3.localhost.localstack.cloud:4566
```

For reference: 
- [Slack Conversation](https://github.com/localstack/localstack/issues/8073)
- [GitHub Ticket](https://localstack-community.slack.com/archives/CMAFN2KSP/p1680654627768269)

### Expected behavior

Creating a bucket regardless of region would work especially since it worked on an older version.

### Actual behavior

Scenarios:
- Locally using v2.x of LocalStack works
- In CI, using v1.4 of LocalStack works
- In CI, using v2.x of LocalStack does not work using `us-east-1` but does using `us-east-2`

### Quarkus version or git rev

2.16.5.Final

### Additional information

This may not even be related to the extension or S3 client but just thought I would raise it in case anyone else comes across it.
