### ISSUE TITLE
Generating Role or ClusterRole resources with empty API group property produces invalid manifests

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#32519]
### Describe the bug

When generating a Role or a ClusterRole resource like:
```
quarkus.kubernetes.rbac.cluster-roles.secret-reader.policy-rules.0.resources=secrets
quarkus.kubernetes.rbac.cluster-roles.secret-reader.policy-rules.0.verbs=get,watch,list
```

Produces the following resource:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
  - resources:
      - secrets
    verbs:
      - get
      - watch
      - list
```

This is invalid because the `apiGroups` field in the rule is mandatory and it's not added by default (because it's null). 

### Expected behavior

When users do not set the `api-groups`, it should use a list with an empty element, to produce:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
  - resources:
      - secrets
    apiGroups: [""]
    verbs:
      - get
      - watch
      - list
```

More context in this comment: https://github.com/quarkusio/quarkus/pull/31797#issuecomment-1497311563
