### ISSUE TITLE
Kubernetes - RBAC ClusterRoleBinding not generating correctly?

### ISSUE THREAD

**Issue by zZHorizonZz** [quarkusio/quarkus#32572]
### Describe the bug

I'm trying to setup the configuration so that the final kubernetes config contains ClusterRoleBinding and not RoleBinding, I have found out this  [quarkus.kubernetes.rbac.role-bindings."role-bindings".cluster-wide](https://quarkus.io/version/main/guides/deploying-to-kubernetes#quarkus-kubernetes-kubernetes-config_quarkus.kubernetes.rbac.role-bindings.-role-bindings-.cluster-wide) but I'm not sure if that should ensure that ClusterRoleBinding is generated or if just that ClusterRole is generated.

Config:
```properties
#Role Config
quarkus.kubernetes.rbac.cluster-roles.conductor-cluster-role.policy-rules.0.api-groups=extensions,apps
quarkus.kubernetes.rbac.cluster-roles.conductor-cluster-role.policy-rules.0.resources=deployments,pods,namespaces
quarkus.kubernetes.rbac.cluster-roles.conductor-cluster-role.policy-rules.0.verbs=get,list,watch,create,update,patch,delete

#Service Account
quarkus.kubernetes.rbac.service-accounts.conductor-service-account.name=conductor-service-account
quarkus.kubernetes.rbac.service-accounts.conductor-service-account.namespace=default
quarkus.kubernetes.rbac.service-accounts.conductor-service-account.use-as-default=true

#Role Binding
quarkus.kubernetes.rbac.role-bindings.conductor-cluster-role-binding.subjects.conductor-service-account.kind=ServiceAccount
quarkus.kubernetes.rbac.role-bindings.conductor-cluster-role-binding.subjects.conductor-service-account.namespace=default
quarkus.kubernetes.rbac.role-bindings.conductor-cluster-role-binding.role-name=conductor-cluster-role
quarkus.kubernetes.rbac.role-bindings.conductor-cluster-role-binding.cluster-wide=true
```

### Expected behavior

I don't really know if this is expected behavior or not since on one hand after looking through code from #31797 I didn't find any mentions of ClusterRoleBinding but on the other hand, I don't see anything changing after setting cluster-wide to true so that could be a forgotten part of code?

### Actual behavior

Current config:

```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: conductor-cluster-role
rules:
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - pods
      - namespaces
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: conductor-cluster-role-binding
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: conductor-cluster-role
subjects:
  - kind: ServiceAccount
    name: conductor-service-account
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: conductor-service-account
  namespace: default
```

### How to Reproduce?

Try creating and then building the project with the already mentioned config.

### Output of `java -version`

java version "17.0.5" 2022-10-18 LTS

### Quarkus version or git rev

3.0.0.Beta1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

### Additional information

Because of the issue mentioned in #32499 I'm not currently able to use CR2 (Waiting on Final).
