### ISSUE TITLE
[Extension Proposal] Rate Limiter

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#32582]
### Description

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

I have a proof of concept based on bucket4J:

https://github.com/rmanibus/quarkus-rate-limiter

here is a first draft of the API that would be exposed by this extension:

```yaml
quarkus:
  rate-limiter:
    limits:
      group1:
        burst-protection:
          max-usage: 10
          duration: 1S
        fair-use:
          max-usage: 100
          duration: 5m
```
```java
@RateLimited(limitsKey = "group1")
void limitedMethod()
```
if multiple methods share the same limits key, user should be able to either share or isolate buckets for those methods.

Segmentation Key:
- UNSEGMENTED: the limit is shared for all the incoming trafic
- SEGMENT_BY_IP: one bucket is created per IP address, should throw if request context is not enabled
- CUSTOM: should allow a user defined segmentation method, working with CDI (use case: segment by user id)

Bucket registry:
Local for now, but network registry should be supported in the future (hazelcast, redis ...)

### Repository name

quarkus-rate-limiter

### Short description

Rate Limiter for quarkus framework

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/<REPOSITORY_NAME>/dev/

### Repository Topics

- quarkus-extension
- 
...

### Team Members

- rmanibus
feel free to reach out if you want to contribute
