### ISSUE TITLE
Kubernetes Service Binding doesn't work with PostgresCluster

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#32773]
### Describe the bug

I deploy app using OpenShift extension and Kubernetes Service Binding extension together with CrunchyData Postgres, however OC secret is never mounted to pod and `SERVICE_BINDING_ROOT` environment variable is not set, so datasource is not configured and pod crashes. IMO regression as steps to reproduce works with 2.16.6.Final.

### Expected behavior

Same as with 2.16.6, the service binding root is set and secret with datasource configuration is mounted.

### Actual behavior

Pod crash as data source is not configured
```
Model classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.
```

### How to Reproduce?

Steps to reproduce:

0. 
```
export quarkus_version='999-SNAPSHOT' && export quarks_grp='io.quarkus' && export quarkus_stream='3.0'
```
and you will need sb operator
1. `oc new-project mvavrik-sb-debug`
2. 
```
cat <<'EOF' >>pg-cluster.yml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgresql
  namespace: mvavrik-sb-debug
spec:
  openshift: true
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.2-1
  postgresVersion: 14
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 150Mi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 150Mi
EOF
```
4. `oc apply -f ./pg-cluster.yml` 
5. `oc -n mvavrik-sb-debug wait --for condition=Ready --timeout=300s pods --all`
6. `quarkus create app --extension openshift,resteasy-reactive,hibernate-orm-panache,jdbc-postgresql,kubernetes-service-binding --stream=$quarkus_stream`
7. `cd code-with-quarkus`
8. 
```
cat <<'EOF' >>src/main/resources/application.properties
quarkus.kubernetes-service-binding.services.postgresql.api-version=postgres-operator.crunchydata.com/v1beta1
quarkus.kubernetes-service-binding.services.postgresql.kind=PostgresCluster
quarkus.kubernetes-service-binding.services.postgresql.name=postgresql
quarkus.datasource.db-kind=postgresql
quarkus.openshift.route.expose=true
quarkus.kubernetes.deployment-target=openshift
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.deploy=true
EOF
```
10. `mvn clean install -Dquarkus.platform.group-id=$quarks_grp -Dquarkus.platform.version=$quarkus_version -DskipTests`
11. `oc get pod -o wide`
12. `oc delete project mvavrik-sb-debug`
13. `cd ..`
14. `rm code-with-quarkus/ -r`

Deployment and running is successful if you replace first step with:
`export quarkus_version='2.16.6.Final' && export quarks_grp='io.quarkus.platform' && export quarkus_stream='2.16'`

### Output of `uname -a` or `ver`

Fedora

### Output of `java -version`

openjdk 11.0.18 2023-01-17 OpenJDK Runtime Environment Temurin-11.0.18+10 (build 11.0.18+10) OpenJDK 64-Bit Server VM Temurin-11.0.18+10 (build 11.0.18+10, mixed mode)

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

### Additional information

```
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: code-with-quarkus-postgresql
spec:
  application:
    group: apps.openshift.io
    name: code-with-quarkus
    version: v1
    kind: DeploymentConfig
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgresql
  detectBindingResources: false
  bindAsFiles: true
---
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name: code-with-quarkus-postgresql
spec:
  application:
    group: apps.openshift.io
    name: code-with-quarkus
    version: v1
    kind: DeploymentConfig
  services:
    - group: postgres-operator.crunchydata.com
      version: v1beta1
      kind: PostgresCluster
      name: postgresql
  detectBindingResources: false
  bindAsFiles: true
```
