### ISSUE TITLE
Create a DevService for the mailer extension

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#32894]
### Description

It would be great if I could experiment with the mail sender without spamming emails through an actual provider. A DevService could possibly help.

Other DevServices might be able to benefit from this too. Out of my mind I can think of Keycloak that could use something like it.

**Comment by geoand** [comment]
I think this has been proposed before, but I can't seem to find it

**Comment by melloware** [comment]
This would be cool it could start up MailHog which has a great web UI for inspecting emails sent during DEV mode.

https://github.com/mailhog/MailHog

```yml
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mail
    logging:
      driver: 'none' # disable saving logs
    volumes:
      - 'mail_data:/var/opt/mail'
    ports:
      - '1025:1025' # smtp server
      - '8025:8025' # web ui
 ```

I guess it could technically use GreenMail as well which is a pure java based Mail Server.

https://greenmail-mail-test.github.io/greenmail/
