### ISSUE TITLE
Kubernetes initContainers volume mount support

### ISSUE THREAD

**Issue by mostafacs** [quarkusio/quarkus#32891]
### Description

I want to mount a volume to init container to edit permission like this:
```
initContainers:
        - name: volumes-init
          image: alpine
          command:
            - chown
            - -R
            - 65534:65534
            - /data
          volumeMounts:
            - name: data
              mountPath: /data
```
possible configuration from the quarkus kubernetes extension not support mounting volume on the initContainers.

**Comment by Sgitario** [comment]
Adding volume mounts in `init-containers` is already supported. 
Have you tried the following configuration:
```
quarkus.kubernetes.init-containers.volumes-init.image=alpine
quarkus.kubernetes.init-containers.volumes-init.command=chown,-R,65534:65534,/data
quarkus.kubernetes.init-containers.volumes-init.mounts.data.path=/data
quarkus.kubernetes.init-containers.volumes-init.mounts.data.read-only=false
```

This generates the following deployment:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-04-26 - 10:45:35 +0000
    app.quarkus.io/commit-id: 4ef3303b6022b42fc51f84dbe3c956b2f0ca1226
  labels:
    app.kubernetes.io/version: 0.1-SNAPSHOT
    app.kubernetes.io/name: kubernetes-with-init-container-volume-mount
    app.kubernetes.io/managed-by: quarkus
  name: kubernetes-with-init-container-volume-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.1-SNAPSHOT
      app.kubernetes.io/name: kubernetes-with-init-container-volume-mount
  template:
    metadata:
      // ...
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: jcarvaja/kubernetes-with-init-container-volume-mount:0.1-SNAPSHOT
          imagePullPolicy: Always
          name: kubernetes-with-init-container-volume-mount
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
            - containerPort: 8080
              name: http
              protocol: TCP
      initContainers:
        - command:
            - chown
            - -R
            - 65534:65534
            - /data
          image: alpine
          imagePullPolicy: IfNotPresent
          name: volumes-init
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: false
```

I'm closing this issue, but feel free to reopen it if you meant something different.
