### ISSUE TITLE
Quarkus with liquibase on Kubernetes

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#33097]
### Describe the bug

Hi - I've noticed when using the Quarkus Kubernetes/OpenShift extension when an app uses MongoDB that there is this new `liquibase-mongodb-init` kubernetes `Job` added.

Why is that, especially if my app has `quarkus.liquibase-mongodb.migrate-at-start=false` set?

when i run `./mvnw clean package -Dquarkus.kubernetes.deployment-target=openshift  -Dquarkus.liquibase-mongodb.migrate-at-start=false` I still see this in the resulting `target/openshift.yml` (note I've removed some things to make it shorter & more readable).

Why do I need that init container if my app doesn't need it? Furthermore, on Openshift 4.12, that `liquibase-mongodb-init` container never actually starts up and causes my entire app not to work.

The image `groundnuty/k8s-wait-for:1.3` seems that the version of `kubctl` is too old.

But in any case, if my app specifies `quarkus.liquibase-mongodb.migrate-at-start=false` why do I even need all this init container stuff?

```yaml
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app.kubernetes.io/name: rest-fights
    app.kubernetes.io/part-of: fights-service
    app.kubernetes.io/version: java17-latest
    app.openshift.io/runtime: quarkus
    app.kubernetes.io/managed-by: quarkus
    system: quarkus-super-heroes
    application: fights-service
    app: rest-fights
  name: rest-fights
spec:
  replicas: 1
  selector:
    app.kubernetes.io/version: java17-latest
    app.kubernetes.io/name: rest-fights
    app.kubernetes.io/part-of: fights-service
  template:
    metadata:
      labels:
        app.kubernetes.io/version: java17-latest
        app.kubernetes.io/name: rest-fights
        app.kubernetes.io/part-of: fights-service
        app.openshift.io/runtime: quarkus
        app.kubernetes.io/managed-by: quarkus
        system: quarkus-super-heroes
        application: fights-service
        app: rest-fights
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LIQUIBASE_MONGODB_ENABLED
              value: "false"
          envFrom:
            - configMapRef:
                name: rest-fights-config
            - secretRef:
                name: rest-fights-config-creds
          image: rest-fights:jaa17-latest
          imagePullPolicy: Always
          name: rest-fights
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            limits:
              memory: 768Mi
            requests:
              memory: 256Mi
      initContainers:
        - args:
            - job
            - liquibase-mongodb-init
          image: groundnuty/k8s-wait-for:1.3
          imagePullPolicy: IfNotPresent
          name: init
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - rest-fights
        from:
          kind: ImageStreamTag
          name: rest-fights:jaa17-latest
      type: ImageChange
---
apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-mongodb-init
spec:
  completionMode: OnFailure
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
            - name: QUARKUS_LIQUIBASE_MONGODB_ENABLED
              value: "true"
          envFrom:
            - configMapRef:
                name: rest-fights-config
            - secretRef:
                name: rest-fights-config-creds
          image: quay.io/quarkus-super-heroes/rest-fights:jaa17-latest
          name: liquibase-mongodb-init
      restartPolicy: OnFailure
```

### How to Reproduce?

1. Clone https://github.com/quarkusio/quarkus-super-heroes
2. `cd` into `rest-fights`
3. Log into an openshift cluster
4. Run 

```bash
./mvnw clean package -DskipTests -Dmaven.compiler.release=17 \
  -Dquarkus.container-image.tag=java17-latest \
  -Dquarkus.liquibase-mongodb.migrate-at-start=false \
  -Dquarkus.kubernetes.deployment-target=openshift \
  -Dquarkus.kubernetes.version=java17-latest \
  -Dquarkus.kubernetes.ingress.expose=true \
  -Dquarkus.kubernetes.resources.limits.memory=768Mi \
  -Dquarkus.kubernetes.resources.requests.memory=256Mi \
  -Dquarkus.openshift.version=java17-latest \
  -Dquarkus.openshift.route.expose=true \
  -Dquarkus.openshift.resources.limits.memory=768Mi \
  -Dquarkus.openshift.resources.requests.memory=256Mi \
  -Dquarkus.kubernetes.deploy=true  \
  -Dquarkus.container-image.group=$(oc project -q) \
  -Dquarkus.container-image.registry= \
  -Dquarkus.profile=openshift-17
```

Notice in `target/kubernetes/openshift.yml` that init container is still there and actually never starts up when deployed.
