### ISSUE TITLE
When using yml to configure kafka, quarkus cannot parse the yml configuration

### ISSUE THREAD

**Issue by lpn666** [quarkusio/quarkus#33298]
### Describe the bug

When using yml to configure kafka, quarkus cannot parse the yml configuration。
here is yml 
![image](https://github.com/quarkusio/quarkus/assets/26716574/e7e7586e-4aaa-4126-a4d0-f6b2e590d33b)

and here is application file
![image](https://github.com/quarkusio/quarkus/assets/26716574/b5b45e3f-40d2-4900-9a17-acc62b428374)
the application can works well , but not the yml.  I got error like this :

`
2023-05-11 17:21:36,324 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (smallrye-kafka-consumer-thread-0) These configurations '["bootstrap.servers", "auto.offset.reset", "group.id"]' were supplied but are not used yet.`
`2023-05-11 17:21:36,380 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (smallrye-kafka-producer-thread-0) These configurations '["bootstrap.servers"]' were supplied but are not used yet.
`
and I tried to put double quotes around the keyword  but it didn't work,same error.
![image](https://github.com/quarkusio/quarkus/assets/26716574/e447987f-d822-4895-8546-a9c9c8c343a2)

### Actual behavior

`
2023-05-11 17:21:36,324 WARN  [org.apa.kaf.cli.con.ConsumerConfig] (smallrye-kafka-consumer-thread-0) These configurations '["bootstrap.servers", "auto.offset.reset", "group.id"]' were supplied but are not used yet.`

`2023-05-11 17:21:36,380 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (smallrye-kafka-producer-thread-0) These configurations '["bootstrap.servers"]' were supplied but are not used yet.
`

### How to Reproduce?

just use a sample quarkus code 
![image](https://github.com/quarkusio/quarkus/assets/26716574/7c85fb00-4211-48a5-aadc-e714f3227478)

### Output of `uname -a` or `ver`

Linux uat144 4.19.90-2107.6.0.0100.oe1.bclinux.x86_64 #1 SMP Wed Dec 1 19:59:44 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

graalvm 17

### GraalVM version (if different from Java)

17

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.8

**Comment by cescoffier** [comment]
Unfortunately the yaml parser is kind of limited. You need to use the full key.

**Comment by lpn666** [comment]
@cescoffier thanks for replying me. Do u mean I need use the application file not the yml, when I code kafka program ?

**Comment by cescoffier** [comment]
@lpn666 No, you can still use yaml, but I don't like the result (my personal taste):

```
mp:
  messaging:
    outgoing:
      words-out:
        topic: words
    incoming:
      words-in:
        topic: words
        auto:
          offset:
            reset: earliest
```

There is another issue with that problem: https://github.com/quarkusio/quarkus/issues/24832.

As you mentioned, I would like to have something like:

```
mp:
  messaging:
    incoming:
      test:
        topic: xxxx
        "auto.offset.reset": earliest
        "schema.registry.url": http://xxxx
```

If I could even drop the quote, that would be even better.

Unfortunately, the Yaml rules and our approach to handle yaml does not allow that yet.
