### ISSUE TITLE
Kubernetes name influenced by the `quarkus.container-image.name` 

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#33554]
### Describe the bug

I have an application. It sets the image name to quarkus.container-image.name=hide-and-seek-${quarkus.application.name}. I didn't expect this to change the name in my kubernetes descriptor:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2023-05-23 - 11:46:15 +0000
    app.quarkus.io/commit-id: 8ebd4faa57246c018ed32642bdc6be234b0e8bfc
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: hide-and-seek-place-service
    app.kubernetes.io/managed-by: quarkus
  name: hide-and-seek-place-service
---
```

According to @iocanel it's not intended and it's a bug

### Expected behavior

Setting `quarkus.container-image.name` should not change the kubernetes names.

### Actual behavior

Setting `quarkus.container-image.name` is used in my kubernetes descriptor (for the names)
