### ISSUE TITLE
Not possible to specify service account for kubernetes liquibase init job

### ISSUE THREAD

**Issue by paloliska** [quarkusio/quarkus#33830]
### Describe the bug

If quarkus service is using specifig service account, deploying of service will fail with error
```
Error from server (Forbidden): jobs.batch "my-service-liquibase-mongodb-init" is forbidden: User "system:serviceaccount:default:default" cannot get resource "jobs" in API group "batch" in the namespace "default"
```

kubernetes.yml:
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-jobs
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-service-view-jobs
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-jobs
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: my-service
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scheme: http
    prometheus.io/port: "8888"
    prometheus.io/path: /q/metrics
    prometheus.io/scrape: "true"
    app.quarkus.io/build-timestamp: 2023-06-05 - 15:40:12 +0000
    app.quarkus.io/commit-id: ****
  labels:
    app.kubernetes.io/name: my-service
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: my-service
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8888
  selector:
    app.kubernetes.io/name: my-service
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scheme: http
    prometheus.io/port: "8888"
    prometheus.io/path: /q/metrics
    prometheus.io/scrape: "true"
    app.quarkus.io/build-timestamp: 2023-06-05 - 15:40:12 +0000
    app.quarkus.io/commit-id: ***
  labels:
    app.kubernetes.io/name: my-service
    app.kubernetes.io/version: 0.1.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: my-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-service
      app.kubernetes.io/version: 0.1.0-SNAPSHOT
  template:
    metadata:
      annotations:
        prometheus.io/scheme: http
        prometheus.io/port: "8888"
        prometheus.io/path: /q/metrics
        prometheus.io/scrape: "true"
        app.quarkus.io/build-timestamp: 2023-06-05 - 15:40:12 +0000
        app.quarkus.io/commit-id: ***
      labels:
        app.kubernetes.io/name: my-service
        app.kubernetes.io/version: 0.1.0-SNAPSHOT
        app.kubernetes.io/managed-by: quarkus
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_LIQUIBASE_MONGODB_ENABLED
              value: "false"
          image: eu.gcr.io/***/my-service:0.1.0-SNAPSHOT
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: my-service
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
            - containerPort: 8443
              name: https
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/started
              port: 8888
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
      initContainers:
        - args:
            - job
            - account-service-liquibase-mongodb-init
          image: groundnuty/k8s-wait-for:1.3
          imagePullPolicy: IfNotPresent
          name: init
---
apiVersion: batch/v1
kind: Job
metadata:
  name: my-service-liquibase-mongodb-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
            - name: QUARKUS_LIQUIBASE_MONGODB_ENABLED
              value: "true"
          image: eu.gcr.io/***/my-service:0.1.0-SNAPSHOT
          name: account-service-liquibase-mongodb-init
      restartPolicy: OnFailure
```

### Expected behavior

service deploy success

### Actual behavior

deploy failed

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (build 17.0.6+10-Ubuntu-0ubuntu122.04) OpenJDK 64-Bit Server VM (build 17.0.6+10-Ubuntu-0ubuntu122.04, mixed mode, sharing)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.1.1

### Additional information

Wil be helpfull if there exist config option to specify service account.

**Comment by geoand** [comment]
@iocanel WDYT?

**Comment by cthiebault** [comment]
It seems that the `ServiceAccount` definition is missing:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: {}
  labels: {}
  name: my-service
```

And you have to specify the service account to use in your Job definition:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: my-service-liquibase-mongodb-init
spec:
  completionMode: NonIndexed
  template:
    metadata: {}
    spec:
      containers:
        - env:
            - name: QUARKUS_INIT_AND_EXIT
              value: "true"
            - name: QUARKUS_LIQUIBASE_MONGODB_ENABLED
              value: "true"
          image: eu.gcr.io/***/my-service:0.1.0-SNAPSHOT
          name: account-service-liquibase-mongodb-init
      restartPolicy: OnFailure
      # ----> this was missing!
      serviceAccountName: my-service
