### ISSUE TITLE
kubernetes extension support RollingUpdate config

### ISSUE THREAD

**Issue by naah69** [quarkusio/quarkus#34047]
### Description

```yaml
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0%
      maxSurge: 100%
```
