### ISSUE TITLE
Kubernetes init-containers ignore pull-policy

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34125]
### Describe the bug

If you configure an init-container with:

```
quarkus.kubernetes.init-containers."kafka-topic-creator".image-pull-policy=always
```

It ends up with:

```
imagePullPolicy: IfNotPresent
```

### Expected behavior

It should used the configured strategy.

### Actual behavior

Even if set to always, it generates:

```
      initContainers:
        - env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka:9092
            - name: KAFKA_TOPICS
              value: "cameras:3,temperatures:3"
          image: quay.io/cescoffi/devnation-2023-kafka-topic-initializer:1.0-SNAPSHOT
          imagePullPolicy: IfNotPresent <--- wrong
          name: kafka-topic-creator
```

### How to Reproduce?

You can create an application with:

```
quarkus.kubernetes.init-containers."kafka-topic-creator".image=quay.io/cescoffi/devnation-2023-kafka-topic-initializer:1.0-SNAPSHOT
quarkus.kubernetes.init-containers."kafka-topic-creator".image-pull-policy=always
quarkus.kubernetes.init-containers."kafka-topic-creator".env.vars.KAFKA_TOPICS=cameras:3,temperatures:3
quarkus.kubernetes.init-containers."kafka-topic-creator".env.vars.KAFKA_BOOTSTRAP_SERVERS=PLAINTEXT://kafka:9092
```

and check that the produced kubernetes descriptor uses `always` as the image pull policy for the init container.
