### ISSUE TITLE
@ConfigMapping behaviour changed in Quarkus 2.16.2

### ISSUE THREAD

**Issue by luce98** [quarkusio/quarkus#34208]
### Describe the bug

We have a project with a configuration as the following in the application.yaml:

```
quarkus:
  mailer:
    username: ${provider-username}
    password: ${provider-password}

...    

provider:
  username: ${provider-api-username}
  password: ${provider-api-password}
```

with a .env for the secrets.
Then we have a configuration class as the following:

```
@ConfigMapping(prefix = "provider")
public interface ProviderProps {

    @NotBlank String username();

    @NotBlank String password();
}
```

When upgrading one of our projects from Quarkus 2.14.2.Final to 2.16.5.Final, something broke.
After looking at the changelog, I see that smallrye-config was upgraded to 2.13.2, in which is present the following change
https://github.com/smallrye/smallrye-config/pull/881
which I believe it is causing the different behaviour.
I don't expect this to be "fixed" because this is probably a right behaviour but maybe a note could be added in the migration guide to pay attention to name .env variables due to possible conflicts.

### Expected behavior

ProviderProps.username() returns the value defined in the .env for provider-api-username.

### Actual behavior

ProviderProps.username() returns the value defined in the .env for provider-username.

### How to Reproduce?

Clone the repository
https://github.com/luce98/quarkus-reproduce-config-issue

1. run the test testConfiguration in class AppConfigTest -> it should pass
2. change quarkus version to 2.16.2
3. run the test again -> it should fail

### Quarkus version or git rev

2.16.2
