### ISSUE TITLE
Quarkus containers should run without Linux capability DAC_OVERRIDE

### ISSUE THREAD

**Issue by dastrobu** [quarkusio/quarkus#34578]
### Description

When building a Quarkus container following the guide https://quarkus.io/guides/getting-started and deploying it to a K8s cluster, I would expect to be able to run it with all capabilities dropped in the security context: 

```yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 10000
          seccompProfile:
            type: RuntimeDefault
```

This is a policy in out K8s cluster. 

The current situation with Quarkus 2 and 3 is that I need to add `DAC_OVERRIDE`. 

```yaml
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - DAC_OVERRIDE
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsUser: 10000
          seccompProfile:
            type: RuntimeDefault
```

Otherwise the container will not start and fail with: 

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: eaccess /usr/local/s2i/run: permission denied: unknown
```

Quarkus default configuration should be adapted to run without DAC_OVERRIDE and a test added to verify this setup. 
Otherwise, I would recommend to document why DAC_OVERRIDE is required to run Quarkus containers.
