### ISSUE TITLE
Quarkus 3.2 hibernate schema validation extremelly slow

### ISSUE THREAD

**Issue by sinattieng** [quarkusio/quarkus#34674]
### Describe the bug

Good morning,

Starting the migration from Quarkus version 2.16.7 to 3.2.0 I'm observing a downgrade (from ms to minute) in terms of hibernate-orm schema validation. My application is based on hibernate+oracle db. I have just migrate my entities from javax.persistence.* to jakarta.persistence.*, none of them is changed. 

Thank you in adavance for the support.

Stefano

**Comment by Sanne** [comment]
Very interesting, thanks for opening the issue.
Do you think we'll reproduce it with any simple model or is there something special in you model?

**Comment by sinattieng** [comment]
What do you mean with "something special"? 
The entities are very simple, I have noticed that every time the schema validations has blocked (stucked than it goes after **minutes**) on the same point, with org.hibernate log level DEBUG I see this:

`2023-07-11 16:47:10,061 DEBUG [org.hibernate.query.named.NamedObjectRepository] (JPA Startup Thread)  Checking named HQL query: OrgVChkPartitionFascByAa.findAll
2023-07-11 16:47:10,062 DEBUG [org.hibernate.orm.query.hql] (JPA Startup Thread)  HQL : SELECT o FROM OrgVChkPartitionFascByAa o
2023-07-11 16:47:10,062 DEBUG [org.hibernate.query.hql.internal.SemanticQueryBuilder] (JPA Startup Thread)  Handling root path - OrgVChkPartitionFascByAa
2023-07-11 16:47:10,062 DEBUG [org.hibernate.orm.query.sqm.ast] (JPA Startup Thread)  SqmStatement Tree :
    -> [select]
      -> [query-spec]
        -> [select]
          -> [selection]
            -> [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
            <- [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
          <- [selection]
        <- [select]
        -> [from]
          -> [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
          <- [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
        <- [from]
      <- [query-spec]
    <- [select]


2023-07-11 16:47:10,063 DEBUG [org.hibernate.query.named.NamedObjectRepository] (JPA Startup Thread)  Checking 0 named SQL queries
`

**Comment by sinattieng** [comment]
I add another very strange scenario, I have this on my application.yaml:

```
  datasource: 
    db-kind: "oracle"
    jdbc:
      driver: "oracle.jdbc.driver.OracleDriver"
  hibernate-orm:
    dialect: "org.hibernate.dialect.OracleDialect"
    packages: "it.eng.parer.fascicolo.jpa"
...
"%dev":
  quarkus:
   http:
     port: 10001
   shutdown:
    timeout: "PT1S"
   hibernate-orm:
     validate-in-dev-mode: false
     database:
       generation: "validate"
```
with this configuration schema validation (locally) took 5 minutes and it has happen that hibernate **drop and create** some tables mapped as entity ! (not all of them only a portion)
