### ISSUE TITLE
quarkus kubernetes: env variable string gets broken down in multiple lines 

### ISSUE THREAD

**Issue by matter-it-does** [quarkusio/quarkus#35281]
### Describe the bug

I have a key available at build time that I want present at runtime on the container.

By setting 
```
export QUARKUS_KUBERNETES_ENV_VARS__KW_PUBLIC_KEY__="-----BEGIN PUBLIC KEY-----#MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5zUzl491rhz1i2vhSqxkkoAKZ0vkcEBn#EUTae1QKlTgYKMggOmNcHbrl1TTLgR3GYeEE6r8XglkkMVEIS+PsnA==#-----END PUBLIC KEY-----"
```

The outcome in kubernetes yaml file is 

```
- name: KW_PUBLIC_KEY
              value: '-----BEGIN PUBLIC KEY-----#MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5zUzl491rhz1i2vhSqxkkoAKZ0vkcEBn#EUTae1QKlTgYKMggOmNcHbrl1TTLgR3GYeEE6r8XglkkMVEIS+PsnA==#-----END
                PUBLIC KEY-----'
```

I.e. extra "\n" after `END`.

In json, it's fine: 

```
}, {
            "name" : "KW_PUBLIC_KEY",
            "value" : "-----BEGIN PUBLIC KEY-----#MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5zUzl491rhz1i2vhSqxkkoAKZ0vkcEBn#EUTae1QKlTgYKMggOmNcHbrl1TTLgR3GYeEE6r8XglkkMVEIS+PsnA==#-----END PUBLIC KEY-----"
          } ],
```

### How to Reproduce?

https://github.com/quarkusio/quarkus/files/12301166/qr_k8s_env_bug.zip 

Run 

```
source ./source.sh &&  mvn package -DskipTests=true
```

observe yaml file. Json is correct!

### Output of `java -version`

17

### Quarkus version or git rev

3.2.3.Final

**Comment by matter-it-does** [comment]
Updates here? I worked around it in the code but would rather not..

**Comment by geoand** [comment]
This is one for @iocanel to look into WRT Dekorate

**Comment by gsmet** [comment]
From a YAML perspective, it's perfectly valid. It's just splitting the string to avoid lines too long.

If you use `yq` to read the thing for instance, you will end up with:

```yaml
- env:
    - name: KUBERNETES_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: KW_PUBLIC_KEY
      value: '-----BEGIN PUBLIC KEY-----#MFYwEAYHKoZIzj0CAQYFK4EEAAoDQgAE5zUzl491rhz1i2vhSqxkkoAKZ0vkcEBn#EUTae1QKlTgYKMggOmNcHbrl1TTLgR3GYeEE6r8XglkkMVEIS+PsnA==#-----END PUBLIC KEY-----'
```
