### ISSUE TITLE
Kubernetes Config Extension: use property names that do not conflict with YAML syntax

### ISSUE THREAD

**Issue by Obirah** [quarkusio/quarkus#35286]
### Description

When using the `kubernetes-config` extension, it is required to configure the property `quarkus.kubernetes-config.secrets.enabled=true` in order to activate the discovery of secrets and the property `quarkus.kubernetes-config.secrets` in order to configure which secrets to discover.

When using YAML configuration only, this would result in invalid YAML syntax:
```
quarkus:
  kubernetes-config:
    enabled: true
    namespace: my-namespace
    secrets:
      enabled: true
      - my-secret
```

In order to avoid that and make the feature work as intended, I currently need to have an additional `application.properties` which specifies `quarkus.kubernetes-config.secrets.enabled=true` next to my `application.yaml`.

### Implementation ideas

Use property names that allow to cleanly define a valid `application.yaml` without the need to have an additional `application.properties` file.

Example:
```
quarkus:
  kubernetes-config:
    enabled: true
    namespace: my-namespace
    secrets:
      enabled: true
      names:
        - my-secret
```

**Comment by Sgitario** [comment]
The right YAML file is:

```yaml
quarkus:
  kubernetes-config:
    enabled: true
    namespace: my-namespace
    secrets.enabled: true
    secrets:
      - my-secret
```

An additional `names` property would make things significantly easier, though it would introduce breaking changes or duplicate properties (if we want to maintain both).

**Comment by Obirah** [comment]
> The right YAML file is:
> 
> ```yaml
> quarkus:
>   kubernetes-config:
>     enabled: true
>     namespace: my-namespace
>     secrets.enabled: true
>     secrets:
>       - my-secret
> ```
> 
> An additional `names` property would make things significantly easier, though it would introduce breaking changes or duplicate properties (if we want to maintain both).

When using that config, I get the following error: `Unrecognized configuration key "quarkus.kubernetes-config."secrets.enabled"" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

**Comment by Obirah** [comment]
> The right YAML file is:
> 
> ```yaml
> quarkus:
>   kubernetes-config:
>     enabled: true
>     namespace: my-namespace
>     secrets.enabled: true
>     secrets:
>       - my-secret
> ```
> 
> An additional `names` property would make things significantly easier, though it would introduce breaking changes or duplicate properties (if we want to maintain both).

When using the proposed configuration, the following error occurs: `Unrecognized configuration key "quarkus.kubernetes-config."secrets.enabled"" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo`

**Comment by Sgitario** [comment]
This might be an issue with the config yaml extension. @radcortez do you know about it or somebody who might help here? 
Reopening.

**Comment by radcortez** [comment]
> This might be an issue with the config yaml extension. @radcortez do you know about it or somebody who might help here?

Not exactly. Please check https://github.com/quarkusio/quarkus/issues/11744.

**Comment by radcortez** [comment]
Close due to #11744 also closed.

**Comment by dmlloyd** [comment]
I think that the original problem got confused with the (incorrect) proposed solution up above. But, the following might work, if I recall correctly how the parsing works:

```yaml
quarkus:
  kubernetes-config:
    enabled: true
    namespace: my-namespace
    secrets:
      enabled: true
      ~:
        - my-secret
```
