### ISSUE TITLE
How support multiple tenant root with hibernate6 ?

### ISSUE THREAD

**Issue by seepine** [quarkusio/quarkus#35424]
## In Springboot
application.yml
```yml
spring:
  jpa:
    properties:
      hibernate:
        multiTenancy: true
        tenant_identifier_resolver: com.example.config.TenantResolver
```
TenantResolver.java
```java
public interface CurrentTenantIdentifierResolver {
        // set tenant value
	String resolveCurrentTenantIdentifier();
   
        // true will query all tenant data
	default boolean isRoot(String tenantId) {
		return false;
	}
}
```

## But in Quarkus 3.x

I can not find how to query ignore tenant like `CurrentTenantIdentifierResolver .isRoot`

application.properties
```properties
quarkus.hibernate-orm.multitenant=DISCRIMINATOR
```

CustomTenantResolver.java
```java
@PersistenceUnitExtension
@RequestScoped
public class CustomTenantResolver implements TenantResolver {

  // what is this ?
  @Override
  public String getDefaultTenantId() {
    return "0";
  }

  @Override
  public String resolveTenantId() {
    return Optional.ofNullable(TenantUtil.getTenantId()).map(Serializable::toString).orElse(null);
  }
}
```

### Implementation ideas

like this

```java
        // true will query all tenant data
	default boolean isRoot(String tenantId) {
		return false;
	}
```
