### ISSUE TITLE
Kubernetes secret not read anymore in 3.3

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#35673]
### Describe the bug

I had an application using:

```
# Kubernetes
%prod.quarkus.kubernetes-config.secrets.enabled=true
quarkus.kubernetes-config.secrets=device-database


# Database
quarkus.hibernate-orm.database.generation=drop-and-create

%prod.quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${database-user}
%prod.quarkus.datasource.password=${database-password}
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://device-database:5432/device-database
```

It was working perfectly in 3.2.0.CR1.

I've updated it to 3.3.1, and the secret is not read anymore.

The secret is the following:

```
kind: Secret
apiVersion: v1
metadata:
  name: device-database
data:
  database-name: ZGV2aWNlLWRhdGFiYXNl
  database-password: ZjdHVHFQcW1nWW5wMkNOQg==
  database-user: dXNlcjJLNA==
type: Opaque
```

### Expected behavior

The values from the secret should be read as before.

### Actual behavior

The secret is not read. 

I can see that the secret permissions are added to the descriptor:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-secrets
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: measure-enrichment-view-secrets
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: view-secrets
subjects:
  - kind: ServiceAccount
    apiGroup: ""
    name: measure-enrichment
```
