### ISSUE TITLE
Support native transports in native executables 

### ISSUE THREAD

**Issue by lucaspouzac** [quarkusio/quarkus#35799]
### Description

As requested in [issue 10095](https://github.com/quarkusio/quarkus/issues/10095), a feature request to track supporting native transport in native executable.

Actually, it's not possible to configure native transport, by example to configure unix socket usage for redis with native build.

```
quarkus:
  vertx:
    prefer-native-transport: true
  redis:
    hosts: unix://[:password@]/domain/docker.sock[?select=db-number]
```

Could you implement this ?
