### ISSUE TITLE
gRPC client: keep-alive-time parameter is ignored

### ISSUE THREAD

**Issue by denysandriyanov** [quarkusio/quarkus#36033]
### Describe the bug

```java
    /**
     * The duration after which a keep alive ping is sent.
     */
    @ConfigItem
    public Optional<Duration> keepAliveTime;
```    

The parameter for gRPC client is ignored. Ping is sent every 10 seconds regardless.

See configuration below:

```yaml
quarkus:
  grpc:
    clients:
      identity-service:
        host: ${AUTH_IDENTITY_SERVICE_GRPC_HOST}
        port: ${AUTH_IDENTITY_SERVICE_GRPC_PORT}
        **keep-alive-time: 1m**
```

Whatever value i set in keep-alive-time if i dump the traffic i see ping wuth 10 seconds interval

### Expected behavior

The frequency of ping is set in the parameter  keep alive 

### Actual behavior

 keep alive  is ignored
