### ISSUE TITLE
Configuration property expressions do not work properly

### ISSUE THREAD

**Issue by JackyAnn** [quarkusio/quarkus#36199]
### Describe the bug

not work
```
quarkus:
  application:
    name: ${name}
    version: ${serviceVersion}
    ui-header: ${name} powered by quarkus
```
<img width="1432" alt="image" src="https://github.com/quarkusio/quarkus/assets/3381801/7e7c2c63-ce8f-4eba-880b-6e84d70c4494">

work properly
```
quarkus:
  application:
    name: ${name}
    version: ${serviceVersion}
    ui-header: ${name}
```
   
<img width="1426" alt="image" src="https://github.com/quarkusio/quarkus/assets/3381801/2a5e2134-9cfa-4f81-bd39-5420eafae3d2">

    
    

### Output of `uname -a` or `ver`

Darwin jackydeMacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "20" 2023-03-21 Java(TM) SE Runtime Environment (build 20+36-2344) Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing)

### Quarkus version or git rev

3.4.1

**Comment by radcortez** [comment]
I was not able to reproduce the described issue. Here is my configuration file:

```yaml
name: my-name
serviceVersion: 999-SNAPSHOT

quarkus:
  application:
    name: ${name}
    version: ${serviceVersion}
    ui-header: ${name} powered by quarkus
```

And DEV-UI:

![Screenshot 2023-09-29 at 15 25 12](https://github.com/quarkusio/quarkus/assets/5796305/e9648769-8803-43e4-aee5-a86c8d589fb7)
