### ISSUE TITLE
Cannot load fixed or default YAML configuration when running native build

### ISSUE THREAD

**Issue by ungaralex** [quarkusio/quarkus#36326]
### Describe the bug

When building a native image using YAML configurations (`application.yml` with `application-prod.yml` for the prod build in this case), Quarkus is not able to load any specific configuration properties that are not configured by setting an environment variable. This includes cases with plain hardcoded values as well as environment variables with fallbacks:
```yaml
my:
  config:
    someConf: 42
    envConfigWithFallback: ${MY_CONFIG:defaultValue}
```

Only if you configure a property with a pure environment variable it works:
```yaml
my:
  config:
    someConf: ${MY_CONFIG}
```

Interestingly enough, all of the above cases work fine when setting Quarkus specific properties under `quarkus: ....`. Only for custom application specific props, the values are not loaded.

The exception given is
```bash
Failed to load config value of type class java.lang.String for: my.config.stringConfig
Failed to load config value of type int for: my.config.intConfig
```

### Expected behavior

Quarkus application configuration with the `io.quarkus:quarkus-config-yaml` extension should be able to load all configuration properties of the following cases:
```yaml
my:
  config:
    someConf: 42
    envConfigWithFallback: ${MY_CONFIG:defaultValue}
    envConfig: ${MY_CONFIG}
```

### Actual behavior

Starting the native executable fails with the exception (given for the mentioned examples) with error
```bash
Failed to load config value of type class java.lang.String for: my.config.stringConfig
Failed to load config value of type int for: my.config.intConfig
```

### How to Reproduce?

Using the attached project:
1. Build the native executable with`quarkus build --native --no-tests -Dquarkus.native.container-build=true`
2. Then build the Docker image with `docker build -f src/main/docker/Dockerfile.native-micro -t quarkus-yaml-bug .`
3. Run `docker run -i --rm quarkus-yaml-bug` to observe the error

[native-quarkus-yaml-bug.zip](https://github.com/quarkusio/quarkus/files/12831367/native-quarkus-yaml-bug.zip)

### Output of `uname -a` or `ver`

Darwin X6X29CW95F 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 17.0.8.1 2023-08-24 OpenJDK Runtime Environment Temurin-17.0.8.1+1 (build 17.0.8.1+1) OpenJDK 64-Bit Server VM Temurin-17.0.8.1+1 (build 17.0.8.1+1, mixed mode)

### Quarkus version or git rev

3.4.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.3
