### ISSUE TITLE
Update Windows CI build Mandrel version?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#36499]
Our Windows CI build is still using Mandrel for Java 17 AFAIK:
```
      - name: Setup GraalVM
        id: setup-graalvm
        uses: graalvm/setup-graalvm@v1
        if: startsWith(matrix.os-name, 'windows')
        with:
          version: 'mandrel-latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
```

See https://github.com/quarkusio/quarkus/blob/main/.github/workflows/ci-actions-incremental.yml#L905-L913

I have also seen some 404 failures when the action is run so I'm wondering if it needs further adjustments?

Also, I think I had some issues with this in old branches as I couldn't find a way to use `graalvm/setup-graalvm@v1` and point to the older Mandrel version we wanted to use.

Maybe the Mandrel team already solved this and can help?
