### ISSUE TITLE
`quarkus.otel.traces.suppress-non-application-uris` not working with `quarkus.management.enabled`

### ISSUE THREAD

**Issue by allevimi-nttdata** [quarkusio/quarkus#36510]
### Describe the bug

The default behaviour of `quarkus.otel.traces.suppress-non-application-uris` is to suppress trace collection of non applicative uris, everything is fine with standard confs, but if I enable the management interface through `quarkus.management.enabled=true`suppresion will fail.

### Expected behavior

With `quarkus.management.enabled` set to true, health check will be redirect to `0.0.0.0:9000/q/health` and trace collection will continue to be suppresed.

### Actual behavior

Otel trace collection is not suppressed and it seems that `quarkus.otel.traces.suppress-non-application-uris` is been ignored.

### How to Reproduce?

```Quarkus platform BOMs:
         io.quarkus.platform:quarkus-bom:pom:3.4.3 ✔

Extensions from io.quarkus.platform:quarkus-bom:
         io.quarkus:quarkus-resteasy-reactive-jackson ✔
         io.quarkus:quarkus-smallrye-health ✔
         io.quarkus:quarkus-config-yaml ✔
         io.quarkus:quarkus-arc ✔
         io.quarkus:quarkus-rest-client-reactive-jackson ✔

 Extensions from unknown origin:
         io.quarkiverse.opentelemetry.exporter:quarkus-opentelemetry-exporter-gcp:2.0.0.Final
```

`application.yaml`
```
quarkus:
  otel:
    traces:
      suppress-non-application-uris: true
  management:
    enabled: true
  opentelemetry:
    tracer:
      exporter:
        gcp:
          enabled: false
        otlp:
          enabled: true
```

1. make call to health api
`curl localhost:9000/q/health`
2. check on Otel receiver (ex. Jaeger)
3. will see a trace for health call

### Output of `uname -a` or `ver`

Darwin *** 23.0.0 Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk 17.0.6 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

### Quarkus version or git rev

3.4.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3
