### ISSUE TITLE
[Redis] Connection not released after DNS issue

### ISSUE THREAD

**Issue by lucaspouzac** [quarkusio/quarkus#36853]
### Describe the bug

When a connection is closed prematurely, it is not always released. We used redis-cli with Uni for reactive programming.

At the time of the problem, we have several log traces of this type : 

```
logger : io.vertx.redis.client.impl.RedisConnectionManager
errorType: "io.netty.channel.StacklessClosedChannelException"
message: "Unhandled Error"
stacktrace : io.netty.channel.StacklessClosedChannelException
	at io.netty.channel.AbstractChannel$AbstractUnsafe.write(Object, ChannelPromise)(Unknown Source)
threadName: "vert.x-eventloop-thread-2"
```

quarkus redis configuration

```
  redis:
    cache:
      max-pool-size: 6
      max-pool-waiting: 1000
      reconnect-attempts: -1
      pool-cleaner-interval: 5S
      tcp:
        keep-alive: true
        connection-timeout: 100MS
        read-idle-timeout: 1S
        write-idle-timeout: 1S
```

redis_pool_active is full and after redis_pool_queue_size is full.
We use redis 7.2.2

![image](https://github.com/quarkusio/quarkus/assets/758899/13029532-a499-4b22-9b78-a5e605b865ab)
![image](https://github.com/quarkusio/quarkus/assets/758899/1fe34c9e-2773-4957-a0d9-a4fca6a839e6)

### Expected behavior

The redis connection must be correctly release after an error

### Output of `java -version`

21

### Quarkus version or git rev

3.5.0
