### ISSUE TITLE
The flyway extension generates Kubernetes resources as if quarkus.flyway.enabled was a runtime property

### ISSUE THREAD

**Issue by PierreBtz** [quarkusio/quarkus#37040]
### Describe the bug

I noticed that when generating Kubernetes resource with the flyway extension in the classpath, an [initialization task is created](https://quarkus.io/guides/init-tasks) (as expected), but then the main container containing the application defines the `QUARKUS_FLYWAY_ENABLED` as false, which cannot have any effect since the [quarkus.flyway.enabled](https://quarkus.io/guides/all-config#quarkus-flyway_quarkus.flyway.enabled) is now a build time property.

### Expected behavior

Either the variable is removed if it's useless anymore, or the logic is changed.

### Actual behavior

With the variable set, at startup, Quarkus will warn that a change on a build property has no effect at runtime. 
I cannot say if it breaks a previous workflow since I detected this while playing around with the extension, I suspect it's not breaking anything but it's not optimal since migration logic will try to run in any application container.

### How to Reproduce?

To reproduce:

* generate a project on code with quarkus using this link https://code.quarkus.io/?g=eu.pierrebeitz&a=quarkus-flyway-build-property-issue&e=flyway&e=kubernetes&e=jdbc-h2&extension-search=origin:platform%20jdbc (it selects the flyway, kubernetes and jdbc-h2 extensions).
* run `mvn package` on the project and `cat target/kubernetes/kubernetes.yml`
* observe the injection of the QUARKUS_FLYWAY_ENABLED variable in the application container:

```
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUARKUS_FLYWAY_ENABLED
              value: "false"
```

### Output of `uname -a` or `ver`

Darwin ** 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:24 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19 OpenJDK Runtime Environment Temurin-17.0.4+8 (build 17.0.4+8) OpenJDK 64-Bit Server VM Temurin-17.0.4+8 (build 17.0.4+8, mixed mode)

### Quarkus version or git rev

3.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)

### Additional information

Note that the same is true for the init task (which sets the variable to true):

```
- env:
    - name: QUARKUS_INIT_AND_EXIT
      value: "true"
    - name: QUARKUS_FLYWAY_ENABLED
      value: "true"
```
