### ISSUE TITLE
Cannot reference default datasource form Quarkus Config

### ISSUE THREAD

**Issue by idursto** [quarkusio/quarkus#37396]
### Describe the bug

I am not sure if this is a bug or just something not supported within Quarkus.  The hibernate-orm-panache extension requires me to have a "default" datasource setup in the Quarkus config.  Then if another extension requires a datasource from their own configuration it requires me to redundantly specify that datasource because I have no way to reference the "default" datasource object in quarkus from the YAML/Config.  Is there any way to reference the "default" quarkus datasource that I am missing?  Here is how I end up having to set things up:

```YAML
quarkus:  
  some_extension_that_needs_a_datasource:  
    repository:  
      type: jdbc  
      jdbc:  
        datasource: default  
  
  datasource:  
    db-kind: h2  
    username: username
    password: password
    jdbc:  
      url: jdbc:h2:file:./data/myapps-db;AUTO_SERVER=TRUE  
  
    default:  
      db-kind: h2  
      username: username
      password: password
      jdbc:  
        url: jdbc:h2:file:./data/myapps-db;AUTO_SERVER=TRUE  
  package:  
    type: uber-jar  
    output-name: myapps-uber-jar
  
  log:  
    level: DEBUG  
    console:  
      enable: true  
      level: DEBUG  
```

### Expected behavior

Somehow have a way to reference the "default" quarkus datasource in my config.

### Actual behavior

There is no way I can find to reference the "default" quarkus datasource in my config forcing redundancy within the config.

### Output of `java -version`

IBM Semeru Runtime Open Edition 11.0.15.0 (build 11.0.15+10)

### Quarkus version or git rev

3.3.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.4
