### ISSUE TITLE
DB Healthcheck is missing from liveness path

### ISSUE THREAD

**Issue by Mulgish** [quarkusio/quarkus#37881]
### Describe the bug

DB healthchecks are missing from `/q/health/live` path and are only present in `/q/health/ready`.

This causes issues if below configuration is used in Kuberenetes as pod's don't get restarted as liveness check keeps passing:
```yaml
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /q/health/ready
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /q/health/live
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
```

### Expected behavior

Liveness probe should include DB healthchecks

### Actual behavior

Only readiness probe includes DB healthchecks

### How to Reproduce?

Can use default Quarkus examples with db connectivity and go to `http://localhost:8080/q/health/live` to observe missing db healthcheck.

### Output of `uname -a` or `ver`

Linux 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.8 2023-07-18 OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-1.fc38) (build 17.0.8+7, mixed mode, sharing)

### Quarkus version or git rev

3.6.3

**Comment by xstefank** [comment]
Hi, I'm not on pc, so take my response with a grain of salt. I can provide more details later if needed.

The DB health check is defined as reasiness only. Not sure what is the reason for that. @gsmet or @geoand can point the people behind it to this issue?

But in every case, you can just extend the provided DBHealthCheck (don't know the class name on top of my head) and define it as liveness.

I can send you the code once I'll be on pc.

**Comment by Mulgish** [comment]
@xstefank I have fixed the problem by pointing liveness probe to `/q/health` rather than `/q/health/live`:

```yaml
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /q/health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 1
```

It will be good to understand the reason why those healthchecks are not included in liveness paths.
