### ISSUE TITLE
Make annotation app.quarkus.io/vcs-uri optional in Kubernetes extension

### ISSUE THREAD

**Issue by antoniomacri** [quarkusio/quarkus#38055]
### Description

The Kubernetes extension adds the annotation `app.quarkus.io/vcs-uri` to the generated deployment.

However, in our case it is integrated in our GitLab CI pipelines, so when the repository is cloned the GL user and token are specified in the URL and as a consequence the token is written as part of the annotation:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/vcs-uri: https://gitlab-ci-token:<token>@gitlab.onprem.com/project.git
...
```

It should be possible to opt-out for this annotation.

**Comment by geoand** [comment]
Sounds reasonable to me @iocanel

**Comment by crumohr** [comment]
Would it be possible to consider just omitting the token from the URL format in the configuration?

Like `https://{omit_including_at@}gitlab.onprem.com/project.git`.

This change would help in preventing the accidental exposure of sensitive credentials in our Argo CD repository.

**Comment by crumohr** [comment]
As a workaround, you can use Kustomize to remove this annotation. Here's how we do it:

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kubernetes.yml

patches:
  - target:
      kind: .*
    patch: |-
      - op: add
        path: "/metadata/annotations/app.quarkus.io~1vcs-uri"
        value: "dummy"
      - op: remove
        path: "/metadata/annotations/app.quarkus.io~1vcs-uri"   
```

This approach first adds a dummy value to ensure the annotation exists on all resources, then removes it.
