### ISSUE TITLE
smallrye-openapi property `oidc-open-id-connect-url` might not be fixed at build time

### ISSUE THREAD

**Issue by aseixas-mgnl** [quarkusio/quarkus#38101]
### Describe the bug

Openapi spec requires (or at least, strict openapi spec validators require) the `components.securitySchemes.SecurityScheme.openIdConnectUrl` value to be present in the openapi spec. This can be provided at build time by the property described in this swagger-ui [doc](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.oidc-open-id-connect-url)

We might want to provide different urls depending on the deployment environment or the same app, without requiring rebuilding the whole app specifically per environment. Making it runtime-bound would fix the problem easily.

But there is maybe something more to this issue:

We are actually using the OIDC extension here together with openapi extension so we are setting up the `QUARKUS_OIDC_AUTH_SERVER_URL` env var (or equivalent property) which is basically bound at runtime. This feature is highly correlated to the property mentioned in the title, I think there might be something extra to be done here like automatically setting up the openIdConnectUrl in the spec when using the oidc auth server url .

### Expected behavior

The OpenApi spec has the runtime provided `openIdConnectUrl` (ex: https://example.com)

```
    servers:
      - url: https://api.example.com/v2
    components:
      securitySchemes:
        openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

### Actual behavior

There is no way to provide the openIdConnectUrl at runtime.

### How to Reproduce?

Create a project with oidc: https://quarkus.io/guides/security-oidc-bearer-token-authentication-tutorial
and some rest endpoints or openapi spec.
Then add the openapi extension (`./mvnw quarkus:add-extension -Dextensions='quarkus-smallrye-openapi'`) to produce an openapi spec

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by MikeEdgar** [comment]
@aseixas-mgnl , do you have any `@RolesAllowed` annotations on your REST endpoints? When used together with `QUARKUS_OIDC_AUTH_SERVER_URL` at runtime, you should be able to set the URL dynamically.

**Comment by aseixas-mgnl** [comment]
We don't use any @RolesAllowed.
Regarding `QUARKUS_OIDC_AUTH_SERVER_URL` this is not the property we want to change to runtime as it already is and works fine. The one we think it might be changed to runtime is [quarkus.smallrye-openapi.oidc-open-id-connect-url](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus.smallrye-openapi.oidc-open-id-connect-url).

In the end our goal is to have the openapi spec reflect the openIdConnectUrl:
```
    servers:
      - url: https://api.example.com/v2
    components:
      securitySchemes:
        openId:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration  <---- this
```
