### ISSUE TITLE
Changing quarkus knative port doesn't work

### ISSUE THREAD

**Issue by llowinge** [quarkusio/quarkus#38137]
### Describe the bug

Following https://quarkus.io/guides/deploying-to-kubernetes#quarkus-knative-knative-config_quarkus.knative.ports.-ports-.container-port

and having multiple variations of this option as follows:

```
quarkus.kubernetes.deployment-target=knative
quarkus.knative.ports."grpc".container-port=8086
quarkus.knative.ports."http1".container-port=8086
quarkus.knative.ports.http1.container-port=8086
quarkus.knative.ports.grpc.container-port=8086
```
always results in
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2024-01-11 - 08:25:59 +0000
  labels:
    app.kubernetes.io/name: code-with-quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: code-with-quarkus
spec:
  template:
    spec:
      containers:
        - image: llowinge/code-with-quarkus:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: code-with-quarkus
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP

```

The same problem is with host port.

### Expected behavior

The resulting knative.yaml/json would have changed/added port value. 

### Actual behavior

Custom port is not added.

### How to Reproduce?

Download app version and containing only quarkus-resteasy-reactive, quarkus-kubernetes extensions from code.quarkus.io

Modify application.properties and run `mvn clean package -DskipTests -ntp && cat target/kubernetes/knative.yml` 

### Output of `uname -a` or `ver`

uname -a                                                                                                                                                                  ✘ 130  Darwin llowinge-mac 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.9+9 (build 17.0.9+9)

### Quarkus version or git rev

3.2.9.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

17.0.9

### Additional information

I've tried also with latest 3.6.5 and it is the same.
