### ISSUE TITLE
Generated OpenAPI Document SecurityScheme wrong after Upgrade to Qurkus 3.0.4 from 2.16.6

### ISSUE THREAD

**Issue by Legion2** [quarkusio/quarkus#38677]
### Describe the bug

We have configured a SecurityScheme via OpenAPIDefinition annotation in our application.

```kotlin
@OpenAPIDefinition(
    info = Info(title = "Foo Service", version = "1.0.0"),
    components = Components(
        securitySchemes = [SecurityScheme(
            securitySchemeName = "SecurityScheme",
            type = SecuritySchemeType.OAUTH2,
            flows = OAuthFlows(
                authorizationCode = OAuthFlow(
                    authorizationUrl = "https://example.com/authorize",
                    tokenUrl = "https://example.com/oauth/token",
                    scopes = [
                        OAuthScope(name = someScope),
                    ]
                )
            )
        )]
    )
)
```

relevant application.properties:
```
quarkus.oidc.auth-server-url=https://example.com
quarkus.oidc.application-type=SERVICE
quarkus.oidc.client-id=foo
quarkus.oidc.token.audience=example.com
quarkus.oidc.token.issuer=any
quarkus.oidc.roles.role-claim-path=scope

quarkus.smallrye-openapi.auto-add-security=false
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger
quarkus.swagger-ui.always-include=true
```

### Expected behavior

After the upgrade to Quarkus 3.0.4 from 2.16.6 the `openapi` document should remain the same

```yaml
...
  securitySchemes:
    SecurityScheme:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            someScope: "null"
```

### Actual behavior

The openapi document changed to:

```yaml
...
  securitySchemes:
    SecurityScheme:
      type: openIdConnect
      description: Authentication
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
```

### How to Reproduce?

Use the above Quarkus version and provided code snippets

### Quarkus version or git rev

3.0.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 7.4 ------------------------------------------------------------  Build time:   2022-02-08 09:58:38 UTC Revision:     f0d9291c04b90b59445041eaa75b2ee744162586  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.9 (Private Build 17.0.9+9-Ubuntu-122.04) OS:           Linux 6.5.0-15-generic amd64

### Additional information

May be related to https://github.com/quarkusio/quarkus/pull/31671
