### ISSUE TITLE
OidcRequestFilter with OidcEndpoint applied to all endpoints

### ISSUE THREAD

**Issue by 01epa** [quarkusio/quarkus#38776]
### Describe the bug

Not able to create a OidcEndpoint filter with OidcEndpoint anotation which is applied only to a set of OIDC endpoints.

### Expected behavior

Filter should be applied to specified endpoint only.

### Actual behavior

Filter is applied to every OIDC endpoint.

### How to Reproduce?

* Follow [instruction ](https://quarkus.io/guides/security-openid-connect-client-reference)and integrate your service with OIDC
* Create an [OIDC filter](https://quarkus.io/guides/security-openid-connect-client-reference#oidc-client-filters) class and apply it to  JWKS endpoint only
```
@ApplicationScoped
@Unremovable
@Slf4j
@OidcEndpoint(value = OidcEndpoint.Type.JWKS)
public class OidcServiceAccountTokenFilter implements OidcRequestFilter {
    @Override
    public void filter(HttpRequest<Buffer> request,
                       Buffer buffer,
                       OidcRequestContextProperties contextProperties) {
        SATokenManager.Token token = SATokenManager.getInstance().getToken();
        request.putHeader(HttpHeaders.AUTHORIZATION, token.getAuthHeader());
    }
}
```
* enable discovery in application.yaml file
```
quarkus:
  oidc:
    auth-server-url: ${AUTH_SERVER_URL:https://kubernetes.default.svc}
    discovery-enabled: true
    authentication:
      user-info-required: false
    roles:
      role-claim-path: "kubernetes.io/serviceaccount/name"
      source: accesstoken
    tls:
      #disable tls verification
      verification: none
    token:
      verify-access-token-with-user-info: false
```
* Start application in debug mode and set breakpoint to your filter class

Result: breakpoint stops when service will try to do discovery

### Additional information

Looks like root cause of this issue is code generation for filter (proxy class).
[Here ](https://github.com/quarkusio/quarkus/blob/3.7.1/extensions/oidc-common/runtime/src/main/java/io/quarkus/oidc/common/runtime/OidcCommonUtils.java#L497) we got proxy classes and later we try to read annotation from it but it does not exist. Annotation is present on original class. As a result anootion is null and filter will be applied to all endpoints
See screenshot from debug for more information

![oidc filter issue](https://github.com/quarkusio/quarkus/assets/23399906/2a5fcabf-f835-46bf-99af-5e02b48223e2)

On the right side you can see 3 evaluation windows:
1. Check annotation on original class
2. Check annotation on proxy class
3. Prove that current filter object is proxy class
