### ISSUE TITLE
POLA violation in config-yaml when merging lists and maps

### ISSUE THREAD

**Issue by marcelstoer** [quarkusio/quarkus#38786]
### Describe the bug

This originated at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/SmallRye.20config.20mapping.3A.20override.20lists.

Overwriting lists in a profile with YAML config does not work as expected. Rather than replacing the complex list object for the given key entirely, the YAML extension maps individual list items back to the original list (in the non-profile config). It is very cumbersome to overwrite long and/or nested lists. This prevents us from shipping our applications with sensible default configuration in some cases.

This IMO violates [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) amongst others because other configuration (mapping) frameworks like [Spring Boot config](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.merging-complex-types) and Lightbend/Typesafe Config for HOCON handle this as I would expect.

### Expected behavior

Given the following configuration.

**application.yaml**

```yaml
supported-language:
  - language-code: EN
    priority: 1
  - language-code: FR
    priority: 2
  - language-code: DE
    priority: 3
```

**application-dev.yaml**

```yaml
supported-language:
  - language-code: IT
    priority: 1
```

The application should run with a single item in the `supported-language` collection - the one from the dev configuration.

### Actual behavior

`supported-language` from `application-dev.yaml` does not replace the same key from `application.yaml`.

### How to Reproduce?

Someone already created a reproducer at https://github.com/nicolaideffremo/quarkus-config-list-override.

### Output of `java -version`

17

### Quarkus version or git rev

3.2.9

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven
