### ISSUE TITLE
Force Zero Data Source Configuration through clearing URL

### ISSUE THREAD

**Issue by c-schmitz-tsystems** [quarkusio/quarkus#39053]
### Describe the bug

We have a default configuration for the default data source in our solution like so:
```yaml
  datasource:
    db-kind: h2
    username: quarkus
    password: quarkus
    jdbc:
       url: jdbc:h2:mem:unittest;DB_CLOSE_DELAY=-1;NON_KEYWORDS=row;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
```

We would like to local developers the opportunity (optinal) to use devservices instead. Therefore the developer defines to following `.env` file:

```
quarkus.devservices.enabled=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=
quarkus.datasource.devservices.port=5432
testcontainers.reuse.enable=false
```

Resetting the url to empty does not trigger the automatic spin up of the appropriate devservice. It only works when we removing the url from the default settings. But thats not an option.

It seems there are a difference between empty and non existent. But to be flexible enough there should be a solution for removing the properties, so that the connected functionality like devservice can work correctly!

### Expected behavior

Set the datasource url to empty triggers the devservices.

### Actual behavior

Set the datasource url to empty does not trigger the devservices. Instead a default datasouce configuration error comes up.

**Comment by yrodiere** [comment]
I think that's related to something I saw discussed recently... @radcortez @maxandersen rings any bell? I think the discussion invovled @dmlloyd as well.

I don't think there's a way to "clear" properties due to how Smallrye Config treats empty strings as "no value", but I may be wrong.

A solution I can suggest would to specify this JDBC URL in a configuration profile, to set that profile by default, and to ask that developer to select another profile. But I'm not sure that's not possible right now without also affecting prod.

@geoand Do we have something similar to [quarkus.test.profile](https://quarkus.io/guides/continuous-testing#quarkus-test-dev-testing-test-config_quarkus-test-profile)/[quarkus.test.integration-test-profile](https://quarkus.io/guides/continuous-testing#quarkus-test-dev-testing-test-config_quarkus-test-integration-test-profile), but for dev mode?

E.g.:

```yaml

quarkus:
  datasource:
    db-kind: postgresql
    username: quarkus
    password: quarkus
  dev:
    profile: dev-no-services # does "quarkus.dev.profile" even exist though?

"%dev-no-services":
  quarkus:
    devservices:
      enabled: false
    datasource:
      db-kind: h2
      jdbc:
         url: jdbc:h2:mem:unittest;DB_CLOSE_DELAY=-1;NON_KEYWORDS=row;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;

"%dev":
  quarkus:
    devservices:
      enabled: true # That's the default but let's be explicit
    datasource:
      devservices:
        port: 5432
```

`.env`:

```
quarkus.dev.profile=dev
testcontainers.reuse.enable=false # Not sure what this is doing here but I'll leave it
```
