### ISSUE TITLE
Docker env does not apply as expected

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#4019]
I tried to build and run the application by a docker-compose file.

```yaml
version: '3.1' # specify docker-compose version

services:
  blogdb:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blogdb
      POSTGRES_USER: user
    volumes:
      - ./data:/var/lib/postgresql
 
  post-service: 
    image: hantsy/quarkus-post-service
    build: 
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.multistage
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:postgresql://blogdb:5432/blogdb
    ports:
      - "8080:8080" #specify ports forewarding
    depends_on:
      - blogdb
  
```
The [Application Configuration Guide](https://quarkus.io/guides/application-configuration-guide#overriding-properties-at-runtime) said, it is possible to use an env variable to override the configured properties. 

When run `docker-compose up`, it still try to connect `localhost` postgres which I defined in the *src/main/resources/application.properties*, and it fails in the *test* phase.
