### ISSUE TITLE
Use the quarkus.tls.trust-all configuration property and it will not take effect when the environment variable is set to true.

### ISSUE THREAD

**Issue by Umizhang0910** [quarkusio/quarkus#42283]
### Describe the bug

Use the quarkus.tls.trust-all configuration property and it will not take effect when the environment variable is set to true.
this is my config (use helm) :

in `deployment.yaml`:

```yaml
         env:
           - name: QUARKUS_TLS_TRUST_ALL
             value: {{$.Values.quarkus.tls.trustAll | quote}}
```

in `values.yaml`:

```yaml
quarkus:
  tls:
    trustAll: true
```

I tried the above configuration and the following two solutions, but neither worked.
in `application.yml`:

```yaml
quarkus:
  tls:
    trust-all: ${QUARKUS_TLS_TRUST_ALL:false}
```

quarkus version: 3.1.3.Final

### Expected behavior

Expect the quarkus.tls.trust-all property to be true so that I will not throw a certificate not found exception when requesting other services.

### Actual behavior

The actual quarkus.tls.trust-all property is false, causing an exception to be thrown when I request other services.

Exception message:
RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target: jakarta.ws.rs.ProcessingException: RESTEASY004655: Unable to invoke request: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	

### Output of `java -version`

openjdk 17.0.11 2024-04-16

### Quarkus version or git rev

<quarkus.platform.version>3.1.3.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.11.0
