### ISSUE TITLE
quarkus.knative.app-config-map misses adding the volumes to the ksvc template

### ISSUE THREAD

**Issue by claudio4j** [quarkusio/quarkus#42466]
### Describe the bug

Given a really simple maven project generated from code.quarkus.io with knative enabled, quarkus platform 3.13.1

When setting the `quarkus.knative.app-config-map=ceq-app` property in application.properties (and `quarkus.kubernetes.deployment-target=knative`) the generated `knative.yml` is missing the `volumes` in the Knative Service.

The full knative service is
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.13.1
    app.quarkus.io/build-timestamp: 2024-08-10 - 13:53:11 +0000
  labels:
    app.kubernetes.io/version: "1.0"
    app.kubernetes.io/name: ceq-kn-printer
  name: ceq-kn-printer
spec:
  template:
    spec:
      containers:
        - env:
            - name: SMALLRYE_CONFIG_LOCATIONS
              value: /mnt/app-config-map
          image: docker.io/mycompany/ceq-kn-printer:1.0
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: ceq-kn-printer
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          volumeMounts:
            - mountPath: /mnt/app-config-map
              name: app-config-map
              readOnly: false
```

The missing part is
```
volumes:
  - configMap:
      name: config-printer
      optional: false
    name: app-config-map
```

Note, if change the deployment target to kubernetes and set `quarkus.kubernetes.app-config-map=config-printer`, the volume is correctly configured.

Workaround:

Set these properties to mount from the configmap.
```
quarkus.knative.config-map-volumes.config-printer.config-map-name=config-printer
quarkus.knative.config-map-volumes.config-printer.default-mode=420
quarkus.knative.mounts.config-printer.path=/mnt/app-config-map
quarkus.knative.mounts.config-printer.name=config-printer
quarkus.knative.env.vars.SMALLRYE_CONFIG_LOCATIONS=/mnt/app-config-map
```

### Expected behavior

To generate the volume mount from config-map in the knative service template.

### Output of `uname -a` or `ver`

linux 6.9.12-200.fc40.x86_64

### Output of `java -version`

21.0.2

### Quarkus version or git rev

3.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.5
