### ISSUE TITLE
Freeform Map<String,String> configuration properties always marked as required

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#42505]
### Describe the bug

We have a config property in Quarkus CXF defined as follows:

```java
        @WssConfigurationConstant(key = "security.signature.properties", transformer = properties)
        @WithName("signature.properties")
        Map<String, String> signatureProperties();
```

Before the recent refactoring of `quarkus-extension-processor`, the metadata was produced with `"optional": true` in `target/asciidoc/generated/config/all-configuration-roots-generated-doc/io.quarkiverse.cxf.ws.security.CxfWsSecurityConfig`:

```json
  {
    "configDocKey": {
      "type": "`Map<String,String>`",
      "key": "quarkus.cxf.client.\"client-name\".security.signature.properties",
      "additionalKeys": [],
      "configDoc": "The Crypto property configuration to use for signing, if `signature.crypto` is not set.\n\nExample\n\n[source,properties]\n----\n[prefix].signature.properties.\"org.apache.ws.security.crypto.provider\" =\norg.apache.ws.security.components.crypto.Merlin\n[prefix].signature.properties.\"org.apache.ws.security.crypto.merlin.keystore.password\" = password\n[prefix].signature.properties.\"org.apache.ws.security.crypto.merlin.file\" = certs/alice.jks\n----",
      "withinAMap": true,
      "defaultValue": "",
      "javaDocSiteLink": "",
      "docMapKey": "signature-properties",
      "configPhase": "RUN_TIME",
      "acceptedValues": null,
      "optional": true,
      "list": false,
      "passThroughMap": true,
      "withinAConfigGroup": true,
      "topLevelGrouping": "quarkus.cxf",
      "since": "2.5.0",
      "environmentVariable": "QUARKUS_CXF_CLIENT__CLIENT_NAME__SECURITY_SIGNATURE_PROPERTIES",
      "enum": false
    }
  },
```

After the refactoring, the `target/quarkus-config-doc/quarkus-config-model.yaml` file is produced without `"optional": true`:

```yaml
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    sourceClass: "io.quarkiverse.cxf.ws.security.CxfWsSecurityConfig.ClientOrEndpointSecurityConfig"
    sourceName: "signatureProperties"
    path: "quarkus.cxf.client.\"client-name\".security.signature.properties.\"signature-properties\""
    type: "java.util.Map<java.lang.String,java.lang.String>"
    phase: "RUN_TIME"
    environmentVariable: "QUARKUS_CXF_CLIENT__CLIENT_NAME__SECURITY_SIGNATURE_PROPERTIES__SIGNATURE_PROPERTIES_"
    typeDescription: "Map<String,String>"
    map: true
    mapKey: "signature-properties"
    withinMap: true
```

### Expected behavior

Freeform Map<String,String> configuration properties should be always considered optional - same like before the refactoring. Therefore `"optional": true` should be present in the metadata.

### Actual behavior

`"optional": true` is missing in the metadata.

### How to Reproduce?

Rebuild `quarkus-agroal` in Quarkus source tree and check `quarkus.datasource.jdbc.additional-jdbc-properties` in its `target/quarkus-config-doc/quarkus-config-model.yaml`.
