### ISSUE TITLE
Enum property values not hyphenated anymore in the configuration metadata

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#42514]
### Describe the bug

We have a config property in Quarkus CXF defined as follows:

```java
    @WithDefault("Keep-Alive")
    @WithConverter(ConnectionTypeConverter.class)
    public ConnectionType connection();
```

Before the recent refactoring of `quarkus-extension-processor`, the metadata was produced with hyphenated enum values `target/asciidoc/generated/config/all-configuration-roots-generated-doc/io.quarkiverse.cxf.CxfConfig`:

```json
  {
    "configDocKey": {
      "type": "org.apache.cxf.transports.http.configuration.ConnectionType",
      "key": "quarkus.cxf.client.\"client-name\".connection",
      "additionalKeys": [],
      "configDoc": "The connection disposition. If close the connection to the server is closed after each request/response dialog. If\nKeep-Alive the client requests the server to keep the connection open, and if the server honors the keep alive request,\nthe connection is reused. Many servers and proxies do not honor keep-alive requests.",
      "withinAMap": true,
      "defaultValue": "keep-alive",
      "javaDocSiteLink": "",
      "docMapKey": "connection",
      "configPhase": "RUN_TIME",
      "acceptedValues": [
        "`close`",
        "`keep-alive`"
      ],
      "optional": false,
      "list": false,
      "passThroughMap": false,
      "withinAConfigGroup": true,
      "topLevelGrouping": "quarkus.cxf",
      "since": "2.2.3",
      "environmentVariable": "QUARKUS_CXF_CLIENT__CLIENT_NAME__CONNECTION",
      "enum": true
    }
  },
```

After the refactoring, the enum values in `target/quarkus-config-doc/quarkus-config-model.yaml` are present verbatim:

```yaml
  - !<io.quarkus.annotation.processor.documentation.config.model.ConfigProperty>
    enum: true
    sourceClass: "io.quarkiverse.cxf.CxfClientConfig"
    sourceName: "connection"
    path: "quarkus.cxf.client.\"client-name\".connection"
    type: "org.apache.cxf.transports.http.configuration.ConnectionType"
    phase: "RUN_TIME"
    environmentVariable: "QUARKUS_CXF_CLIENT__CLIENT_NAME__CONNECTION"
    typeDescription: "ConnectionType"
    withinMap: true
    converted: true
    enumAcceptedValues:
      qualifiedName: "org.apache.cxf.transports.http.configuration.ConnectionType"
      values:
        CLOSE:
          configValue: "CLOSE"
        KEEP_ALIVE:
          configValue: "KEEP_ALIVE"
    defaultValue: "Keep-Alive"
```

### Expected behavior

The enum values should be produced hyphenated, same as before quarkus-extension-processor refactoring.

I am aware of the following note in ConfigResolver

https://github.com/quarkusio/quarkus/blob/baf77db720ab5794a1b152c87a01df3c291f864e/core/processor/src/main/java/io/quarkus/annotation/processor/documentation/config/resolver/ConfigResolver.java#L155-L156

However my example proves that the rule to decide about hyphenation must have been complexer than just "if the property has a converter"
