### ISSUE TITLE
OpenShift:  improve triggering of Deployment from ImageStream

### ISSUE THREAD

**Issue by grdryn** [quarkusio/quarkus#42747]
### Description

The main reason for opening this issue is that the [deploying-to-openshift](https://quarkus.io/guides/deploying-to-openshift) docs page says the following:
> Since Deployment is a Kubernetes resource and not OpenShift specific, it can’t possibly leverage ImageStream resources, as is the case with DeploymentConfig.

I don't think this is _entirely_ correct to say: it's possible to set the `image.openshift.io/triggers` annotation in a Deployment (also works with other resource types like CronJob/Job, StatefulSet, DaemonSet, Pod) such that it will be updated with the new image reference, when the ImageStreamTag is updated.

I think past releases of Quarkus defaulted to using DeploymentConfig, and the latest image in the ImageStreamTag was automatically deployed, no matter if the image was updated by something that the developer did outside Quarkus (such as manually triggering a BuildConfig that updated it), or by using one of the quarkus conveniences (such as the `quarkus build -Dquarkus.openshift.deploy=true` in the docs that seems like it waits for the build to finish, then modifies the Deployment with the new image reference). Now that Quarkus appears to default to Deployment, the Deployment doesn't appear to get updated with the new image reference if the ImageStreamTag is updated outside of Quarkus.

Now that DeploymentConfig is deprecated since OpenShift 4.14 and Deployment is the default in Quarkus, I think this would be a nice improvement

### Implementation ideas

Per the [OpenShift docs on triggering updates on ImageStream changes](https://docs.openshift.com/container-platform/4.16/openshift_images/triggering-updates-on-imagestream-changes.html), an annotation can be added like this to appropriate Kubernetes resources:

```yaml
    image.openshift.io/triggers:
      [
       {
         "from": {
           "kind": "ImageStreamTag", 
           "name": "example:latest", 
           "namespace": "myapp" 
         },
         "fieldPath": "spec.template.spec.containers[?(@.name==\"web\")].image", 
         "paused": false 
       },
      # ...
      ]
```
