### ISSUE TITLE
Can't inject MongoClient with quarkus-mongodb-client.

### ISSUE THREAD

**Issue by DioxideCN** [quarkusio/quarkus#43499]
### Describe the bug

I've definded a no name mongo connection in my application.yaml:

```
quarkus:
  mongodb:
    connection-string: mongodb://localhost:27017
    database: test_collection
```

and I try to inject `MongoClient` into my application:

```java
@Startup
@ApplicationScoped
public class MongoService {
    
    @Inject MongoClient mongoClient;
    
    public MongoService() {
        System.out.println(mongoClient == null);
    }
    
}
```

but the IDEA told me that 'Unsatisfied dependency: no bean matches the injection point'. Also after starting the application I got "true" which means mongoClient is null in console.

### Output of `java -version`

graalvm 21.0.4

### Quarkus version or git rev

3.14.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven-3.9.8
