### ISSUE TITLE
Configuration validation failed error when mixing @ConfigMapping and @ConfigProperty

### ISSUE THREAD

**Issue by elenagarrido** [quarkusio/quarkus#44011]
### Describe the bug

We have an interface declared as follows

```java
@ConfigMapping(prefix = "aaa.ldap.pool")
public interface ConnectionPoolConfig {
.... several methods matching with the configuration values
}
``` 

in a class we have
```java
@ApplicationScoped
public class LogsSummarizer {
  @ConfigProperty(name = "aaa.rlogsummary.period")
  String secondsPreiod;
}
``` 

In our application.yaml file 
```
aaa:
  ldap:
    pool:
        ..... names matching with the interface
  logsummary:
    period: 30s
``` 

### Expected behavior

To run the application and be able to retrieve the values from the interface and the class 

### Actual behavior

We have an exception 
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	SRCFG00050: aaa.logsummary.period in YamlConfigSource[source=file:/C:/..../target/classes/application.yaml] does not map to any root

As soon as I change the name of the variable in the class to 
aaalogsummary.period

and the respective yaml file to 
 ```
aaa:
  ldap:
    pool:
        ..... names matching with the interface
aaalogsummary:
    period: 30s
``` 

I stop having the exception and the application runs. But I would prefer to have the application.yaml file  the way it fails right now

### Output of `uname -a` or `ver`

inux currito 6.8.0-47-generic #47-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep 27 21:40:26 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Java version: 17.0.5, vendor: N/A, runtime: /usr/lib64/jvm/java-17-openjdk-17

### Quarkus version or git rev

3.9.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
