### ISSUE TITLE
Kubeconfig file is not overridden when we use as flavor = kind and property: ﻿﻿override-kubeconfig=true of the kubernetes-client

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#44315]
### Describe the bug

The Kubeconfig file is not overridden with the config of the newly kind container created by testcontainer when we set the following properties
```
quarkus.kubernetes-client.devservices.enabled=true
quarkus.kubernetes-client.devservices.flavor=kind
quarkus.kubernetes-client.devservices.override-kubeconfig=true
```

The console reports that the cluster is well started
```
2024-11-05 11:17:14,891 INFO  [io.qua.kub.cli.dep.DevServicesKubernetesProcessor] (build-15) Dev Services for Kubernetes started. Other Quarkus applications in dev mode will find the cluster automatically.
```
and using the UI we can get the certificate, api url, etc but the local `~/.kube/config` file don't include such parameters

![Image](https://github.com/user-attachments/assets/3b453c2d-2fe6-42e0-9a17-c9c8f69039bc)

### Expected behavior

When we wet the property `quarkus.kubernetes-client.devservices.override-kubeconfig=true` using the flavor `kind` or `k3s` I expect to have a new cluster declared within the config kubernetes file

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tL...klDQVRFLS0tLS0K
    server: https://localhost:40351
  name: clever-napier
contexts:
- context:
    cluster: clever-napier
    user: clever-napier
  name: clever-napier
current-context: clever-napier
kind: Config
preferences: {}
users:
- name: clever-napier
  user:
    client-certificate-data: LS0tLS1CRU...S0tLS0K
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJ...URSBLRVktLS0tLQo=
```

### Actual behavior

Nothing has been added to the ~/.kube/config file

### How to Reproduce?

1. Create a quarkus project (>= 3.15)
2. Add as dependency: `quarkus-kubernetes-client`
3. Set the properties
```
quarkus.kubernetes-client.devservices.enabled=true
quarkus.kubernetes-client.devservices.flavor=kind
quarkus.kubernetes-client.devservices.override-kubeconfig=true
```
4. Start podman or docker
5. Run `./mvnw compile quarkus:dev`

### Output of `uname -a` or `ver`

Darwin cmoullias-MacBook-Pro 23.6.0 Darwin Kernel Version 23.6.0

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.15

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8
