### ISSUE TITLE
Micrometer default metrics issue

### ISSUE THREAD

**Issue by andreiyusupau** [quarkusio/quarkus#45064]
### Describe the bug

I have the following Micrometer config
```yaml
quarkus:
  micrometer:
    export:
      prometheus:
        enabled: true
        path: /metrics
    binder:
      http-client:
        enabled: false
      http-server:
        enabled: true
      jvm: false
      messaging:
        enabled: false
      system: false
      vertx:
        enabled: true
      netty:
        enabled: false
```
When I disable `vertx` (to remove for example event bus metrics) `http-server` metrics also gets disabled. How could I enable only `http-server` metrics? (explicit `http-server.enabled: true` doesn't help)

P.S. Also is there a way to enable only required default metrics , instead of enabling all and disabling them one by one?

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4460]

### Output of `java -version`

21.0.5

### Quarkus version or git rev

3.17.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.10.2
