### ISSUE TITLE
Generate Kubernetes Ingress Paths from Jakarta REST

### ISSUE THREAD

**Issue by Eric-Prokop** [quarkusio/quarkus#45696]
### Description

It would be nice if the ingress routing could be more explicit by adding the pahts known from Jakarta REST to the generated kubernetes ingress instead of just a 
```yaml
  path: /
    pathType: Prefix
```

**Comment by geoand** [comment]
Thanks for reporting.

Can you provide a few more details on what you would like to see here?

**Comment by Eric-Prokop** [comment]
So bascially this is my resource:
```java
@Path("/projects")
public interface ProjectsApi {

    @GET
    @Path("/autocomplete")
    @Produces({ "application/json" })
    Uni<AutocompleteResponse> autocomplete(@QueryParam("term") @NotNull @Size(min=3) String term);

    @GET
    @Path("/filter-elements")
    @Produces({ "application/json" })
    Uni<GetFilterElementsResponse> getFilterElements();

    @GET
    @Path("/all")
    @Produces({ "application/json" })
    Uni<ListProjectsResponse> listProjects();
}
```
Using the kubernetes extension with `quarkus.kubernetes.ingress.expose=true` produces:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.17.5
  labels:
    app.kubernetes.io/name: project-service
    app.kubernetes.io/managed-by: quarkus
  name: project-service
  namespace: staging
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: project-service
                port:
                  name: http
            path: /
            pathType: Prefix
```
But it would be much nicer to get this:
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.17.5
  labels:
    app.kubernetes.io/name: project-service
    app.kubernetes.io/managed-by: quarkus
  name: project-service
  namespace: staging
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: project-service
                port:
                  name: http
            path: /projects/autocomplete
            pathType: Exact
          - backend:
              service:
                name: project-service
                port:
                  name: http
            path: /projects/filter-elements
            pathType: Exact
          - backend:
              service:
                name: project-service
                port:
                  name: http
            path: /projects/all
            pathType: Exact
```
