### ISSUE TITLE
Kubernetes Initialization Tasks - Generated Role

### ISSUE THREAD

**Issue by efuturetoday** [quarkusio/quarkus#45748]
### Description

Currently, it is not possible to deploy multiple Quarkus applications within the same Kubernetes namespace when the init-tasks feature is enabled. This is because the framework generates a Role named view-jobs without providing options to modify the name or disable it entirely. Since Kubernetes does not allow two Roles with the same name in a namespace, deploying multiple applications is not feasible under these conditions.

I attempted to change the Role's name by setting the following property in application.properties:
`quarkus.kubernetes.rbac.roles.view-jobs.name=service-one-view-jobs`

However, the generated Kubernetes resource does not reflect the modified name. Instead, it adds an additional Role with the provided name (service-one-view-jobs).

Is there any workaround for this issue? Based on the [source code](https://github.com/quarkusio/quarkus/blob/77a710bcf2e3e1a62dfc952ce4fda5de62d9085e/extensions/kubernetes/vanilla/deployment/src/main/java/io/quarkus/kubernetes/deployment/InitTaskProcessor.java#L79), it seems there is no built-in way to customize the Role name or disable RBAC entirely.

**Comment by indiealexh** [comment]
I have this same issues.
I deploy multiple quarkus services into the same namespace and have to manually delete the generated role from my gitops repo, when I would like to just generate it and know it doesn't need tweaking.

My helm based workaround:

```yaml
quarkus:
  helm:
    add-if-statement:
      "jobRole.enabled":
        on-resource-kind: Role
        with-default-value: false
```

which results in:

```yaml
{{- if .Values.app.jobRole.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: app-name
    app.kubernetes.io/version: 2.1.0
  name: view-jobs
rules:
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get

{{- end }}
```

**Comment by iocanel** [comment]
I think that the simplest thing to do would be to just prefix things with the application name.

**Comment by FritzOscar** [comment]
Still reproducible on Quarkus 3.37.4. Two applications in the same namespace, deployed by ArgoCD, which reports:

```
Role/view-jobs is part of applications argocd/app-one and app-two
```

A kustomize-based workaround, for anyone not using the Helm extension — note that the `roleRef` has to be patched explicitly, because kustomize only fixes name references for renames driven by `namePrefix`/`nameSuffix`, not for JSON patches on `metadata/name`:

```yaml
patches:
  - target: { kind: Role, name: view-jobs }
    patch: |-
      - op: replace
        path: /metadata/name
        value: my-app-view-jobs
  - target: { kind: RoleBinding, name: my-app-view-jobs }
    patch: |-
      - op: replace
        path: /roleRef/name
        value: my-app-view-jobs
```

Setting `quarkus.kubernetes.init-tasks."<task>".enabled=false` does remove the Role today, but it also removes the init Job and the `wait-for-…` init container, so it is not an option when the externalized migration job is wanted.

One data point that may help settle the API shape: the same name-collision problem in `quarkus-kubernetes-config` was recently addressed in #54261 by adding `quarkus.kubernetes-config.secrets-role-config.prefix-name` (default `false`), which prefixes the Role name with the application name **and** sets the `RoleBinding` name accordingly so it is not double-prefixed by the Kubernetes extension — worth keeping in mind here, since renaming the Role alone leaves the binding name derived from `<app>-<roleRef>`.
