### ISSUE TITLE
Custom format of file handler not applied when quarkus-logging-json dependency is used

### ISSUE THREAD

**Issue by akridl** [quarkusio/quarkus#47169]
### Describe the bug

In my `pom.xml`, I have a dependency
```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-logging-json</artifactId>
        </dependency>
```

My `application.yaml` file:
```yaml
my-config:
  log-file: &log-file
    /tmp/quarkus.log
quarkus:
  log:
    handler:
      file:
        my-file-handler:
          enable: true
          path: *log-file
          format: '%d{yyyy-MM-dd HH:mm:ss} [%p] %s%e%n'
    category:
      "com.example":
        level: DEBUG
        handlers:
          - my-file-handler
```

Example usage of logging (using logger `com.example.GreetingResource`):
```java
@Path("/hello")
@Slf4j
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        log.debug("hello");
        log.info("hi");
        return "Hello from Quarkus REST";
    }
}
```

### Expected behavior

- after requesting `GET /hello` endpoint and stoping the application, file `/tmp/quarkus.log` should **contain logs of my configured format**, e.g.:
```
2025-04-03 15:25:34 [DEBUG] hello
2025-04-03 15:25:34 [INFO] hi
```

### Actual behavior

  - after requesting `GET /hello` endpoint and stoping the application, file `/tmp/quarkus.log` **contains logs in JSON format**, e.g.:
```json
{"timestamp":"2025-04-03T15:25:34.26140817+02:00","sequence":2102,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.example.GreetingResource","level":"DEBUG","message":"hello","threadName":"executor-thread-1","threadId":117,"mdc":{},"ndc":"","hostName":"fedora","processName":"/usr/lib/jvm/java-21-openjdk/bin/java","processId":246572}
{"timestamp":"2025-04-03T15:25:34.263763096+02:00","sequence":2103,"loggerClassName":"org.slf4j.impl.Slf4jLogger","loggerName":"com.example.GreetingResource","level":"INFO","message":"hi","threadName":"executor-thread-1","threadId":117,"mdc":{},"ndc":"","hostName":"fedora","processName":"/usr/lib/jvm/java-21-openjdk/bin/java","processId":246572}
```

### How to Reproduce?

Complete example available at my GitHub: https://github.com/akridl/logging-reproducer

### Additional information

- when I comment out the dependency `quarkus-logging-json`, the format of my file handler is correctly applied
- in the [documentation](https://quarkus.io/guides/logging#json-logging), I can see:
  > By default, the presence of this extension replaces the output format configuration from the console configuration
  
  so file (handler) configurations should not be affected based on docs
- mistakenly, I have created this issue for `io.quarkiverse.loggingjson:quarkus-logging-json`, see https://github.com/quarkiverse/quarkus-logging-json/issues/346, already containing a brief discussion
