### ISSUE TITLE
Metrics for the quarkus-load-shedding extension

### ISSUE THREAD

**Issue by brunobat** [quarkusio/quarkus#47761]
### Description

See https://quarkus.io/guides/load-shedding-reference

**Comment by Ladicek** [comment]
What kind of metrics do you imagine? I guess something around rejected requests, I don't know, a histogram perhaps?

**Comment by brunobat** [comment]
A counter with the rejected requests, yes and maybe some gauges to externalize some of the computation values, of the `OverloadDetector` or the `lastThreshold` in the `PriorityLoadShedding`. 
Things that can:
1. Allow us to get data to improve the algorithm
2. Provide early warning or insights about impending rejections.

**Comment by Ladicek** [comment]
That makes sense I guess. Are you gonna work on it, or should I?

**Comment by brunobat** [comment]
I can do that at some point, however, one thing it would be cool in the meantime is if you could add an IT project.

**Comment by Ladicek** [comment]
Testing this extension is hard because of its stochastic nature. I actually tested this locally using Hyperfoil, with this simple benchmark:

```yaml
name: load-shedding
http:
  host: http://localhost:8080
  sharedConnections: 5000
staircase:
  steadyStateDuration: 10s
  initialUsersPerSec: 500
  incrementUsersPerSec: 500
  maxIterations: 10
  scenario:
  - test:
    - httpRequest:
        GET: /
```

and this resource:

```java
@Path("/")
public class MyResource {
    @GET
    public String hello() throws InterruptedException {
        int millis = 5 + ThreadLocalRandom.current().nextInt(5);
        if (ThreadLocalRandom.current().nextInt(10) == 0) {
            long end = System.currentTimeMillis() + millis;
            while (System.currentTimeMillis() < end) {
            }
        } else {
            Thread.sleep(millis);
        }
        return "Hello World!";
    }
}
```

We could probably write something like that in Java, but it would be hard to test for concrete numbers.
