### ISSUE TITLE
Using YAML to configure async logging, the `enable` prop does not work with other prop such as `overflow`

### ISSUE THREAD

**Issue by zhangwanly** [quarkusio/quarkus#47889]
### Describe the bug

this can be work to enable async log：
```
quarkus:
  log:
    console:
      async: true
```
but together with other prop not work：
```
quarkus:
  log:
    console:
      async:
        enable: true
        overflow: discard
```

because `io.quarkus.runtime.logging.LogRuntimeConfig.AsyncConfig#enable` annotated with `@WithParentName`

i think it should be removed (`@WithParentName`)
