### ISSUE TITLE
Support multiple oidc tenants for graphql dynamic client

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#47999]
### Description

it would be interesting to allow the creation of dynamic clients targeting different services using different tenants.
right now it is possible to only refer to a single tenant (either the default or one named tenant).
in other words, I would like to be able to create:
```
    @Inject
    @GraphQLClient("client1")
    DynamicGraphQLClient dynamicClient1;

    @Inject
    @GraphQLClient("client2")
    DynamicGraphQLClient dynamicClient2;
```

```
quarkus:
  oidc-client-graphql:
    "client1":                                         <======= make this available
      client-name: my_tenant1
    "client2":
      client-name: my_tenant2
  oidc-client:
    my_tenant1:
      client-enabled: true
      auth-server-url: https://login.dev.tbiservices.net/adfs
      client-id: foo
      scopes:
        - openid
        - api://lodh.internal.jwt/allatclaims
      credentials:
        secret: ...
    my_tenant2:
      client-enabled: true
      auth-server-url: https://login.dev.tbiservices.net/adfs
      client-id: bar
      scopes:
        - openid
        - api://lodh.internal.jwt/allatclaims
      credentials:
        secret: ...
  smallrye-graphql-client:
    client1:
      url: https://...
    client2:
      url: https://...
```

right now we are only limited to a single tenant, as in:
```
quarkus:
  oidc-client-graphql:
    client-name: my_tenant1
```

cc @jmartisk @sberyozkin
