### ISSUE TITLE
Wrong connection information for docker compose mssql

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#48322]
### Describe the bug

I am using this docker compose definition for mssql:

```
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Quarkus123
    labels:
      io.quarkus.devservices.compose.wait_for.ports.disable: true
      io.quarkus.devservices.compose.wait_for.logs: .*Recovery is complete.*
      # io.quarkus.devservices.compose.wait_for.logs: .*Service Broker manager has started.*
```

and the following ap configuration:
```
  datasource:
    db-kind: "mssql"
  hibernate-orm:
    schema-management:
      strategy: update
```

with deps:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mssql</artifactId>
        </dependency>
```

the compose dev service configures a connection with:
```
url = "jdbc:sqlserver://localhost:49399/quarkus"
suppliedProperties = (Properties)
 "password" -> "Quarkus123"
 "user" -> "quarkus"
```

this should be (and that is what is configured with regular dev service)
```
url = "jdbc:sqlserver://localhost:49399"
suppliedProperties = (Properties)
 "password" -> "Quarkus123"
 "user" -> "sa"
```

connection attempt fails with:
```
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The port number 49399/quarkus is not valid.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDriverError(SQLServerException.java:242)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2870)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1971)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1263)
```

### Expected behavior

this should configure the dev service with the appropriate connection details (user and url)

### Actual behavior

the connection attempt fails

### How to Reproduce?

1- create an application with the appropriate deps (`quarkus-hibernate-orm` and `quarkus-jdbc-mssql`)
2 - create `compose-devservices.yml` with the above content
3 - `docker compose -f compose-devservices.yml up`
4 - wait for container `x-mssql-1` to be up
5 - start application in dev mode with `mvn quarkus:dev`

### Quarkus version or git rev

`3.23.2`
