### ISSUE TITLE
Allow Quarkus OIDC for webapp to forward prompt=login and force reauthentication

### ISSUE THREAD

**Issue by viswatejan** [quarkusio/quarkus#48505]
### Description

I have the following configuration and the using Keycloak/RHBK as the OIDC provider.

```yaml
quarkus:
  oidc:
    application-type: HYBRID
    authentication:
      forward-params:
        - kc_idp_hint
        - kc_action
        - login_hint
        - prompt
        - max_age
        - ui_locales
        - acr_values
```

The above forward-parms are working as expected when there is no application session but when there is session, they are ignored because quarkus-oidc skips redirect to OIDC provider.

It will be great if there is a way to give preference to the presence of at least **prompt** and **kc_action** params in the application URL and redirect to OIDC provider by forwarding these params just like how it is happening on the Keycloak JS adapter.

`prompt(OIDC spec)` will enable app to force reauthentication ignoring the SSO session on the OIDC provider and `kc_action` can help acheive some crucial actions like change password, delete account, registereing passkeys, etc with Keycloak.
