### ISSUE TITLE
Allow for short notation for Qute expressions and logical operators

### ISSUE THREAD

**Issue by goldmann** [quarkusio/quarkus#48535]
### Description

Currently such an expression is not supported within the Qute language and it will always evaluate to `false`.

```
{event.generation.status.toName() == 'FINISHED' && event.generation.request.generator.name == 'syft'}
```

Instead, I had to write it in a such way:

```
{#if event.generation.status.toName() == 'FINISHED' && event.generation.request.generator.name == 'syft'}true{#else}false{/if}
```

At first glance it may not look as a big deal, but consider usage scenario like this:

```yaml
conditions:
- type: expression
    if: {event.generation.status.toName() == 'FINISHED' && event.generation.request.generator.name == 'syft'}
```

This is more intuitive and cleaner than the form currently required:

```yaml
conditions:
- type: expression
    if: {#if event.generation.status.toName() == 'FINISHED' && event.generation.request.generator.name == 'syft'}true{#else}false{/if}
```
