### ISSUE TITLE
short-name is defined in extension descriptor root but read from metadata

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4977]
**Describe the bug**
`Extension.getShortName` retrieve the value from `metadata.short-name` but the value is set in the root of each extension descriptors. ex:
```
---
name: "SmallRye Context Propagation"
short-name: "context propagation"
metadata:
  keywords:
  - "smallrye-context-propagation"
  - "microprofile-context-propagation"
  - "context-propagation"
  - "context"
  - "reactive"
  categories:
  - "reactive"
```

**Expected**
```
---
name: "SmallRye Context Propagation"
metadata:
  short-name: "context propagation"
  keywords:
  - "smallrye-context-propagation"
  - "microprofile-context-propagation"
  - "context-propagation"
  - "context"
  - "reactive"
  categories:
  - "reactive"
```
