### ISSUE TITLE
Amazon Lambda SAM CLI integration

### ISSUE THREAD

**Issue by oztimpower** [quarkusio/quarkus#5037]
**Description**
I've tested the SAM integration that is on the Amazon Lambda HTTP docs, and used a similar sam.jvm.yaml (without the dynamo db YAML), and it works fine.

Any chance the archetype and documentation could clone this functionality from the Amazon Lambda HTTP implementation (incl. uber jar) -- particularly whilst it's fresh in the minds of the developers.

```
./extensions/amazon-lambda-http/maven-archetype/target/classes/archetype-resources/sam.jvm.yaml
./extensions/amazon-lambda-http/maven-archetype/target/classes/archetype-resources/sam.native.yaml
./extensions/amazon-lambda-http/maven-archetype/src/main/resources/archetype-resources/sam.jvm.yaml
./extensions/amazon-lambda-http/maven-archetype/src/main/resources/archetype-resources/sam.native.yaml

```

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
Resources:
  QuarkusSam:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
      Runtime: java8
      CodeUri: target/lambda-kotlin-1.0-SNAPSHOT-runner.jar
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole

```

It would be super cool also to have this in Gradle which is my preferred build tool.
