### ISSUE TITLE
override extension no longer seem to merge extenions but instead override

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5170]
current platform overrides for camel are completely ignoring metadata from camel extensions.

**Comment by maxandersen** [comment]
camel-core have:
```
name: "Camel Quarkus Core"
description: "The Camel Quarkus core module"
metadata:
  keywords:
  - "camel"
  guide: "https://quarkus.io/guides/camel"
  categories:
  - "integration"
```

override have: 
```
{
      "group-id": "org.apache.camel.quarkus",
      "artifact-id": "camel-quarkus-core",
      "version": "0.3.1",
      "description": "The Camel Quarkus core module"
    },
```

resulting platform have:

```
{
      "group-id": "org.apache.camel.quarkus",
      "artifact-id": "camel-quarkus-core",
      "version": "0.3.1",
      "description": "The Camel Quarkus core module"
    },
```

it should have:
```
{
      "group-id": "org.apache.camel.quarkus",
      "artifact-id": "camel-quarkus-core",
      "version": "0.3.1",
      "description": "The Camel Quarkus core module",
      "name" : "Camel Quarkus Core", 
      "keywords": ....
    },
```
