### ISSUE TITLE
dependabot - security - dependency_type: indirect ?

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5902]
I was looking a bit into dependabot configuration samples and noticed that security updates have often `dependency_type: indirect`.

Quarkus doesn't specify `dependency_type: indirect`.
https://github.com/quarkusio/quarkus/blob/master/.dependabot/config.yml#L7

Changed setup would be this:
```yaml
    allowed_updates:
      - match:
          update_type: "security"
          dependency_type: "indirect"
```

@gastaldi wdyt ?

Of course not sure how wild it could be as Quarkus integrates with half of the Java world :)
