### ISSUE TITLE
Document the usage to application.yaml

### ISSUE THREAD

**Issue by alexzimmer96** [quarkusio/quarkus#6106]
**Describe the bug**
In contrast to the 1.10.CR1-Annoucement, it does not seem like Quarkus or atleast Hibernate accepts the YAML-Format for configuration. Starting with only a application.yaml file containing all necessary informationen does not come up. Hibernate fails to identifiy the provided driver (at least, this is the Exception).

**Expected behavior**
The driver in the  `application.yaml` should be used when its specified.

**Actual behavior**
It does not seem that Hibernate uses the configuration provided in the `application.yaml`

**To Reproduce**
Try to start an Quarkus 1.1.0.CR1 Application which has the configuration defined in YAML and uses Hibernate. Hibernate should fail to interprete the JDBC-Driver configuration and the application should instantly shut down.

**Configuration**
```yaml
# ....
quarkus:
  datasource:
    url: jdbc:postgresql://localhost:5432/some-database
    driver: org.postgresql.Driver
    username: quarkus
    password: quarkus
  hibernate-orm:
    database.generation: drop-and-create
# ....
```

**Environment (please complete the following information):**
- openjdk version "11.0.2" 2019-01-15
  OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
  OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - Quarkus version or git rev: 1.1.0.CR1

**Additional context**
I renamed the original application.properties so it will not use this one. The following properties-file does work:
```properties
quarkus.datasource.url=jdbc:postgresql://localhost:5432/some-service
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.hibernate-orm.database.generation=drop-and-create
```
