### ISSUE TITLE
Container Port is 0 in Manifests generated by Kubernetes Extension

### ISSUE THREAD

**Issue by cedric-lamalle** [quarkusio/quarkus#6408]
When generating Kubernetes Manifest with `./mvnw package` the resulting containerPort in the Pod Spec is always 0. As a side effect the Service is generated with port and targetPort set to 0 too.

**Expected behavior**

The Pod containerPort should be the same as `quarkus.http.port`, and consequently port and targetPort in service Spec.

**Actual behavior**

The Pod Template Spec generated is:
```yaml
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "cedric.lamalle/code-with-quarkus:1.0.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "code-with-quarkus"
          ports:
          - containerPort: 0
            name: "http"
            protocol: "TCP"
```

And the Service Spec is:

```yaml
  spec:
    ports:
    - name: "http"
      port: 0
      targetPort: 0
```

**To Reproduce**
1. Go to https://code.quarkus.io/
2. Add Kubernetes Extension
3. Click Generate Application
4. Unzip the Application and go to the code-with-quarkus folder
5. Run `./mvnw package`
6. Open target/kubernetes/kubernetes.yml to see the generated manifests

**Configuration**
```properties
# Configuration file
# key = value
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: ``Darwin cedric-lamalle.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64``
 - Output of `java -version`: ``java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)``
 - GraalVM version (if different from Java):  -
 - Quarkus version or git rev: ``1.1.0.Final``

**Additional context**

Editing `pom.xml` and setting the following properties: `quarkus-plugin.version` and `quarkus.platform.version` to `1.0.0.Final` and running `./mvnw clean package` generates the expected Manifests.

I have noticed that if I had the following in `application.properties`:

```properties
kubernetes.ports[0].name=test
kubernetes.ports[0].containerPort=8081
```

The new Port is generated correctly:

Pod Template Spec:

```yaml
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "cedric.lamalle/code-with-quarkus:1.0.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "code-with-quarkus"
          ports:
          - containerPort: 0
            name: "http"
            protocol: "TCP"
          - containerPort: 8081
            name: "test"
            protocol: "TCP"
        serviceAccount: "code-with-quarkus"
```

Service Spec:

```
  spec:
    ports:
    - name: "http"
      port: 0
      targetPort: 0
    - name: "test"
      port: 8081
      targetPort: 8081
```

If I put the following in `application.properties` (kebab case):

```properties
kubernetes.ports[0].name=test
kubernetes.ports[0].container-port=8081
```

The new Port is generated with containerPort equal to 0. Note that the kebab case form is the one documented in:

- https://quarkus.io/guides/kubernetes#configuration-options Table 6
- https://github.com/dekorateio/dekorate/blob/master/assets/config.md#port
