### ISSUE TITLE
Request: Example gitlab-ci.yml with jvm and native builds

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#6531]
Can you add an example gitlab-ci.yml file to the documentation? I haven't been able to find such an example and it would be especially interesting to include tasks for tests, native tests, jvm builds and native builds. Including such an example allows an easier start into Quarkus.

**Comment by gsmet** [comment]
Are you talking about the Quarkus build or the projects we generate?

**Comment by gsmet** [comment]
@andreas-eberle ping?

**Comment by andreas-eberle** [comment]
Oh, sorry, didn't see your answer.

I was talking about an example for how to build a gitlab-ci.yml for my projects I build with Quarkus. So for a user of Quarkus. It would be especially interesting to know how to make a native build with the docker-build in gitlab.

**Comment by gsmet** [comment]
So we could include that in our project template (and probably something for GH actions too) but we would need someone to handle that and maintain it.

Do you volunteer? :)

**Comment by andreas-eberle** [comment]
Unfortunately, I'm not deep into gitlab. That's why I'm asking for the example.

**Comment by garethahealy** [comment]
@andreas-eberle ; hopefully this helps:

install-graal.sh
`
#!/usr/bin/env bash

echo "Downloading GraalVM"
wget -q https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.1/graalvm-ce-java8-linux-amd64-19.3.1.tar.gz
tar zxf graalvm-ce-java8-linux-amd64-19.3.1.tar.gz

echo "Installing GraalVM via gu"

${CI_PROJECT_DIR}/graalvm-ce-java8-19.3.1/bin/gu install native-image
`

.gitlab-ci.yml
`
image: maven:latest

cache:
  paths:
    - .m2/repository/

before_script:
  - apt-get update -qq
  - apt-get install -y -qq build-essential libz-dev zlib1g-dev

build:
  stage: build
  script:
    - chmod +x build-graal.sh && ./build-graal.sh jdk8
    - export GRAALVM_HOME=${CI_PROJECT_DIR}/graalvm-ce-java8-19.3.1
    - mvn clean install -P native
`

**Comment by garethahealy** [comment]
@gsmet ; happy to raise a PR if you can suggest where it should live.

**Comment by andreas-eberle** [comment]
@garethahealy: I was actually able to use the `image: oracle/graalvm-ce:19.3.1-java11`, which has graalvm installed and configured. 

Unfortunately, I still haven't found an good way to run the native build as dockerbuild inside gitlab. However, this might also have to do with our Gitlab instance making this a bit tricky. So I cannot really judge that.

**Comment by zeljkot** [comment]
AFAIK for Docker build you need "dind", and then you can either run CI on Docker image or use whatever you want and use job-specific Docker image just for the build job.

Another option would be to use JIB, but I cannot figure out how to configure credential properly  - it always ends up with 403. I came here because I was wondering did anybody ask for CI guide for jib.

**Comment by k33g** [comment]
👋hello - about Docker, you don't need "dind", you can use Kaniko: https://docs.gitlab.com/ee/ci/docker/using_kaniko.html

**Comment by zeljkot** [comment]
Currently, I am using JIB without neither; it works faster than "dind" and does not require an image with Docker CLI.
```yaml
quarkus:

  container-image:
    group: mycompany/myproject
    registry: ${CI_REGISTRY}
    username: ${CI_REGISTRY_USER}
    password: ${CI_REGISTRY_PASSWORD}
```

**Comment by sladyn98** [comment]
@gsmet This is listed as a good first issue, I could give this a shot, maybe add the configuration template to the repo

**Comment by gsmet** [comment]
@sladyn98 sure!

**Comment by sladyn98** [comment]
As suggested earlier
```
image: maven:latest

cache:
  paths:
    - .m2/repository/

before_script:
  - apt-get update -qq
  - apt-get install -y -qq build-essential libz-dev zlib1g-dev

build:
  stage: build
  script:
    - chmod +x install-graal.sh && ./install-graal.sh jdk8
    - export GRAALVM_HOME=${CI_PROJECT_DIR}/graalvm-ce-java8-19.3.1
    - mvn clean install -P native
``` This could go in the root of the project as 
gitlabci.yml

**Comment by czetsuya** [comment]
I tried the 2 scripts above, unfortunately it doesn't work for me as I got:

```
/usr/bin/bash: line 99: apt-get: command not found
ERROR: Job failed: exit code 1
```

Anybody has an update on how to create a pipeline for Quarkus project in GitLab?

**Comment by garethahealy** [comment]
@czetsuya what image did you use? i had: `maven:latest`

**Comment by czetsuya** [comment]
@garethahealy when I tried to commit that in GitLab I got:
```
$ apt-get update -qq
/usr/bin/bash: line 99: apt-get: command not found
```

**Comment by czetsuya** [comment]
After updating both .gitlab-ci.yaml and install-graal.sh, here's the version that works for me:

https://czetsuya-tech.blogspot.com/2020/08/building-quarkus-in-gitlab.html

**Comment by ledider** [comment]
@czetsuya can you please update the link to your solution? I have the exact same problem

**Comment by czetsuya** [comment]
@ledider updated.

**Comment by jeanphibaconnais** [comment]
Hi, i saw this discussion and like @k33g said, you can use Kaniko to deploy your image.

Based on the example of @czetsuya, I added deployment and this is available [here](https://gitlab.com/-/snippets/2151871). This gitlabci file allows to package a project in jvm mode & native mode and use Kaniko to make one image for each mode.

**Comment by ia3andy** [comment]
You could provide this as a codestart like we do for github-action:
https://github.com/quarkusio/quarkus/tree/main/independent-projects/tools/base-codestarts/src/main/resources/codestarts/quarkus/tooling/github-action

For now the github-action codestart is only used by code.quarkus.io, but we could make that new options in the Quarkus CLI/Maven plugin too

**Comment by jeanphibaconnais** [comment]
Thanks @ia3andy for this response. I will try to initialize it this week, otherwise it will be at the end of august.

**Comment by xasx** [comment]
@kvnb93 looks like there's a `-c` somewhere it does not belong 

> `Error: Unrecognized option: -c`

maybe disclose your `.gitlab-ci.yml` should you not find it

**Comment by xasx** [comment]
> The failing step is run on a GitLab shared runner. Maybe it causes the problem.

That is what I suspect as well. Some kind of special configuration, I guess.

**Comment by jeanphibaconnais** [comment]
Hi, i'm starting to work on this issue.

**Comment by fsomme2s** [comment]
`Error: Unrecognized option: -c`
 +1

but maybe I'm doing it wrong:

```
build_my-fancy-project-core:
    tags:
        - some-tag-required-to-run-on-the-customer-companys-gitlab-runner-on-aws-eu-central1
    image: quay.io/quarkus/ubi-quarkus-mandrel:21.2-java11
    stage: le_build_app_stage_name
    script:
      - cd my-fancy-project-core
      - ./mvnw clean package -Dnative -Dmaven.repo.local=./.m2/repository
    artifacts:
      paths:
        - my-fancy-project-core/target/
        - my-fancy-project-core/.m2/
      expire_in: 4 h
```

without -Dnative and image: maven:3-jdk-11 it works fine (but has slow cold starts on a lambda, of course)

**Comment by Legion2** [comment]
Here is the config I use with gradle projects, it uses jib to create the container images and works with kubernetes executor without dind:
```yaml
quarkus-native-build:
  variables:
    QUARKUS_PACKAGE_TYPE: native
    QUARKUS_CONTAINER_IMAGE_BUILD: "true"
    QUARKUS_CONTAINER_IMAGE_PUSH: "true"
    QUARKUS_CONTAINER_IMAGE_BUILDER: jib
    QUARKUS_CONTAINER_IMAGE_USERNAME: $CI_REGISTRY_USER
    QUARKUS_CONTAINER_IMAGE_PASSWORD: $CI_REGISTRY_PASSWORD
  image: quay.io/quarkus/centos-quarkus-maven:21.3-java11
  script:
    - ./gradlew build -Dquarkus.container-image.image=${CI_REGISTRY_IMAGE}:latest
```

**Comment by einarjohnson** [comment]
> Currently, I am using JIB without neither; it works faster than "dind" and does not require an image with Docker CLI.
> 
> ```yaml
> quarkus:
> 
>   container-image:
>     group: mycompany/myproject
>     registry: ${CI_REGISTRY}
>     username: ${CI_REGISTRY_USER}
>     password: ${CI_REGISTRY_PASSWORD}
> ```

I am trying to achieve this myself. I am using a `@QuarkusTest` which uses a `@QuarkusTestResource` to spin up MySQL and Kafka containers and then I have `@QuarkusIntegrationTest` which extends this class. Everything works perfectly locally when I execute` mvnw -Dquarkus.container-image.build=true clean verify` but the test/failsafe run fails inside Gitlab when it starts running the @QuarkusIntegrationTest. I don't get any logs from the test at all (I've inserted a log.info line in a @BeforeAll) and I am not sure what is going on.  Any ideas what I might be doing wrong?

**Comment by nicolas-vivot** [comment]
Using JIB or Kaniko to build docker images and publish to a registry without docker is the way to go.

But how do you just run a quarkus build when dev services are in use for tests and therefore a docker runtime become a requirement ?

**Comment by einarjohnson** [comment]
@nicolas-vivot , i have tried using the centos-quarkus-maven image without any luck either. does anyone have any suggestions on how to get this working inside Gitlab?

**Comment by jeanphibaconnais** [comment]
Hi @nicolas-vivot , according to your dev services, you can try to use GitLab Services.

**Comment by nicolas-vivot** [comment]
@einarjohnson 
As i mentioned [here](https://github.com/quarkusio/quarkus-images/issues/169), somebody need to add the podman-docker package to the image + a few configuration so that it works.

I don't have the time right now to do it so if any of you can submit a PR on that topic you're welcome.

**Comment by einarjohnson** [comment]
@nicolas-vivot , can you explain further. in order to run @QuarkusIntegration tests inside Gitlab the base image running the tests needs to have podman installed?

**Comment by nicolas-vivot** [comment]
@einarjohnson Yes, Podman but also Podman-docker, if you want to get rid of Docker itself (docker daemon)

I'll try to summarize it.

There are two things to distinguish: building an image from a Docker file without Docker, and running an image without Docker.
We already explained & gave a few tools to build images from a Docker file without Docker, so let's jump into the second and more problematic case: running an image without Docker (e.g without accessing the Docker daemon)

First, why running without Docker: to avoid any security issue if you want to use Gitlab runners running on one of your kubernetes cluster. Gitlab forked Docker and are running their own Docker daemon version, so i would you're good to continue to use Docker in Docker if you use Gitlab shared runners.

Now, coming to Quarkus. In Quarkus, you can run @QuarkusTest using dev services to automatically pop a mongdb instance, or a mssql instance along with your Quarkus application to run the tests on.
The Quarkus DevServices are using the TestContainer library to run these side car containers, expecting to have access to a local Docker daemon to run the images.

So usually on Gitlab, you would use Docker in Docker to give access to the Docker daemon running on the Gitlab runner to your image used to compile/run your Quarkus build.
In order to avoid the Docker in Docker when your Gitlab runner is executed inside a Kubernetes cluster, you have to go with another technology that is not relying on a daemon to run. This is what Podman is right. You can see podman as a rootless docker.

So one idea to be able to run the Quarkus Dev Services without any Docker is to use Podman as the container runtime. But to do that, you need kind of a bridge between what the Dev services are expecting (a docker socket to connect to)
Podman-docker is another library that enable to make that link. Podman will then be able to take over & respond to any request made to a supposed docker socket.

Unfortunately, the current Quarkus image provided as tooling image only embed the GraalVM, Maven, Gradle, Podman and Buildah. This image is originally meant to build images for quarkus native apps and not to run it.

**By adding Podman-docker to that existing image, plus a few configuration as demonstrated in [this blog](https://quarkus.io/blog/quarkus-devservices-testcontainers-podman/), we could use that image not only to build images/containers but also to run it, which is a requirement when it comes to integration tests with Quarkus dev services.**
To make it clear, with that single image you could now build your maven project including running tests that are using Dev Services without having access to the Docker daemon since Podman would take over in place of Docker.

This would make it possible to build a Quarkus project including the integration tests on a gitlab runner anywhere, without having the access to a docker daemon.

**Comment by thedewpoint** [comment]
Just adding another example here. I was having trouble tracking down an example that used maven + jib + native image + deployed to aws ecr. 

```yaml
cache:
  key: mavencache
  paths:
    - ./.m2/repository
services:
  - docker:dind

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_ECR: "<account_id>.dkr.ecr.<region>.amazonaws.com/<repo_name>"
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"


stages:
  - login
  - package
aws:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  stage: login
  script:
    - aws ecr get-login-password --region $AWS_DEFAULT_REGION >> password.txt
  artifacts:
    paths:
      - password.txt
package:
  needs:
    - job: aws
      artifacts: true
  image:
    name: softinstigate/graalvm-maven
    entrypoint: [""]
  stage: package
  script:
    - ls -ltr
    - source /root/.bashrc
    - mvn install $MAVEN_CLI_OPTS -DskipTests
    - mvn package $MAVEN_CLI_OPTS -Pnative -DskipTests -Dquarkus.container-image.image=$AWS_ECR:latest -Dquarkus.container-image.push=true -Dquarkus.container-image.username=AWS -Dquarkus.container-image.password=$(cat password.txt)
```

**Comment by sebastiangraf** [comment]
> `Error: Unrecognized option: -c` +1
> 
> but maybe I'm doing it wrong:
> 
> relevant .gitlab-ci.yml step:
> [...]

If somebody stumbles over this `-c`-Error as well: The image `ubi-quarkus-mandrel`-image has a default entrypoint enabled, you need to override this, then the `-c`-Error disappears.:
```
  image:
    name: quay.io/quarkus/ubi-quarkus-mandrel:22.3.0.1-Final-java17
    entrypoint:
      - ""
```

**Comment by Lory1990** [comment]
Hi everyone,
I am posting my solution for **gitlab cd-ci**,  hope it helps


```
variables: 
  GRAALVM_IMG_TAG: ol7-java17-22.3.0
  GRAALVM_HOME_DIR: /opt/graalvm-ce-java17-22.3.0/

build-jar:
  image: ghcr.io/graalvm/graalvm-ce:$GRAALVM_IMG_TAG
  needs:
    - install-dependencies
    - test
  before_script:
    - yum install wget -y
    - wget https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz --no-check-certificate
    - tar -xvf apache-maven-3.9.2-bin.tar.gz
    - mv apache-maven-3.9.2 /opt/
    - export M2_HOME='/opt/apache-maven-3.9.2'
    - PATH="$M2_HOME/bin:$PATH"
    - export PATH
    - mvn -version
    - export  GRAALVM_HOME=$GRAALVM_HOME_DIR
    - gu install native-image
  script:
    - mvn package -Pnative -DskipTests
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/target
```
