### ISSUE TITLE
Add more information about yaml configuration 

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#6584]
It should be nice if https://quarkus.io/guides/config#yaml could add some information about:

 * how to use yaml config to configure MP REST. I mean how to write yaml configuration for mp-rest `org.acme.restclient.CountriesService/mp-rest/url = http://...` ?
 * is mapped property is supported, if yes please give us a sample.

Thanks!

**Comment by fmhwong** [comment]
@angelozerr You asked about "mapped property".  Did you mean [this](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#environment-variables-mapping-rules)?

**Comment by angelozerr** [comment]
> @angelozerr You asked about "mapped property". Did you mean this?

I mean for instance [quarkus.datasource."datasource-name".driver](https://quarkus.io/guides/all-config#quarkus-agroal_quarkus.datasource.-datasource-name-.driver) where "datasource-name" is dynamic.

**Comment by fmhwong** [comment]
@angelozerr 

`org.acme.restclient.CountriesService/mp-rest/url=https://restcountries.eu/rest` can be represented in yaml as follows:-

```
org:
    acme:
        restclient:
            CountriesService/mp-rest/url: https://restcountries.eu/rest
```

For multiple datasources:
e.g.:
```
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.url=jdbc:h2:tcp://localhost/mem:default
quarkus.datasource.username=username-default
quarkus.datasource.min-size=3
quarkus.datasource.max-size=13

quarkus.datasource.users.driver=org.h2.Driver
quarkus.datasource.users.url=jdbc:h2:tcp://localhost/mem:users
quarkus.datasource.users.username=username1
quarkus.datasource.users.min-size=1
quarkus.datasource.users.max-size=11

quarkus.datasource.inventory.driver=org.h2.Driver
quarkus.datasource.inventory.url=jdbc:h2:tcp://localhost/mem:inventory
quarkus.datasource.inventory.username=username2
quarkus.datasource.inventory.min-size=2
quarkus.datasource.inventory.max-size=12
```
can be represented in yaml as follows:-
```
quarkus:
    datasource:
        driver: org.h2.Driver
        url: jdbc:h2:tcp://localhost/mem:default
        username: username-default
        min-size: 3
        max-size: 13
        users:
            driver: org.h2.Driver
            url: jdbc:h2:tcp://localhost/mem:users
            username: username1
            min-size: 1
            max-size: 11
        inventory:
            driver: org.h2.Driver
            url: jdbc:h2:tcp://localhost/mem:inventory
            username: username2
            min-size: 2
            max-size: 22
```

I can add an example on how to rest client URL in the https://quarkus.io/guides/config#yaml.

**Comment by angelozerr** [comment]
@fmhwong thank you for your feedback.

So the basic idea is to split with '.' (like I did in vscode-quarkus)

For mapped property like `quarkus.log.category."io.quarkus".level=DEBUG` do we split "io.quarkus" too ?

**Comment by fmhwong** [comment]
@angelozerr it will look like this

```
quarkus:
    log:
        category:
            "io.quarkus":
                    level: DEBUG
```
