### ISSUE TITLE
Kubernetes Extension and Secrets generates incorrect deployment file.

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6826]
**Describe the bug**

When trying to configure the generation of Kubernetes deployment file with secrets as volume, it ignores the properties.

**Expected behavior**

File should be generated correctly.

**Actual behavior**

Defaults are used instead of the configured ones. 

**To Reproduce**

```
kubernetes.env-vars[0].name=GITHUB_API_KEY_TOKEN
kubernetes.env-vars[0].secret=greeting-security
kubernetes.env-vars[0].value=github.api.key.token

kubernetes.mounts[0].name=github-token
kubernetes.mounts[0].path=/deployment/github
kubernetes.mounts[0].read-only=true

kubernetes.secret-volumes[0].volume-name=github-token
kubernetes.secret-volumes[0].secret-name=greeting-security
```

The generated YAML file is:

```yaml
spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          - name: "GITHUB_API_KEY_TOKEN"
            valueFrom:
              secretKeyRef:
                key: "github.api.key.token"
                name: "greeting-security"
                optional: false
          image: "quarkus/greeting-started-kubernetes-secrets:1.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "greeting-app"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
          volumeMounts:
          - mountPath: "/deployment/github"
            name: "github-token"
            readOnly: false
            subPath: ""
        volumes:
        - secret:
            defaultMode: 384
            optional: false
```

Notice that readOnly configuration is ignored as well as secret-volumes configuration which is empty with defaults.
