### ISSUE TITLE
Kubernetes: liveness and readiness probes ignore the `quarkus.http.root-path` setting

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#6833]
**Describe the bug**

When I configure `quarkus.http.root-path`, the `/health` endpoint is moved under it (as well as `/metrics`, but that is irrelevant here). That seems to be intentional, per https://github.com/quarkusio/quarkus/issues/3745. The generated Kubernetes probes don't reflect that, however.

**Expected behavior**

Autogenerated liveness and readiness probes point to the real health endpoint, even if `quarkus.http.root-path` is defined.

**Actual behavior**

If `quarkus.http.root-path` is defined, the autogenerated liveness and readiness probes point to a non-existing path and the pod never starts successfully.

**To Reproduce**

```properties
quarkus.http.root-path=/api
```

The generated Kubernetes YAML looks like:

```yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  ...
  name: "http"
spec:
  ...
  template:
    ...
    spec:
      containers:
      - ...
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
          ...
        ...
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/ready"
            port: 8080
            scheme: "HTTP"
          ...
```

The OpenShift YAML is identical in this regard.

However, the health endpoint is at `/api/health`.

**Environment (please complete the following information):**
 - Quarkus version or git rev: `76fcdc4b8e6c113c53bb55f965a116afdee5290a`
