### ISSUE TITLE
Add serviceaccountname property for Kubernetes extension

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6834]
**Description**

`serviceaccountname` cannot be set in Kubernetes extension.

**Implementation ideas**

`serviceaccount` and `serviceaccountname` cannot be set in Kubernetes extension and it should be possible:

```
spec:
  containers:
  - image: alpine:3.7
    imagePullPolicy: IfNotPresent
    name: tmp
    resources: {}
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: vault-token-mm5qx
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: vault
  serviceAccountName: vault
```

This is really important for Vault extension for using the Kubernetes Auth method.

**Comment by ShubhamRwt** [comment]
Hello @geoand , I would like to work on this issue.

**Comment by geoand** [comment]
Feel free to pick it up @ShubhamRwt

**Comment by ShubhamRwt** [comment]
Can you give me a brief description for this issue, It would really help. Thankyou

**Comment by geoand** [comment]
@alexsoto care you provide some more info?

**Comment by lordofthejars** [comment]
If I remember correctly it was about be able to set the serviceaccountname
from application.properties, but maybe this is possible right now

**Comment by geoand** [comment]
@ShubhamRwt actually I think that myself and / or @iocanel will handle this one.

The reason is that I think there are multiple things that need to be done here.

**Comment by ShubhamRwt** [comment]
Ok @geond. I will start up with some other issues.

**Comment by smoell** [comment]
Hey, I was wondering if there's an update regarding the issue. It would be great to have this feature, because Amazon EKS is using IAM roles for service accounts which basically means, you can configure pods to use IAM roles: https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html

A typical deployment looks like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: my-app
        image: public.ecr.aws/nginx/nginx:1.21
```
