### ISSUE TITLE
Native Build in OpenShift is failing

### ISSUE THREAD

**Issue by aklemp** [quarkusio/quarkus#7166]
**Describe the bug**
Building a native Quarkus application in OpenShift 3.11 is failing. The same works locally without problems (on Debian with Docker build and GraalVM 19.3.1-java8).

**Expected behavior**
The build is successful like it is locally.

**Actual behavior**
There are a lot of errors but it seems like OpenShift is trying to augment the application with features, that are not supported natively.

```
[getting-started-1.0-SNAPSHOT-runner:205]     analysis: 128,603.97 ms
Error: Unsupported features in 5 methods
Detailed message:
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object java.util.concurrent.locks.AbstractQueuedSynchronizer$Node
	object java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject
	object java.util.concurrent.LinkedBlockingQueue
	object com.instana.agent.loader.v1_3_23.AgentUrlLogger
	object com.instana.agent.loader.v1_3_23.AgentLogDispatcher
	object java.util.InstanaLoggerV4
	field java.util.InstanaLoggerV4.INSTANCE
Error: Detected a started Thread in the image heap. Threads running in the image generator are no longer running at image run time.  To see how this object got instantiated use -H:+TraceClassInitialization. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image run time by using the option --initialize-at-build-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: 	object sun.net.www.http.KeepAliveCache
	field sun.net.www.http.HttpClient.kac
Error: No instances of java.net.SocketInputStream are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 	object java.io.BufferedInputStream
	object sun.net.www.http.HttpClient
	object sun.net.www.http.KeepAliveEntry
	object java.lang.Object[]
	object sun.net.www.http.ClientVector
	object java.util.HashMap$Node
	object java.util.HashMap$Node[]
	object sun.net.www.http.KeepAliveCache
	field sun.net.www.http.HttpClient.kac
Error: No instances of java.net.SocketOutputStream are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 	object java.io.BufferedOutputStream
	object java.io.PrintStream
	object sun.net.www.http.HttpClient
	object sun.net.www.http.KeepAliveEntry
	object java.lang.Object[]
	object sun.net.www.http.ClientVector
	object java.util.HashMap$Node
	object java.util.HashMap$Node[]
	object sun.net.www.http.KeepAliveCache
	field sun.net.www.http.HttpClient.kac
Error: No instances of java.net.SocksSocketImpl are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use -H:+TraceClassInitialization.
Trace: 	object java.net.Socket
	object sun.net.www.http.HttpClient
	object sun.net.www.http.KeepAliveEntry
	object java.lang.Object[]
	object sun.net.www.http.ClientVector
	object java.util.HashMap$Node
	object java.util.HashMap$Node[]
	object sun.net.www.http.KeepAliveCache
	field sun.net.www.http.HttpClient.kac
```

**To Reproduce**
* Create new project with the contents of https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started.
* Have to set `MAVEN_MIRROR_URL` and `HTTP_PROXY_NONPROXYHOST` in `.s2i/environment` in our environment.
* Create a pipeline (we are using GitLab CI with necessary plugins to interact with openshift). The relevant commands in the pipeline are.
```
oc create imagestreamtag ubi-quarkus-native-s2i:19.3.1-java8 --from-image=quay.io/quarkus/ubi-quarkus-native-s2i:19.3.1-java8
oc process -f openshift/build-native.yaml | oc apply -f -
oc start-build getting-started --from-dir=. --wait
```
Build-Config in `openshift/build-native.yaml`:
```
---

kind: Template
apiVersion: v1
metadata:
  name: getting-started
labels:
  template: getting-started

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: getting-started
      labels:
        app: getting-started
    spec:
      lookupPolicy:
        local: true
      dockerImageRepository: ''
      tags:
        - name: latest
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: getting-started
      labels:
        app: getting-started
    spec:
      runPolicy: SerialLatestOnly
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 1
      source:
        binary: {}
        type: Binary
      strategy:
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: ubi-quarkus-native-s2i:19.3.1-java8
        type: Source
      output:
        to:
          kind: ImageStream
          name: getting-started
      resources:
        requests:
          memory: 2Gi
        limits:
          memory: 10Gi
```

**Configuration**
Using a two-stage build to create a minimal image. The problem here is already building the native application (the first stage).

**Screenshots**
n/a

**Environment (please complete the following information):**
* Quarkus 1.2.0.Final
* GraalVM 19.3.1-java8
* OpenShift 3.11
* builder image ubi-quarkus-native-s2i:19.3.1-java8

**Additional context**
n/a
