### ISSUE TITLE
Using an import.sql file doesn't seem to get loaded with H2 in tests

### ISSUE THREAD

**Issue by bnjns** [quarkusio/quarkus#7290]
**Describe the bug**
I'm using H2 for tests so that I don't have to worry about booting up a clean database instance both locally and in CI. Following the guides, I have the configuration outlined below, and the test classes are annotated with 

```kotlin
@QuarkusTest
@QuarkusTestResource(H2DatabaseTestResource::class)
```

When the tests are started I can see that Hibernate is creating the database schema, but the `import.sql` (which is located in `src/main/resources`) doesn't get run. I have a test that simply queries an endpoint that lists all entities in the database - this returns an empty list. Using `CDI.current().select(Repository::class.java).get()` and inspecting the repository manually also returns no results.

Some detailed debugging has highlighted one (slightly separate) issue - the `HibernateOrmProcessor` seems to want to load this relative to the `build/classes/kotlin/main` directory, so the test fails to boot as the `import.sql` file doesn't exist in this directory. Doing a bit of path "hacking", I can set the path to `../../../resources/main/import.sql` which now boots, but it's then still not actually run.

I've kinda having to resort to calling a separate endpoint that creates records in the db to test the retrieval endpoints, but it's really icky.

**Expected behavior**
When the test starts, Hibernate generates the database structure and then runs the `import.sql` file to insert any test data. This data is then returned by any integration tests that then call the application to query the database.

**Actual behavior**
Hibernate generates the database structure, but the data isn't imported into the database.

**To Reproduce**
1. Create a new Kotlin and Gradle project via code.quarkus.io with `hibernate-orm-panache` and `quarkus-test-h2`
2. Write a basic REST endpoint that returns the result of `.findAll().list<EntityType>`
3. Create an `import.sql` file in `src/main/resources` that adds some data to the table
4. Write a test to verify that the result isn't empty

If needed, I could make a repo with this for you to work from.

**Configuration**
```yaml
"%test":
  quarkus:
    datasource:
      url: jdbc:h2:tcp://localhost/mem:test
      driver: org.h2.Driver
      username: sa
      password: 
    hibernate-orm:
      sql-load-script: import.sql
      log:
        jdbc-warnings: true
        sql: true
      database:
        generation: drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin beans.lan 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "1.8.0_232"
 - GraalVM version (if different from Java): GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - Quarkus version or git rev: 1.1.1.Final

**Additional context**
Using Kotlin 1.3.61, compiled down to Java 1.8
