### ISSUE TITLE
defaultMode of a ConfigMap volume is 600 (decimal!) by default

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#7722]
**Describe the bug**

When I specify a ConfigMap volume using the Quarkus Kubernetes extension configuration properties, the volume has by default a `defaultMode` of `600`:

```yaml
      volumes:
      - configMap:
          defaultMode: 600
          name: "app-config"
          optional: false
        name: "app-config"
```

This is a decimal number, because it doesn't begin with `0`.

The Fabric8 Kubernetes client even warns about that: `Invalid value: 600: must be a number between 0 and 0777 (octal), both inclusive`.

The documentation says that default value here is `384` (which is `0600`). The corresponding `*Config` classes have `@ConfigItem(defaultValue = "0600")`, but apparently, when that string is converted to `int`, it's parsed as decimal, not octal.

**Expected behavior**
Default value of `defaultMode` is either `384` or `0600`.

**Actual behavior**
Default value of `defaultMode` is `600`.

**To Reproduce**
1. Add the `quarkus-kubernetes` extension.
2. Specify a ConfigMap in `application.properties`.
3. Run `mvn clean package -DskipTests`.
4. See `target/kubernetes/*.yml`.

**Configuration**
```properties
quarkus.kubernetes.deployment-target=openshift
quarkus.openshift.config-map-volumes.app-config.config-map-name=app-config
quarkus.openshift.mounts.app-config.path=/deployments/config
```
