### ISSUE TITLE
Gradle quarkusDev

### ISSUE THREAD

**Issue by IZharov** [quarkusio/quarkus#7934]
Hello,
I have problems launching quarkus.
I am using Kotlin 1.3.61, Java 11, quarkus 1.3.0.Final.
My build.gradle:

```
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.3.61"
    id "org.jetbrains.kotlin.kapt" version "1.3.61"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.3.61"
    id "com.github.johnrengelman.shadow" version "5.0.0"
    id 'io.quarkus' version '1.3.0.Final'
}

version "0.1.1"
group "org.zharov.analytic"

repositories {
    mavenCentral()
    maven { url "https://jcenter.bintray.com" }
}


configurations {
    developmentOnly
}

dependencies {
    implementation(enforcedPlatform("io.quarkus:quarkus-bom:$quarkusVersion"))
    implementation("io.quarkus:quarkus-resteasy-jackson")
    implementation("io.quarkus:quarkus-resteasy-jsonb")
    implementation("io.quarkus:quarkus-rest-client")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-config-yaml")
    testImplementation("io.quarkus:quarkus-junit5")
    implementation("org.apache.camel.quarkus:camel-quarkus-platform-http:1.0.0-M4")
    implementation("org.apache.camel.quarkus:camel-quarkus-jackson:1.0.0-M4")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
}

test.classpath += configurations.developmentOnly

allOpen {
    annotation("javax.enterprise.context.ApplicationScoped")
}

test {
    useJUnitPlatform()
}

compileKotlin {
	kotlinOptions {
	    jvmTarget = '1.8'
	    javaParameters = true
	}
}

compileTestKotlin {
	kotlinOptions {
	    jvmTarget = '1.8'
	    javaParameters = true
	}
}

shadowJar {
    mergeServiceFiles()
}

```

```
@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello(): String {
        return "test"
    }

    @GET
    @Path("/name")
    @Produces(MediaType.TEXT_PLAIN)
    fun helloName(): String {
        return "name"
    }
}
```

I face a problem that when I run through a Gradle quarkusDev, when I contact http://localhost:8080/hello return  404 not found, but if I change the request during work, it will work out, so with each request. Also, if a class with a request uses another class and change the request while working, it return: 
500
Error restarting Quarkus
java.lang.RuntimeException: Compilation failed. import 

java.lang.RuntimeException: Compilation failed. import org.zharov.analytic.service.MediaService
D:\Projects\Intellij\test_project\src\main\kotlin\org\zharov\analytic\controller\MediaController.kt:3:41
Reason: Unresolved reference: service
class MediaController(@Inject private val mediaService: MediaService) {
D:\Projects\Intellij\test_project\src\main\kotlin\org\zharov\analytic\controller\MediaController.kt:11:73
Reason: Unresolved reference: MediaService
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:82)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:174)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:194)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:125)
	at org.apache.camel.quarkus.core.devmode.CamelHotReplacementSetup$1.run(CamelHotReplacementSetup.java:36)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)

```
@Path("/media")
class FaceDetectionController(@Inject private val mediaService: MediaService) {


    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    fun saveDetection(media: MediaDto): Response {
        return Response.ok().build()
    }
}
```

application.yml:
```
quarkus:
  http:
    host: localhost
    port: 8080
    cors:
      enabled: true
  images:
    path: C:/images/



application-info:
  name: quarkus-service
  framework:
    name: Quarkus
    release-year: 2020


camel:
  main:
    xml-routes: file:src/main/resources/camel-routes.xml
  properties:
    prefixToken: {{
    suffixToken: }}
  context:
    name: quarkus-camel-example
  file:
    route:
      folder: src/main/resources/file
    repeat:
      interval: 30s
    split:
    parallel: false
```
Error occurs without camel.
How can I fix this? thanks
