### ISSUE TITLE
Generated kubernetes manifests contain wrong port in health probes

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#8090]
**Describe the bug**
When `quarkus.http.port=9090` and the `quarkus-smallrye-health` extensions is present, it is expected that the health and liveness probes will use that port (instead of the the default.)

**Expected behavior**
Port `9090` is used in health and liveness probes.

**Actual behavior**
The liveness probe (readiness is the same) looks like this:

```
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
```
**Environment (please complete the following information):**
 - Quarkus version or git rev: `1.3.0.Final`
