### ISSUE TITLE
quarkus.kubernetes.image-pull-policy ignored

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#8091]
I put this in `application.properties`

`quarkus.kubernetes.image-pull-policy=Always`

After performing:

```
mvn clean package
```

and in `target/kubernetes/kubernetes.yaml`

I have this : 

```
image: "docker.example.com:5000/iep/quarkus-k8s-hello:latest"
imagePullPolicy: "IfNotPresent"
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: "/health/live"
    port: 8080
    scheme: "HTTP"
  initialDelaySeconds: 0
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 10
name: "quarkus-k8s-hello"
```
