### ISSUE TITLE
Kubernetes extension replicas configuration

### ISSUE THREAD

**Issue by cemnura** [quarkusio/quarkus#8273]
**Describe the bug**

Im trying out the Kubernetes extension have stumbled upon a bug. I have the following dependencies

     <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kubernetes</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-container-image-jib</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>
I preferred the yaml config option and have the following configuration.

```yaml
quarkus:
  kubernetes:
    part-of: hr-app
    name: employee-service
    version: 1.0.0
    replicas: 3
```

Yet the generated Kubernetes manifest file does not set the replicas as 3

```yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-03-27 - 21:43:23 +0000"
    app.quarkus.io/commit-id: "809f76f1b476ea1dc07cf311d079baceeb414d21"
  labels:
    app.kubernetes.io/name: "employee-service"
    app.kubernetes.io/part-of: "hr-app"
    app.kubernetes.io/version: "1.0.0"
  name: "employee-service"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "employee-service"
      app.kubernetes.io/part-of: "hr-app"
      app.kubernetes.io/version: "1.0.0"
```

**Expected behavior**
Generated Kubernetes manifest file replicas are set correctly.

**Actual behavior**
Generated Kubernetes manifest file replicas are not set correctly. 

It seems as quarkus.kubernetes.replicas is ignored.

**To Reproduce**
1. Generate project

 mvn io.quarkus:quarkus-maven-plugin:1.3.1.Final:create \
    -DprojectGroupId=com.acme \
    -DprojectArtifactId=getting-started \
    -DprojectVersion=1.0 \
    -DclassName="org.my.group.MyResource"

2. Add extensions
./mvnw quarkus:add-extension -Dextensions="quarkus-kubernetes,quarkus-container-image-jib,quarkus-config-yaml"

3. Add the following configuration to application.yaml to resources
```yaml
quarkus:
  kubernetes:
    part-of: getting-started
    name: getting-started
    version: 1.0.0
    replicas: 3
```
3. Package
./mvnw package
4. Observe generated Kubernetes Manifest 
target/kubernetes/kubernetes.yml

**Configuration**
```yaml
quarkus:
  kubernetes:
    part-of: getting-started
    name: getting-started
    version: 1.0.0
    replicas: 3
```

**Environment:**
 - Output of `uname -a` or `ver`:
 Linux localhost.localdomain 5.0.9-301.fc30.x86_64 #1 SMP Tue Apr 23 23:57:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:
 openjdk version "11.0.2" 2019-01-15
 OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
 OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
 - GraalVM version (if different from Java):
 N/A
 - Quarkus version or git rev:
 1.3.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):
 Apache Maven 3.6.3
