### ISSUE TITLE
quarkus-swagger-ui treat string($date-time) as a regular string

### ISSUE THREAD

**Issue by rainmanhhh** [quarkusio/quarkus#8635]
**Describe the bug**
swagger-ui says the param type is "string(query)" but schema returned by /openapi is:
```Yaml
paths:
  /datetime:
    get:
      parameters:
      - name: i
        in: query
        schema:
          format: date-time
          type: string
```

**Expected behavior**
query param "i" type should be "string($date-time)" in swagger-ui

**Actual behavior**
query param "i" type is "string"

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)
