### ISSUE TITLE
Kubernetes probes not added when using container-image.name

### ISSUE THREAD

**Issue by jorsol** [quarkusio/quarkus#8733]
**Describe the bug**
`livenessProbe` and `readinessProbe` are not added to the final Kubernetes Deployment file when the `quarkus.container-image.name` property is set

**Expected behavior**
Probes added to the Deployment:
```
***
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "registry.gitlab.com/jorsol/kubernetes-quickstart:1.0-SNAPSHOT"
        imagePullPolicy: "Always"
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/live"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: "kubernetes-quickstart"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/health/ready"
            port: 8080
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
      serviceAccount: "kubernetes-quickstart"
```

**Actual behavior**
```
***
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: "jorsol/demo:1.0-SNAPSHOT"
        imagePullPolicy: "Always"
        name: "demo"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "demo"
```

**To Reproduce**
1. Create project with -Dextensions="kubernetes, jib, smallrye-health"
2. `mvn clean package && cat target/kubernetes/kubernetes.yml`
3. `mvn clean package -Dquarkus.container-image.name=demo && cat target/kubernetes/kubernetes.yml`

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.4.0.CR1

cc @iocanel
