### ISSUE TITLE
cleaner kubernetes.yaml generation 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9280]
**Description**
while working and comparing our yaml with example yaml i noticed a few things that could make ours a bit nicer:

- [ ] don't add quotes unless needed (i.e. [MINIMIZE_QUOTES](https://www.javadoc.io/doc/com.fasterxml.jackson.dataformat/jackson-dataformat-yaml/2.7.5/com/fasterxml/jackson/dataformat/yaml/YAMLGenerator.Feature.html#MINIMIZE_QUOTES) )
- [ ] don't generate labels/annotations for vcs and similar if those values are not available, i..e. "<<unknown>>" looks  noisy

i.e. generate this:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/build-timestamp: "2020-05-13 - 20:16:21 +0000"
  labels:
    app.kubernetes.io/name: jugchdemo
    app.kubernetes.io/version: 1.0-SNAPSHOT
  name: jugchdemo
```

instead of 

```yaml
---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations:
    app.quarkus.io/vcs-url: "<<unknown>>"
    app.quarkus.io/build-timestamp: "2020-05-13 - 20:16:21 +0000"
    app.quarkus.io/commit-id: "<<unknown>>"
  labels:
    app.kubernetes.io/name: "jugchdemo"
    app.kubernetes.io/version: "1.0-SNAPSHOT"
  name: "jugchdemo"
```
