### ISSUE TITLE
Kafka mbean fails due to conflicting client names

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#9799]
**Describe the bug**
If there is more than one Kafka topic configured and different client names are not configured for each topic, warning is generated during the startup for each topic:

```
Error registering AppInfo mbean: javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=xxxxx 
```

**Expected behavior**
It should not be a problem to use the same client name for each topic.

**Actual behavior**
Log is flooded with irrelevant warnings.

**To Reproduce**
1. Define client at connector level
2. Define multiple topics without the client
3. Start the application

**Configuration**

```
messaging:
  connector:
    smallrye-kafka:
      client:
        id: my-client

  incoming:
    topic1:
      connector: smallrye-kafka
      topic: topic1

    topic2:
      connector: smallrye-kafka
      topic: topic2

    topic3:
      connector: smallrye-kafka
      topic: topic3
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.19041.264]
 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.5.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
(Add any other context about the problem here.)
