### ISSUE TITLE
After upgrade to Quarkus 1.5.1 @Transactional not save changes

### ISSUE THREAD

**Issue by DemiusAcademius** [quarkusio/quarkus#9961]
After upgrade to Quarkus 1.5.0 (and 1.5.1 also) @Transactional not save changes to database

In version 1.4.2 all changes commited to Oracle db
with version 1.5.1 I expect same bahaviour

but changes not saved

**Configuration in yaml**
```yaml
quarkus:
  resteasy:
    gzip:
      enabled: true
      max-input: 10M

  datasource:
    url: jdbc:oracle:thin:@10.10.112.1:1521:ACC
    driver: oracle.jdbc.OracleDriver
    username: FISC
    password: "${FISC_PASSWORD}"
    jdbc:
      initial-size: 1
      min-size: 1
      max-size: 4
      background-validation-interval: 5M
      acquisition-timeout: 10
      leak-detection-interval: 5M

  hibernate-orm:
    dialect: org.hibernate.dialect.Oracle12cDialect
    database:
      generation: none

  log:
    category:
      "io.quarkus.category":
        level: TRACE

com:
  sia:
    restclient:
      auth:
        CloudprintAuthService/mp-rest/url: https://api-int.bytemill.io/auth/realms/apa-canal
        CloudprintAuthService/mp-rest/scope: javax.inject.Singleton
      api:
        CloudprintApiService/mp-rest/url: https://api-int.bytemill.io/api/event
        CloudprintApiService/mp-rest/scope: javax.inject.Singleton

cloudprint:
  config:
    apikey: d3b38a19-8f88-466e-8553-a68a6f667498
    client-id: core-app
    client-secret: "${FP_CLIENT_SECRET}"
    scope: openid api
    username: api-user
    password: vEq6Sapp9g8F
  schedule:
    printing: "*/2 * * * * ?"
    heartbit: "0 */5 * * * ?"
```

**not working snipped**

```java
@Transactional
public List<JobDto> fetchAndPrepareJobs() {
    var timestamp = new Timestamp(System.currentTimeMillis());

    var jobs = FPJob.loadAllPendings();
    for (var job : jobs) {
        if (job.printerId != null) {
            FPPrinterStatus fpStatus = FPPrinterStatus.findById(job.printerId);
            fpStatus.processing = true;
            fpStatus.sysdate = timestamp;
            fpStatus.persist();
            LOG.info("set printer processing status to true");
        }

        job.sysdateRegistered = timestamp;
        job.persist();

        LOG.info("job " + job.id + " with registered status persisted");
    }
        
    // return Collections.emptyList();
    return jobs.stream().map(JobDto::new).collect(Collectors.toUnmodifiableList());
}
```

**Query in FPJob PanacheEntity**

```java
public static List<FPJob> loadAllPendings() {
    var startDT = LocalDateTime.now().minus(10, ChronoUnit.MINUTES);
    var startDate = Date.from(startDT.atZone(ZoneId.systemDefault()).toInstant());

    return find("#load-all-pending-jobs", startDate).withLock(LockModeType.PESSIMISTIC_WRITE).list();
}
```

**but this code is working**
```java
@Transactional
public void removeOldJobs() {
    var startDT = LocalDateTime.now().truncatedTo(ChronoUnit.DAYS).minus(6, ChronoUnit.DAYS);
    var startDate = java.util.Date.from(startDT.atZone(ZoneId.systemDefault()).toInstant());
    FPJob.delete("sysdateReq < ?1", startDate);
}
```
