### ISSUE TITLE
Spring-Cloud-Config-Client Configuration not working

### ISSUE THREAD

**Issue by fluoxa** [quarkusio/quarkus#9973]
The settings for your Spring-Cloud-Config-Client  are ignored when you configure them in your application.yml (using quarkus-config-yaml extension). Configuring them in application.properties are working normally.

Quarkus Version: 1.5.1.Final

**Expected behavior**
Spring-Cloud-Config-Client configuration should also work in application.yml (like in quarkus 1.4)

**Actual behavior**
Spring-Cloud-Config-Client configuration in application.yml is ignored

quarkus:
..application:
....name: xxx
..spring-cloud-config:
....enabled: true
....url: http://localhost:8889
....fail-fast: true

does not work

quarkus.application.name=xxx
quarkus.spring-cloud-config.enabled=true
quarkus.spring-cloud-config.url=http://localhost:8889
quarkus.spring-cloud-config.fail-fast=true

works

**Comment by geoand** [comment]
I tried this both with our integration test (https://github.com/quarkusio/quarkus/tree/a45ee4da5d57255f8d01af48abf0ea6d7f83c1a6/integration-tests/spring-cloud-config-client) updated for YAML of course and with a new project and both worked fine.

For reference, here is the YAML I used:

```yaml
quarkus:
  application:
    name: some-test
  spring-cloud-config:
    url: http://localhost:8089
    username: user
    password: pass
    enabled: true

```
